### ISSUE TITLE
XRAY分流,DNS解析没有分流

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1002]
导致自定义规则的解析服务器依然是默认服务器的解析结果.
例如 cn.nytimes.com 分流使用美国服务器,
解析到的ip确是香港cdn的,ping.pe检测到美国服务器连接有150ms的延迟.

**Comment by yunxi993** [comment]
分流确实好像出问题了，解析的都是默认节点的IP，并不是分流节点的IP

**Comment by xiaorouji** [comment]
使用Xray内置路由实现的分流，透明代理下的DNS还需要加强。如果用的是socks应该没问题的。
