### ISSUE TITLE
有遇到过升级passwall提示“找不到出口接口”的吗？

### ISSUE THREAD

**Issue by aglent** [xiaorouji/openwrt-passwall#1003]
从4-12升级到4-15
节点能用 只是日志里有一堆提示“找不到出口接口：，1分钟后再重试(5/5)” 后面是不同的ip地址 重试5次后不再提示
不知道这表示什么？

**Comment by WYC-2020** [comment]
保留配置升级？

**Comment by aglent** [comment]
> 
> 
> 保留配置升级？

是的 和保留配置有关？

**Comment by WYC-2020** [comment]
@aglent pw最近逻辑变化比较多，你可以试下全新，你先把配置导出来，全新安装后，你在试下还原或者 手工进行替换配置即可，起始配置也不多

**Comment by aglent** [comment]
> 
> 
> @aglent pw最近逻辑变化比较多，你可以试下全新，你先把配置导出来，全新安装后，你在试下还原或者 手工进行替换配置即可，起始配置也不多

全新配置 可以了 谢谢
