### ISSUE TITLE
发现一个奇怪的问题

### ISSUE THREAD

**Issue by kxjhcmc** [xiaorouji/openwrt-passwall#1004]
最近几个版本出现的，同一个节点，使用软路由透明代理，看视频速度很慢，用该节点的socks代理，看视频就很快，用电脑版的v2rayn速度也快，感觉是透明代理的问题。我开启了ipv6透明代理，关闭ipv6透明代理后，速度依然有这样的差异，很是奇怪。

**Comment by kxjhcmc** [comment]
根据最新测试，还是和ipv6透明代理有关系，上面说关闭后，一样慢，是因为没有清空DNS缓存导致的，可能IPV6透明代理还是有点问题吧

**Comment by xiaorouji** [comment]
你先确认你的内网ipv6类型是否NAT6

**Comment by xiaorouji** [comment]
Ping @ShanStone

**Comment by ShanStone** [comment]
想不出是哪里的问题。
如果是开启IPv6后视频慢有可能是优先走的IPv6，现在IPv6链路速度大部分是不如IPv4的，可以理解，但是关闭ipv6透明代理后相关防火墙规则都被清理掉了，不应该出现这个问题，IPv6的dns我并没有改动啊

**Comment by kxjhcmc** [comment]
> 想不出是哪里的问题。
> 如果是开启IPv6后视频慢有可能是优先走的IPv6，现在IPv6链路速度大部分是不如IPv4的，可以理解，但是关闭ipv6透明代理后相关防火墙规则都被清理掉了，不应该出现这个问题，IPv6的dns我并没有改动啊

可能和tproxy 效能有关系，因为如果ipv6透明代理后，访问国外网站，是通过外网服务器的IPV6访问，理论不会影响速度，因为连接地址使用的ipv4啊，并不是用的ipv6的地址进行连接。下面这个问题和这个情况类似。
https://github.com/XTLS/Xray-core/issues/325

**Comment by kxjhcmc** [comment]
> 你先确认你的内网ipv6类型是否NAT6

是否NAT6不知道如何确定，但是如果开启的话，路由器，电脑等都能获取到IPV6地址，且ipv6test也能通过，连接服务器的地址依然用的IPV4地址，不是用的ipv6进行连接，透明代理目的是解决开启ipv6后电脑默认使ipv6进行直连，不能连接代理服务器的问题。

**Comment by Bearljj** [comment]
应该跟ipv6没关系，你看看透明代理的那个Xray自己的流量的屏蔽机制生效了么，我之前用Gid方式就不太行，后来换了mark方式就没问题了

**Comment by Bearljj** [comment]
而且透明代理的DNS貌似更复杂，具体还是要看配置

**Comment by kxjhcmc** [comment]
> 而且透明代理的DNS貌似更复杂，具体还是要看配置

DNS 使用的xraydns doh,解析的域名确实生效，使用ping命令验证，解析出的域名和vps上ping出的ipv6地址完全一致，连接服务器使用的ipv4地址，所以不会影响连接速度，ipv6透明代理确实可以用，开了后，谷歌等网址不会出现直接连接ipv6导致代理失效的情况，就是速度很慢，感觉就是转发性能的问题。

**Comment by xiaorouji** [comment]
试试最新源码？加了个链，据说可以提高性能
