### ISSUE TITLE
请教各位大佬一个问题！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall#1005]
那个分流总节点是什么作用，里面的youtube和奈飞那些分流这个容易理解，但里面的广告规则和china，passwall不应该是在防火墙列表或者是中国列表外的流量才会让passwall接管吗？这样还可以去广告还是只能去掉fq流量的广告？既然需要fq的流量才通过passwall按管，那样china还要分流？一直搞不明白这个分流总节点的作用！还有分流里面又有默认节点，默认节点前置这些

**Comment by doegeenon** [comment]
作用在于全局模式下，china选择直连，广告选择blackhole，其他什么tg nf按需选择，默认和前置节点选择自己使用的节点，这样能达到白名单+广告过滤的效果（cn全部直连，屏蔽广告，其余都走代理）

**Comment by snakwu** [comment]
@doegeenon  哦，明白了，谢谢大佬，因为全局就已经是接管了所有流量，让passwall来分流了，这样思路就通了，像我用gfw模式的，就不需要分流了！

**Comment by CoolCollin** [comment]
前置节点意义或者作用到底是什么？

**Comment by snakwu** [comment]
@CoolCollin  没猜错的话，就是通过前置代理的节点去中转分流节点，因为有一些人看视频的节点快，但是浏览网页慢，这时就通过前置去中转分流节点比较快

**Comment by monokoo** [comment]
> @doegeenon 哦，明白了，谢谢大佬，因为全局就已经是接管了所有流量，让passwall来分流了，这样思路就通了，像我用gfw模式的，就不需要分流了！

这个时候是不是局域网客户端的访问控制功能如果设置为黑名单之类的类型，去广告也就无效了？

**Comment by snakwu** [comment]
@monokoo  应该有个优先级的吧，我只用gfw模式，没有测试
