### ISSUE TITLE
能更新添加这样的高级路由设置吗？

### ISSUE THREAD

**Issue by spphinslove** [xiaorouji/openwrt-passwall#1006]
https://github.com/Loyalsoldier/v2ray-rules-dat
![图片](https://user-images.githubusercontent.com/11383988/108594294-28c15b00-73b4-11eb-8bdd-4f9b0c9a3d7f.png)

**Comment by xiaorouji** [comment]
现在不是可以？？？？

**Comment by doegeenon** [comment]
> https://github.com/Loyalsoldier/v2ray-rules-dat
> ![图片](https://user-images.githubusercontent.com/11383988/108594294-28c15b00-73b4-11eb-8bdd-4f9b0c9a3d7f.png)

分流啊兄弟
