### ISSUE TITLE
关于启动passwall后，DHCP/DNS 页面的 DNS 转发自动新增两个服务器

### ISSUE THREAD

**Issue by mulder125** [xiaorouji/openwrt-passwall#1009]
询问一下
当启动passwall后，在DHCP/DNS 页面的 DNS 转发会自动添加两个服务器
127.0.0.1#5053
127.0.0.1#5054

根据我测试这两个服务器是passwall启动时加上的，我手动删除后，下次再次启动passwall就会立刻自动加上
想问一下有办法改为不自动添加吗？ 
因我已将AdGuard Home 设为dnsmasq上游，故想要一个127.0.0.1#5553就好

**Comment by WYC-2020** [comment]
不可能吧，用了这么多版本没遇到过，我是最近才编译的

**Comment by monokoo** [comment]
查看是否安装了https-dns-proxy，有的话卸载

**Comment by mulder125** [comment]
我查了一下个论坛也有人说https-dns-proxy，但我openwrt中没有这个

**Comment by mulder125** [comment]
找到原因了，应和passwall无关
在/etc/config/dhcp中有两行定义
	list doh_backup_server '127.0.0.1#5053'
	list doh_backup_server '127.0.0.1#5054'

删掉就OK了
就是不知道这两行是怎么出现的，DHCP/DNS 页面也没显示这个设定
