### ISSUE TITLE
编译的luci-app-passwall无法在friendlywrt r2s上正常运行

### ISSUE THREAD

**Issue by kinmeic** [xiaorouji/openwrt-passwall#1011]
问题描述：
1、在基础设置里的保存并应用无法使tcp正常启动或者关闭（勾选主开关，选择某个节点，点击保存并应用，加载条完成后tcp还是运行不起来，也没有产生日志）
2、去规则管理，点击手动更新，则可以产生日志，tcp也正常运行（曲线救国？）

版本从4-11开始到4-15都试过，
在x86_64上使用正常，但是在friendlywrt官方固件的r2s上安装后，无法正常使用。

Hostname	R2S
Model	FriendlyElec NanoPi R2S
Architecture	?
Firmware Version	OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-21.048.62294-9df7ea4
Kernel Version	5.10.2

**Comment by xiaorouji** [comment]
会不会和5.10内核有关？缺少了部分模块？
输入 /etc/init.d/passwall restart 看看

**Comment by kinmeic** [comment]
root@R2S:~# /etc/init.d/passwall restart
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
root@R2S:~# 

执行完以后，产生了日志，tcp也正常运行了

但是在界面通过保存和应用还是无法起作用。

**Comment by tritu** [comment]
I've used passwall 4-6 and 4-7 in two r2s for a while...

**Comment by hcym** [comment]
下午编译armv8正常，内核好像不是510

**Comment by kinmeic** [comment]
我是用友善官方sdk进行的编译：
openwrt-sdk-19.07.5-rockchip-rk3328_gcc-7.5.0_musl.Linux-x86_64.tar.xz

**Comment by xiaorouji** [comment]
> Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

似乎有其他APP占用了iptables，锁住了。
也可能是luci问题

**Comment by 1715173329** [comment]
友善的垃圾固件还是省省吧

**Comment by kinmeic** [comment]
刚刚更新编译了最新版本
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
这个报错没有了
但是保存并应用按钮还是不起作用...

**Comment by kinmeic** [comment]
<img width="455" alt="截屏2021-02-22 下午11 57 15" src="https://user-images.githubusercontent.com/76244375/108733849-cf9b2800-7569-11eb-98eb-943906b5c49b.png">
<img width="672" alt="截屏2021-02-22 下午11 57 27" src="https://user-images.githubusercontent.com/76244375/108733867-d32eaf00-7569-11eb-98ff-573da07749d6.png">

**Comment by sage-z** [comment]
> 友善的垃圾固件还是省省吧

那用啥啊 仁兄 我遇到了一样的问题

**Comment by kinmeic** [comment]
最新版本编译的可以正常使用了，一切正常

**Comment by sage-z** [comment]
> 最新版本编译的可以正常使用了，一切正常

可以分享下吗，怎样操作的？
