### ISSUE TITLE
请问“高级设置”中怎么没有“tcp节点数”的设置了？导致在“访问控制”中无法为某ip指定特定的“tcp节点”？

### ISSUE THREAD

**Issue by xukongyang** [xiaorouji/openwrt-passwall#1014]
请问高级设置里面怎么没有“tcp节点数”的设置了？导致在“访问控制”中无法为指定ip指定特定的科学上网“tcp节点”？

我在esir的高大全，精品小包，佛跳墙三个版本2021年2月的passwall中没有找到，美丽应用的树莓派4的20210219的passwall中也没有找到。passwall版本都是4.15.

![微信图片_20210222150038-无tcp节点数](https://user-images.githubusercontent.com/4610225/108673532-c89af800-751e-11eb-88b3-c37dd1bcbd24.png)

原来是有tcp节点数设置的，类似界面如下

![微信图片_20210222150038-有tcp节点数](https://user-images.githubusercontent.com/4610225/108674212-dbfa9300-751f-11eb-9158-15caeff05044.png)

**Comment by db-one** [comment]
前不久删除了

**Comment by xukongyang** [comment]
很有用的功能啊，为什么说删就删了呢？:(

**Comment by hathlife** [comment]
> 很有用的功能啊，为什么说删就删了呢？:(

改用xray分流了，功能更加强大

**Comment by xukongyang** [comment]
谢谢答复，有功能更加强大的xray分流是好事，但是也不要太激进啊，加入新功能的同时不要马上砍掉旧功能嘛，很多人都习惯了旧功能的使用了，原来的使用方法还是比较直观简单的。

而且我看这个xray的分流基本上都没有什么相关的说明，也没有对如何代替原有的tcp节点分流的相关帖子的教程，简直是一头雾水，请问哪里有用xray分流来代替原来的tcp节点数方便访问控制使用分流呢？

**Comment by fidysonsimon** [comment]
我也是更新了以后发现没有多tcp设置了，又刷了回去。新的xray分流我也试了，大概思路好像是在规则管理那里先设好，然后建一个xray分流节点。但很遗憾，好像这个规则里面如果只单独指定IP地址，不写域名的话，是不会生效的。最后我只能刷回原来的版本了。

**Comment by hathlife** [comment]
> 我也是更新了以后发现没有多tcp设置了，又刷了回去。新的xray分流我也试了，大概思路好像是在规则管理那里先设好，然后建一个xray分流节点。但很遗憾，好像这个规则里面如果只单独指定IP地址，不写域名的话，是不会生效的。最后我只能刷回原来的版本了。

分流的域名解析策略默认的`AsIs`模式就是这样啊 就是只按照域名分流 你这个要求要改成`IPIfNonMatch`才对

**Comment by xukongyang** [comment]
我看了下现在实现的xray分流，好像是根据访问的目的地址来分流的，例如访问油管走哪个vps，访问奈非走那个vps，

但是原来的访问控制是根据 源地址 来分流的，比如192.168.1.111是谷歌硬盘备份机，所有流量就走大流量的vps，192.168.1.222是手机，就走流量小但是快速的cn2 gia vps，

所以请大家不要说得兴起，讨论方向走偏了。。。

**Comment by monokoo** [comment]
> 我看了下现在实现的xray分流，好像是根据访问的目的地址来分流的，例如访问油管走哪个vps，访问奈非走那个vps，
> 
> 但是原来的访问控制是根据 源地址 来分流的，比如192.168.1.111是谷歌硬盘备份机，所有流量就走大流量的vps，192.168.1.222是手机，就走流量小但是快速的cn2 gia vps，
> 
> 所以请大家不要说得兴起，讨论方向走偏了。。。

那可以把谷歌云的相关地址作为规则指定走大流量vps也是可以的

**Comment by xukongyang** [comment]
谢谢答复，不过还是觉得原来的方式简单直观，只需要设置清晰明瞭可控的本地源地址和自己的vps节点即可，现在还要到处去找谷歌云的相关地址，找到的地址不全呢？不对呢？不太可控。。。

**Comment by db-one** [comment]
![image](https://user-images.githubusercontent.com/20243226/108791093-3bf14800-75b9-11eb-937f-c3c6a0591906.png)
如果我想默认走1181，TG走1182，是不是这样就可以了？
广告黑洞是直接丢弃了？去广告？
china选择直连就是不走代理，是这个意思吧？

**Comment by db-one** [comment]
1181  和  1182  是两个负载均衡节点

**Comment by WYC-2020** [comment]
@db-one  你可以让大佬出一个使用说明文档了，来一个官方教程哈哈

**Comment by fmbfmbhh** [comment]
分流要求自己获取服务的域名，像我谷歌drive的域名是在adg上面查日志才获取googleapis.com，然后再手动创建规则，我的P站和小姐姐也是单独去adg找规则，包括CDN和下载链接的域名都是不同的，非常麻烦。。。。还是求大佬把原来的多节点功能恢复吧

**Comment by laowagong** [comment]
多TCP节点选择挺好用的，建议恢复

**Comment by huanghe9527** [comment]
那么问题来了，最后一个有tcp计数器数是哪一个版本呢？
