### ISSUE TITLE
为什么 奈飞 看着看着就突然 不可用了

### ISSUE THREAD

**Issue by sendme365** [xiaorouji/openwrt-passwall#1015]
基本上默认配置没有改动什么。就在防火墙自定义规则里。添加了iptables -t nat -I POSTROUTING -j MASQUERADE 用来解决只能翻墙不能访问国内网站的问题。

然后第一次用奈飞。刚开始没问题。打开开了1小时后然后突然页面打不开。提示Not Available。
不用openwrt-passwall 直接用代理 却是可以打开的。 然后过一会就自己又好了，时间不定

**Comment by MGBB** [comment]
关闭IPV6 或者禁用国外域名IPV6解析

**Comment by EriTang** [comment]
请问如何禁用国外域名IPV6解析
