### ISSUE TITLE
服务端里的socks5启动不了

### ISSUE THREAD

**Issue by malong1989** [xiaorouji/openwrt-passwall#1017]
有遇到同样情况的吗？

**Comment by malong1989** [comment]
![Uploading 108851908...]()

**Comment by xiaorouji** [comment]
日志呢？

**Comment by malong1989** [comment]
大佬，日志显示的是server_setup: Address family not supported by protocol

**Comment by malong1989** [comment]
> 日志呢？

大佬，日志显示的是server_setup: Address family not supported by protocol
