### ISSUE TITLE
路由器重启后，passwall会进行多次重启

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#1018]
路由器重启后，查看pass日志走了一次配置，然后打开手机或者电脑浏览一下国内国外网站，再去查看passwall日志，多了两次配置的日志，一共进行了三次重新配置，不知道有没大佬遇到和我一样的情况。版本是最新版本

**Comment by jh0072110** [comment]
好像是这样的，我曾经好像也看到过…

**Comment by WYC-2020** [comment]
@jh0072110 不知道是一个什么逻辑。为啥要进行多次配置，按理应该配置一次就可以的，看来只有作者知道了哈哈，不影响使用，但是看起来确实别扭

**Comment by xiaorouji** [comment]
请说明一下网络环境 固件源码版本

**Comment by WYC-2020** [comment]
@xiaorouji 版本是最新4.15并且commit已经更新到最新的21号，网络环境的话是在主路由上面跑的，用的是负载均衡，下面是日志：
![image](https://user-images.githubusercontent.com/34025388/108951732-82bb6c80-76a3-11eb-9f55-2ed45544eebe.png)
这个是重启路由后第一次日志
![image](https://user-images.githubusercontent.com/34025388/108951781-9961c380-76a3-11eb-8dc4-17f07799b578.png)
这个是第二次
![image](https://user-images.githubusercontent.com/34025388/108951806-a1b9fe80-76a3-11eb-9ed0-60547fdec191.png)
这个是第三次
日志基本都是一样的，就是感觉它自己自动配置了三次

**Comment by monokoo** [comment]
passwall会检测iptables的变动，重启路由通常IP之类的都会变，触发重启很正常的

**Comment by WYC-2020** [comment]
@monokoo 他是重启路由后，自动进行了三次配置

**Comment by WYC-2020** [comment]
刚又看了一下日志 ，有自动配置了一次，现在已经有四次重新配置的日志了，不知道咋回事

**Comment by xiaorouji** [comment]
就正如 @monokoo 所说的，防火墙reload了，就会触发重启进程

**Comment by yunxi993** [comment]
确实，不看你这个还没注意，确实是的，三次.

**Comment by xiaorouji** [comment]
可以把 “开机时延时启动” 设置久一点
