### ISSUE TITLE
更新后 TCP节点一两秒钟后停止

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-passwall#1019]
更新后 TCP节点一两秒钟后停止

**Comment by xiaorouji** [comment]
日志呢？

**Comment by gswangmd-gssi** [comment]
Xray 1.3.0 (Xray, Penetrates Everything.) OpenWrt (go1.16 linux/amd64)
A unified platform for anti-censorship.
2021/02/24 11:23:02 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
2021/02/24 11:23:02 [Warning] core: Xray 1.3.0 started
2021/02/24 11:23:06 10.10.10.100:58236 accepted tcp:142.250.199.78:443 [d990ee47eab44a3d808745cec55efda2]
panic: crypto/hmac: hash generation function does not produce unique values

goroutine 37 [running]:
crypto/hmac.New(0xc000430c10, 0xc00003a138, 0x18, 0x18, 0x18, 0x18)
crypto/hmac/hmac.go:143 +0x370
github.com/xtls/xray-core/proxy/vmess/aead.KDF(0xc0001da030, 0x10, 0x10, 0xc000430dd0, 0x1, 0x1, 0x4612f3, 0xda6460, 0x0)
github.com/xtls/xray-core/proxy/vmess/aead/kdf.go:13 +0x12f
github.com/xtls/xray-core/proxy/vmess/aead.KDF16(...)
github.com/xtls/xray-core/proxy/vmess/aead/kdf.go:22
github.com/xtls/xray-core/proxy/vmess/encoding.(*ClientSession).DecodeResponseHeader(0xc0001da000, 0x100d680, 0xc000338480, 0x0, 0x0, 0x0)
github.com/xtls/xray-core/proxy/vmess/encoding/client.go:195 +0xd6
github.com/xtls/xray-core/proxy/vmess/outbound.(*Handler).Process.func3(0x0, 0x0)
github.com/xtls/xray-core/proxy/vmess/outbound/outbound.go:172 +0x16e
github.com/xtls/xray-core/common/task.OnSuccess.func1(0xc00010e9c0, 0x0)
github.com/xtls/xray-core/common/task/task.go:12 +0x2f
github.com/xtls/xray-core/common/task.Run.func1(0xc000306000, 0xc00007e300, 0xc0004de168)
github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
github.com/xtls/xray-core/common/task/task.go:27 +0x152

**Comment by gswangmd-gssi** [comment]
另外： 2月22日前编译的版本是正常的。

**Comment by xiaorouji** [comment]
应该是用了 Go 1.16 + 1.30的Xray的问题，更新Xray源码到最新提交编译应该没问题了，只不过Xray还没出新release。。。
https://github.com/XTLS/Xray-core/commit/d22c2d034cc29bf553566d3483f3bf761d2225ab
https://github.com/golang/go/commit/2a206c7fcc91854a0ab78fe5799bda38dd330b11

**Comment by xiaorouji** [comment]
更新最新源码即可
