### ISSUE TITLE
节点检测正常，百度、谷歌连接检测失败

### ISSUE THREAD

**Issue by ShoukakuChuuCC** [xiaorouji/openwrt-passwall#1021]
![log](https://user-images.githubusercontent.com/38343280/109026086-5252ed00-76fa-11eb-987f-d621c6cb77c1.png)
![log2](https://user-images.githubusercontent.com/38343280/109026498-c55c6380-76fa-11eb-8ce4-db6008177162.png)
2021/2/6编译的版本正常
2021/2/24编译的版本就不行 并且PassWall里的DNS选项没有ChinaDNS-NG开关
使用设备：树莓派4B（旁路由）

**Comment by WYC-2020** [comment]
多看commit
