### ISSUE TITLE
更新最新源码即可

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-passwall#1022]
更新最新源码即可
问题依旧，TCP、UDP节点交替停止
_Originally posted by @xiaorouji in https://github.com/xiaorouji/openwrt-passwall/issues/1019#issuecomment-785134780_

**Comment by xiaorouji** [comment]
那肯定是你的固件源码Xray-core重复了，自行解决

**Comment by Beginner-Go** [comment]
> 那肯定是你的固件二进制Xray-core重复了，自行解决

大佬 不考虑xray makeflie加个upx?

**Comment by gswangmd-gssi** [comment]
已经解决，谢谢！
