### ISSUE TITLE
为什么没有加载列表？请大佬帮我看看！谢谢！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall#1027]
@xiaorouji 大佬，麻烦看看，为什么日志里面加载的列表都是0，我有自己定交黑名单和白名单的，用的是gfw模式，谢谢！
![QQ图片20210226001633](https://user-images.githubusercontent.com/5343595/109182688-2c941980-77c8-11eb-9de4-f6cd458e3d83.png)

**Comment by snakwu** [comment]
感觉是列表路径有问题，麻烦@ @xiaorouji 大佬看看，谢谢!
![QQ图片20210226002941](https://user-images.githubusercontent.com/5343595/109184466-fe173e00-77c9-11eb-8e2d-f243df62384e.png)
![QQ图片20210226002922](https://user-images.githubusercontent.com/5343595/109184478-02435b80-77ca-11eb-9b70-f14c0c01d7dd.png)
![Uploading QQ图片20210226002922.png…]()

**Comment by xiaorouji** [comment]
[0] 不代表列表数量，意义就是上传日志给我们看的时候，我们可以快速定位问题

**Comment by snakwu** [comment]
@xiaorouji  明白谢谢大佬
