### ISSUE TITLE
最新版本passwall在除中国列表外模式下，直连列表和代理模式失效

### ISSUE THREAD

**Issue by HuTao1996** [xiaorouji/openwrt-passwall#1028]
在防火墙模式下，代理列表和直连模式生效。

**Comment by WYC-2020** [comment]
这描述，生效哈哈

**Comment by snakwu** [comment]
我也发现，这个直连和代理列表中的host有问题，那怕是gfw模式下

**Comment by snakwu** [comment]
印象中是从加进geoip后开始出现的

**Comment by xiaorouji** [comment]
你这描述是什么意思？

**Comment by HuTao1996** [comment]
我是做旁路由





------------------ 原始邮件 ------------------
发件人: xiaorouji <notifications@github.com&gt;
发送时间: 2021年3月5日 23:57
收件人: xiaorouji/openwrt-passwall <openwrt-passwall@noreply.github.com&gt;
抄送: HuTao1996 <294587434@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[xiaorouji/openwrt-passwall] 最新版本passwall在除中国列表外模式下，直连列表和代理模式失效 (#1028)





 
Closed #1028.
