### ISSUE TITLE
shunt rules protocol option

### ISSUE THREAD

**Issue by xcyll** [xiaorouji/openwrt-passwall#1030]
![2021-02-26 185359](https://user-images.githubusercontent.com/63227888/109291525-0d4aca00-7864-11eb-98d7-c5c1bd36beee.jpg)
请教下这里新加的3个协议选项有什么作用？列如：勾了bittorrent就可以对BT流量进行分流是吗
（在无域名列表 无IP列表下 勾选有用吗？）

**Comment by xcyll** [comment]
![2021-02-26 211559](https://user-images.githubusercontent.com/63227888/109305430-a8e63580-7878-11eb-8e4f-125e30150753.jpg)
界面崩了 报错
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute function dispatcher target for entry '/admin/services/passwall'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/passwall/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/i18n.lua:38: bad argument #1 to 'translate' (string expected, got nil)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by xiaorouji** [comment]
`勾了bittorrent就可以对BT流量进行分流是吗` 效果未知，需要测试。
`（在无域名列表 无IP列表下 勾选有用吗？）` 有用
