### ISSUE TITLE
服务端的socks5启动不起来

### ISSUE THREAD

**Issue by malong1989** [xiaorouji/openwrt-passwall#1032]
日志显示server_setup: Address family not supported by protocol

**Comment by xiaorouji** [comment]
输入`cat /etc/config/passwall_server` 看看

**Comment by malong1989** [comment]
> 输入`cat /etc/config/passwall_server` 看看

好的，大佬

**Comment by malong1989** [comment]
> 输入`cat /etc/config/passwall_server` 看看

大佬，显示的这些
root@OpenWrt:~# cat /etc/config/passwall_server

config global 'global'
        option enable '0'

**Comment by xiaorouji** [comment]
你连服务端节点都没创建。。

**Comment by xiaorouji** [comment]
你用xray的socks做服务端看看行不行

**Comment by malong1989** [comment]
> 你用xray的socks做服务端看看行不行

谢谢大佬，这个可以
