### ISSUE TITLE
更新规则文件会造成路由器死机

### ISSUE THREAD

**Issue by TwoBall** [xiaorouji/openwrt-passwall#1033]
开启了geoip自动更新，早上起来突然上不了网了。ping路由器也不通，ssh也进不去，所以获取不到日志。
重启后可进去luci界面，点击手动更新，跑到`规则更新完成重启应用`就死机了。

**Comment by xiaorouji** [comment]
这...我也不知道什么原因

**Comment by jh0072110** [comment]
我也遇到了🙃

**Comment by WROIATE** [comment]
我也遇到相同问题，包括手动更新和自动更新，直接卡死，连ssh都进不去，但能ping通
在连接ssh情况下手动更新ssh不会断连，但不能上网，使用命令行重启passwall后恢复正常

**Comment by WROIATE** [comment]
还有一个老问题就是使用nginx后每次点击手动更新都返回`192.168.1.1 错误`的信息
![Snipaste_2021-03-01_09-02-35](https://user-images.githubusercontent.com/44677306/109440339-eca19080-7a6c-11eb-8b70-9f7e0f2bcb40.png)

**Comment by SakuraFallingMad** [comment]
我也碰到了

**Comment by xiaorouji** [comment]
可能是bug，我今晚回去看看

**Comment by xiaorouji** [comment]
已修复

**Comment by z826540272** [comment]
> 已修复

试了一下,更新订阅后正常,但是打开/关闭节点开关后,路由器就死机了
