### ISSUE TITLE
fake IP  不能更新 google play

### ISSUE THREAD

**Issue by liuquanqing** [xiaorouji/openwrt-passwall#1034]
小米手机更新、安装 APP 一直卡在正在下载中，求解。

换成 doh 就好了

**Comment by liuquanqing** [comment]
解决了，将 googleapis.cn 设置为代理就好了

**Comment by xiaorouji** [comment]
googleapis.cn
googleapis.com
google.com.tw
google.com.hk
gstatic.com
xn--ngstr-lra8j.com
以上域名都要加入代理列表
