### ISSUE TITLE
使用官方openwrt编译出现大量问题

### ISSUE THREAD

**Issue by w931018h** [xiaorouji/openwrt-passwall#1037]
v2ray-plugin broke trojan go 无法编译
luci passwall 和chinadns编译完成无法安装提示架构不对

**Comment by kentooo** [comment]
> v2ray-plugin broke trojan go 无法编译
> luci passwall 和chinadns编译完成无法安装提示架构不对

go无法编译应该是版本的问题，openwrt官方最新的SDK版本19.07.7中包含的golang是1.13版本
如果要编译trojan-go，需要手动修改SDK中的golang版本，具体编辑下面两个文件

```
[openwrt_sdk_folder]/feeds/packages/lang/golang/golang-version.mk
-----------------------------------------------------------------
GO_VERSION_MAJOR_MINOR:=1.15 (将此字段修改为1.15)
GO_VERSION_PATCH:=8 (将此字段修改为8)
```

```
[openwrt_sdk_folder]/feeds/packages/lang/golang/golang/Makefile
---------------------------------------------------------------
PKG_SOURCE:=go$(PKG_VERSION).src.tar.gz
PKG_SOURCE_URL:=$(GO_SOURCE_URLS)
PKG_HASH:=540c0ab7781084d124991321ed1458e479982de94454a98afab6acadf38497c2 (将此字段修改为golang 15.8的源码hash值)
```

还有，如果用官方SDK编译的过程中可能会出现找不到upx而引发的编译失败
如果是软路由或者路由器本身的Flash空间很大，可以在make menuconfig里面把Trojan-go和xray-plugin的upx压缩选项关掉，
如果Flash空间不太充裕，那就自己找个upx包或者粗暴一点把系统安装好的的upx二进制文件复制到 [openwrt_sdk_folder]/staging_dir/host/bin 文件夹里面去

我用的是x86_64，暂时没发现架构不对的问题，其他的路由器不太清楚

**Comment by Es-dese** [comment]
我是把配置文件删了，重新配置一遍config就好了

**Comment by w931018h** [comment]
感谢上面2位朋友 我会尝试下 
但我直接去掉v2ray  broke  trojan go三个子选项可以正常编译出最后的ipk 文件 只不过浏览器里上传ipk后提示255错误 架构不对。

**Comment by w931018h** [comment]
另外是设备是树莓派4

**Comment by w931018h** [comment]
root@OpenWrt:/tmp# opkg install luci-app-passwall_4-15_all.ipk
Unknown package 'luci-app-passwall'.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.

**Comment by z826540272** [comment]
直接拉源码编译,iPK也出来了.

**Comment by w931018h** [comment]
> 直接拉源码编译,iPK也出来了.

我就是源码编译的 编译完发现ipk没装上去 直接从包里拿出来上传上去抱错255

**Comment by starambler** [comment]
golang版本过低的话，在 update feeds 后执行以下命令即可

pushd feeds/packages/lang
rm -rf golang && svn co https://github.com/openwrt/packages/trunk/lang/golang
popd
