### ISSUE TITLE
固件启动卡住，UEFI 启动问题

### ISSUE THREAD

**Issue by TDSEND** [xiaorouji/openwrt-passwall#1038]
错误提示：  
i915 0000:00:02.0: Failed to load DMC firmware [https://01.org/linuxgraphics/intel-linux-graphics-firmwares], disabling runtime power management.

J4125U， 只支持UEFI 启动，望修复，谢谢！

**Comment by hcym** [comment]
自己多试试吧，pass不管这个东西，我有两个机器用大雕的不能启动，只能用官方master才能efi启动，dd都不行

**Comment by jh0072110** [comment]
这个issue应该提给你编译的openwrt源码作者…吧
