### ISSUE TITLE
能否单独导入/出passwall配置

### ISSUE THREAD

**Issue by bingxueqingzhi** [xiaorouji/openwrt-passwall#1039]
每次刷固件重置之后,都要重新手动设置,甚是麻烦
是否有办法快速导入导出passwall配置?

**Comment by WYC-2020** [comment]
保留配置升级，或者升级之前导出，升级之后导入不就行了

**Comment by 283915025** [comment]
把/etc/config/passwall拿出来重新覆盖一下就行

**Comment by bingxueqingzhi** [comment]
> 
> 
> 保留配置升级，或者升级之前导出，升级之后导入不就行了

试过, 如果Passwall隔了几个版本, passwall就会出问题

**Comment by bingxueqingzhi** [comment]
> 
> 
> 把/etc/config/passwall拿出来重新覆盖一下就行

我试试

**Comment by db-one** [comment]
> 试过, 如果Passwall隔了几个版本, passwall就会出问题

那你直接恢复PASSWALL不是该出问题还是出问题？
