### ISSUE TITLE
passwall 服务器端 启动延迟？

### ISSUE THREAD

**Issue by violesea** [xiaorouji/openwrt-passwall#1042]
软路由重启后 服务器端建立的服务没有办法第一时间通过域名链接。
 通过测试：
1.IP：端口的形式可以连接服务器端的服务；
2.路由器ip与域名解析正常；
3.其他的类似helloworld服务器端建立的服务似乎也不行。
软路由启动大概二十分钟后可以连接正常使用。
本人门外汉，不知道描述清楚没有…

**Comment by xiaorouji** [comment]
建议先了解 域名 DNS TTL 缓存
