### ISSUE TITLE
请教几个设置的问题

### ISSUE THREAD

**Issue by silencehunt** [xiaorouji/openwrt-passwall#1054]
第一次用passwall，有几个问题想请教一下。我的软路由上只建了一个xray节点，使用tcp。我想要达到的目的是：
1.gfwlist上的内容，使用xray来访问，其余的都使用直连。
我在“基本设置”－“模式”里，把“TCP默认代理模式”设为了“防火墙表”，“路由器自身TCP代理模式”设为了“默认”。请问这样是否能达到我的目的？另外，“UDP默认代理模式”和“路由器自身UDP代理模式”该设置成什么？
2.怎么能快速地获取dns解析结果？我希望是gfwlist上的内容，使用国外的dns来解析，其余的用国内的来解析。
我在“基本设置”－“dns”里，把“本地DNS(UDP)”设为了“114.114.114.114”，“过滤模式”设为“pdnsd通过tcp节点请求dns”，“远程dns”设为了“8.8.8.8”。这样设置后，我的主观感觉是，网页打开的速度还是比较慢。
请大家给点儿意见，谢谢。

**Comment by xiaorouji** [comment]
1. 新版已经没有“本地DNS”选项了。
2. 因为你不是最新源码版本，无法知道是否是BUG还是什么。
3. 防火墙表模式 + xray节点的话DNS方案可以使用“Fake IP“，亲测效果不错。
4. 建议升级最新源码再测试反馈。

**Comment by silencehunt** [comment]
> 1. 新版已经没有“本地DNS”选项了。
> 2. 因为你不是最新源码版本，无法知道是否是BUG还是什么。
> 3. 防火墙表模式 + xray节点的话DNS方案可以使用“Fake IP“，亲测效果不错。
> 4. 建议升级最新源码再测试反馈。
今天编译了最新的4-16试了一下，dns里的确是没有“本地DNS”了，过滤模式按照建议，改成“fake ip”，先试试再说。
不过模式里四种代理模式应该怎么填，能不能给解释一下？谢谢了。
另外，在x86-64架构的软路由上，这个内存占用率正常吗？
32469	root	/var/etc/passwall/bin/xray -config=/var/etc/passwall/TCP.json	0%	483%

**Comment by xiaorouji** [comment]
不是很正常，有可能是显示BUG，实际应该不会用那么多
