### ISSUE TITLE
Trojan-Go 分流

### ISSUE THREAD

**Issue by KGB333** [xiaorouji/openwrt-passwall#1055]
**也就好奇问下**，大佬后续会做Trojan-Go的分流吗？或者是把分流做成功能，协议随意切换的形式，还是暂时没这打算呢？

**Comment by xiaorouji** [comment]
目前不会，我接手PassWall后基本上都是以我自己的需求目的去做实现。不会为了支持而支持。

**Comment by KGB333** [comment]
> 目前不会，我接手PassWall后基本上都是以我自己的需求目的去做实现。不会为了支持而支持。

毕竟用爱发电，还是感谢大神
