### ISSUE TITLE
节点失效，内网也跟差断网（中国列表以外）！！

### ISSUE THREAD

**Issue by kitkw** [xiaorouji/openwrt-passwall#1056]
一直被困扰的问题，从旧版到新版就一直这样。
设置如下 其它没有改过（ADHOME SmartDNS 都没打开）DNS 加速打开了。
希望有大佬指教
![image](https://user-images.githubusercontent.com/31963066/110107612-18fb3b00-7de6-11eb-910d-2f39635b0a03.png)

![image](https://user-images.githubusercontent.com/31963066/110107727-3fb97180-7de6-11eb-81e4-0a056626e273.png)

**Comment by WYC-2020** [comment]
我也好像发现了，只要你不设置一个上游就会出现打不开网页，必须设置一个，不知道是不是pw那个获取上游服务器设置有关

**Comment by WYC-2020** [comment]
没有删除本地dns设置那个版本好像没问题

**Comment by kitkw** [comment]
> 我也好像发现了，只要你不设置一个上游就会出现打不开网页，必须设置一个，不知道是不是pw那个获取上游服务器设置有关

设置了一下SmartDNS 还是节点断 全网断。
不知道那里设置有错？
![image](https://user-images.githubusercontent.com/31963066/110200546-7f8d6100-7e99-11eb-835d-0ed6ece17267.png)
![image](https://user-images.githubusercontent.com/31963066/110200587-b5cae080-7e99-11eb-9e35-e3f8c4718bc8.png)
![image](https://user-images.githubusercontent.com/31963066/110200600-c54a2980-7e99-11eb-9c5b-9ca727e5bfc3.png)
![image](https://user-images.githubusercontent.com/31963066/110200634-e579e880-7e99-11eb-8491-60fc3bf247dc.png)

**Comment by monokoo** [comment]
尝试下DHCP/DNS 中 取消勾选忽略解析文件选项

**Comment by kitkw** [comment]
> 尝试下DHCP/DNS 中 取消勾选忽略解析文件选项

这项本来就没有勾选上的。
