### ISSUE TITLE
反馈冲突问题

### ISSUE THREAD

**Issue by haitun001** [xiaorouji/openwrt-passwall#1060]
首先对我上一个反馈当中的问题的不严谨给开发者造成困惑表示抱歉。
经过反复测试发现，问题来源于adbybyplus这个插件，只要这个插件和passwall一起开就会产生这样那样奇奇怪怪的问题，比如国内不能访问这些，请问开发者是否有什么缓解策略或者方案，还是放弃使用adbybyplus

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/110236272-d8c7c400-7f6f-11eb-8ad9-8402c87064c6.png)
adbyby规则貌似停更好久了，不如放弃？

**Comment by jh0072110** [comment]
> ![image](https://user-images.githubusercontent.com/60100640/110236272-d8c7c400-7f6f-11eb-8ad9-8402c87064c6.png)
> adbyby规则貌似停更好久了，不如放弃？

肉鸡大佬推荐一个呗😅😅😅

**Comment by xiaorouji** [comment]
@jh0072110 我个人也没使用过此类插件，不清楚啊。。如果有你们也可以推荐一下

**Comment by hplee0120** [comment]
现在还在更新而且效果不错的只有koolproxy了吧，但是毕竟现在的openwrt的koolproxy软件包也是很久前的版本了，现在基本都是换皮的。有一些以前遗留下的bug和兼容性问题

**Comment by hplee0120** [comment]
> 现在还在更新而且效果不错的只有koolproxy了吧，但是毕竟现在的openwrt的koolproxy软件包也是很久前的版本了，现在基本都是换皮的。有一些以前遗留下的bug和兼容性问题。或者等待adguard home支持mitm吧，不过不知道是啥时候了，作者倒是有计划增加这个功能。

**Comment by haitun001** [comment]
我看了无数个kp的仓库都是很久很久以前更新的，那么是否有朋友能提供一个还在持续更新的kp的仓库地址呢？感激不尽。

**Comment by eightsheep67** [comment]
看到你说adbybyplus和passwall一起用会产生各种奇奇怪怪的问题，我赶紧把adbybyplus卸了，再试试会不会出现不定时全部网页访问不了的情况。https://github.com/xiaorouji/openwrt-passwall/issues/1064

**Comment by ddzzhen** [comment]
我没有用adbyby，用的是simple-adblock，passwall打开一天或几个小时后，cpu一直高占用，直到卡死网络。用命令行停掉passwall，页面停用后恢复正常（已三天没有问题）。
卡顿的时候htop查看CPU占用，是haproxy的锅，貌似dns解析陷入了混乱，原因不明，日志比较少。
