### ISSUE TITLE
如何避免迅雷BT走代理流量

### ISSUE THREAD

**Issue by eightsheep67** [xiaorouji/openwrt-passwall#1061]
现在的科学配置是HEROKU部署APP，然后用CF的WORKERS反代，现在的问题就是在常用PC上使用迅雷进行BT下载，就会导致Cloudflare被封，断开大概10分钟左右会恢复，应该就是走了迅雷BT走了代理流量。

但是我的常用PC又经常需要科学上网，不能设定访问控制为不代理，这个要怎么设置呢？？
下面是我现在的设置。

![捕获](https://user-images.githubusercontent.com/70835718/110209492-dad64800-7ec7-11eb-9613-95bc6fc7bde5.PNG)
![2](https://user-images.githubusercontent.com/70835718/110209494-dca00b80-7ec7-11eb-8bc1-bcd21b6683f4.PNG)

**Comment by lededev** [comment]
在PC上增加一个局域网IP地址，也就是双IP。例如192.168.1.91(默认主IP）和192.168.1.92(BT专用IP)
放弃使用迅雷BT改为qBittorrent，按Alt+O进入选项=>高级
修改设置：
  网络接口 任意网络接口
  绑定到可选IP地址 192.168.1.92
确定保存退出。
进passwall luci配置界面，直连/代理名单管理 将192.168.1.92加入直连IP列表，保存应用。
启动qBittorrent。现在全部BT流量应该就都走直连不会从代理绕行了。

**Comment by eightsheep67** [comment]
![1](https://user-images.githubusercontent.com/70835718/110232743-9e076100-7f5a-11eb-952b-8f7c6bbaee49.PNG)
![2](https://user-images.githubusercontent.com/70835718/110232744-9f388e00-7f5a-11eb-9985-5e6c057f8597.PNG)
![3](https://user-images.githubusercontent.com/70835718/110232745-9fd12480-7f5a-11eb-9911-ea9a22bdd4a7.PNG)
我测试了下以上设置，好像不会再被Cloudflare封了。貌似不会再走代理流量了。

**Comment by xcyll** [comment]
嗯嗯 设置为防火墙列表模式可行
