### ISSUE TITLE
长期的困扰，突然所有网站都打不开。

### ISSUE THREAD

**Issue by eightsheep67** [xiaorouji/openwrt-passwall#1064]
编译过多个固件了，但是一直会有这种情况，就是正常开启PASSWALL，但是用了一两天，突然会出现手机微信，网页打不开，智能家居断线，电脑网页也打不开，关闭PASSWALL开关可以解决，再次打开PASSWALL有一定几率还是会出现同样的情况，有时候点击IPSET重置可能可以解决，有时候又不行。

固件内没有编译其他的DNS插件，我只在接口PPPOE处更改为手动DNS，223.5.5.5和114.114.114.114。

**Comment by ddzzhen** [comment]
看看卡顿的时候是不是haproxy的cpu占用很高，我也是这样，暂时停用了

**Comment by eightsheep67** [comment]
昨天重新编译了一个固件，我的固件是越来越精简了，adbyby也去掉了，DNS也都直接用电信通告地址，也没有再设置dnsmasq，就这样，PASSWALL就是vless单节点运行没有再使用负载均衡，目前稳定运行12h，用几天看看。

**Comment by ddzzhen** [comment]
> 昨天重新编译了一个固件，我的固件是越来越精简了，adbyby也去掉了，DNS也都直接用电信通告地址，也没有再设置dnsmasq，就这样，PASSWALL就是vless单节点运行没有再使用负载均衡，目前稳定运行12h，用几天看看。

我也尝试测试过，如果不打开负载均衡和自动切换，haproxy就不需要工作，这样是不会出问题的。

**Comment by eightsheep67** [comment]
> 看看卡顿的时候是不是haproxy的cpu占用很高，我也是这样，暂时停用了

卡顿倒是不会卡顿，CPU占用除非在迅雷下载之类的不然都很低，就是突然所有需要域名解析的东西都打不开了，外面电视还在播放的就能播放，如果退出来就刷不出页面之类的。就是DNS出问题了，也不知道是哪里出了问题我也不会看……

**Comment by monokoo** [comment]
> > 看看卡顿的时候是不是haproxy的cpu占用很高，我也是这样，暂时停用了
> 
> 卡顿倒是不会卡顿，CPU占用除非在迅雷下载之类的不然都很低，就是突然所有需要域名解析的东西都打不开了，外面电视还在播放的就能播放，如果退出来就刷不出页面之类的。就是DNS出问题了，也不知道是哪里出了问题我也不会看……

可以排查下DHCP/DNS设置

**Comment by eightsheep67** [comment]
> > > 看看卡顿的时候是不是haproxy的cpu占用很高，我也是这样，暂时停用了
> > 
> > 
> > 卡顿倒是不会卡顿，CPU占用除非在迅雷下载之类的不然都很低，就是突然所有需要域名解析的东西都打不开了，外面电视还在播放的就能播放，如果退出来就刷不出页面之类的。就是DNS出问题了，也不知道是哪里出了问题我也不会看……
> 
> 可以排查下DHCP/DNS设置

![1](https://user-images.githubusercontent.com/70835718/110405930-5ac50380-80bc-11eb-9abc-5b9e3aca95f1.PNG)
![2](https://user-images.githubusercontent.com/70835718/110405937-5c8ec700-80bc-11eb-83b9-4f4a35c1a0a1.PNG)
![3](https://user-images.githubusercontent.com/70835718/110405944-5dbff400-80bc-11eb-86c6-1a55ea82c1fc.PNG)
![4](https://user-images.githubusercontent.com/70835718/110405947-5ef12100-80bc-11eb-8670-d536d1666eb5.PNG)
![5](https://user-images.githubusercontent.com/70835718/110405950-61537b00-80bc-11eb-857b-ffdec66b9fbc.PNG)


基本上都是默认设置

**Comment by ddzzhen** [comment]
> > > > 看看卡顿的时候是不是haproxy的cpu占用很高，我也是这样，暂时停用了
> > > 
> > > 
> > > 卡顿倒是不会卡顿，CPU占用除非在迅雷下载之类的不然都很低，就是突然所有需要域名解析的东西都打不开了，外面电视还在播放的就能播放，如果退出来就刷不出页面之类的。就是DNS出问题了，也不知道是哪里出了问题我也不会看……
> > 
> > 
> > 可以排查下DHCP/DNS设置
> 
> ![1](https://user-images.githubusercontent.com/70835718/110405930-5ac50380-80bc-11eb-9abc-5b9e3aca95f1.PNG)
> ![2](https://user-images.githubusercontent.com/70835718/110406061-9233b000-80bc-11eb-9d3f-fa455c535b91.PNG)
> ![3](https://user-images.githubusercontent.com/70835718/110405944-5dbff400-80bc-11eb-86c6-1a55ea82c1fc.PNG)
> ![4](https://user-images.githubusercontent.com/70835718/110405947-5ef12100-80bc-11eb-8670-d536d1666eb5.PNG)
> ![5](https://user-images.githubusercontent.com/70835718/110405950-61537b00-80bc-11eb-857b-ffdec66b9fbc.PNG)
> 
> 基本上都是默认设置

差不多 我也都是默认的，差别就是日志关了
