### ISSUE TITLE
ipv6节点订阅被过滤以及延迟测试问题

### ISSUE THREAD

**Issue by RainCat1998** [xiaorouji/openwrt-passwall#1067]
如题，订阅节点中如果包含ipv6节点(使用ipv6地址非域名)，该节点会被过滤掉。

另外最新版本所有ipv6节点延时测试超时，之前的旧版没有这个问题。

**Comment by xiaorouji** [comment]
请提供订阅链接，发往我邮箱(xiaoroujixxoo@gmail.com)，不然无法修复。
