### ISSUE TITLE
希望大佬们修复一下这个问题

### ISSUE THREAD

**Issue by malong1989** [xiaorouji/openwrt-passwall#1073]
passwall更新到最新源码后，在基本设置页面下的tcp节点选择上，卡顿甚至网页崩溃，点后面的修改与日志也卡！（手机浏览器没有问题）

**Comment by malong1989** [comment]
@xiaorouji 大佬，能修复一下这个问题吗？

**Comment by ddzzhen** [comment]
我也是昨晚重新编译了一次，只联网开无线，启动passwall（tcp节点，udp同tcp节点，dns使用的dns2socks，127.0.0.1:9050，开了socks，其它全部默认），CPU居高不下网络直接卡死。

关掉haproxy，重启passwall还是一样，全部停用恢复正常。
