### ISSUE TITLE
Fake IP+防火墙表访问github的问题

### ISSUE THREAD

**Issue by hujiao80** [xiaorouji/openwrt-passwall#1074]
Fastly error: unknown domain: github.com. Please check that this domain has been added to a service.

Details: cache-itm18845-ITM

分流节点+Fake IP+防火墙表，github任何页面都会不定期出现上面的错误，一般是开关插件后过上5-10分钟就可能会出现以上错误，一般过上几分钟有可能恢复，或者开关一次插件恢复正常，然后又循环出现。其他网站还没有出现类似问题。

已更新至最新代码，不知道什么问题，是我姿势不对吗？

**Comment by xiaorouji** [comment]
github.com有没有加入代理列表？
ping github.com
看看解析出来的是不是假IP

**Comment by hujiao80** [comment]
ping github.com
正在 Ping github.com [11.1.1.1] 具有 32 字节的数据:
访问正常与否，返回都是这个ip。

github-production-release-asset-2e65be.s3.amazonaws.com
github.com
github.io
githubapp.com
githubassets.com
githubusercontent.com
上述网址均已加入代理列表。

另外关于代理列表还有个问题，似乎代理列表在分流节点模式下优先级比较低，因为我分流设了国内直连，即使将googleapis.cn加入代理列表后play商店安装app还是会卡在等待下载。但是在规则管理加一条google站点的规则放在国内直连之前play商店下载就没问题了

**Comment by hcym** [comment]
可能是gfw搞什么新意思，git源码编译完全没有问题，网页浏览基本正常，手机app经常断开，几个固件两种模式都如此，只有手机上用clash好一点😅

**Comment by xiaorouji** [comment]
返回 11.1.1.1 那就是没问题，的确是Fake IP。

**Comment by ygcaicn** [comment]
这是因为Chrome会尝试走h2 or quic, github支持h2, Sniffing 只能从HTTP / TLS 类型的流量中提取出域名，因此会出问题。
