### ISSUE TITLE
服务器端防火墙没有放行，导致外出无法连接回来

### ISSUE THREAD

**Issue by db-one** [xiaorouji/openwrt-passwall#1075]
最近一段时间好像都有这个问题，具体表现是固件升级以后，外面网络无法通过pw服务器连接回家，重启则完全正常，今天确认了一下应该是防火墙没有放行pw的服务器端口，在防火墙里面完全查不到服务器端的端口，手动再次提交一下pw设置，防火墙里面才可以看到端口

**Comment by db-one** [comment]
![Screenshot_2021-03-11-10-12-58-467_com mmbox xbrowser pro](https://user-images.githubusercontent.com/20243226/110725379-79f59980-8252-11eb-9f11-9c3e86381297.jpg)

**Comment by db-one** [comment]
> 防火墙端口通信规则界面手动设置放行端口规则即可

嗯  但是他软件本身是可以自己申请端口放行的，如果再手动放行就多次一举了，应该是哪里出了BUG导致放行不成功或者是什么其他问题导致没有放行
这种情况只出现在更新固件之后首次重启，这时候重复提交应用一下PW的设置就好了，以后在重启就正常的

**Comment by xiaorouji** [comment]
更新固件后重启一遍比较好

**Comment by db-one** [comment]
好的，明白
