### ISSUE TITLE
DNS 随机解析失败

### ISSUE THREAD

**Issue by BOBINIUNIU** [xiaorouji/openwrt-passwall#1077]
表现：浏览器打开网站时出现服务器IP找不到信息，过大约1秒后重新连接成功， 有时候则需要手动刷新。

固件环境
未编译Chinadns
节点 xray vless

我已经尝试了所有的dns设置组合，每次测试前都清空IPSET和flushdns，问题仍然存在。

**Comment by CirnoSalt** [comment]
有相同问题，gfwlist模式，
尤其是节点不稳定时国内也会出现随机无法解析

**Comment by yunxi993** [comment]
遇到过相同问题.

**Comment by cncherisher** [comment]
相同问题+1，暂时切换到ssr plus+

**Comment by xiaorouji** [comment]
我专门用了一天gfw模式，没复现。请提供下日志

**Comment by BOBINIUNIU** [comment]
> 我专门用了一天gfw模式，没复现。请提供下日志。

之前是不管gfw或者大陆白模式都有这个问题。这两天研究实验后，这个问题已经大大缓解。
变量如下
1. 之前主机用的是bbr plus 129版，换成了新版plus。据说老版本会断流，可能就是因为这个原因。
2. 之前的固件我没有编译ChinaDns, 仅编译了xray选项。这次加入了ChinaDns
3. DNS设置开启禁用IPV6解析和禁用无效信息缓存，其他的选项默认

有同样问题的可以参考一下。

感谢大佬回复，目前还在测试中，如果再次出现这个问题就发日志。
P.S日志等级是不是要调成debug？

**Comment by CirnoSalt** [comment]
> > 我专门用了一天gfw模式，没复现。请提供下日志。
> 
> 之前是不管gfw或者大陆白模式都有这个问题。这两天研究实验后，这个问题已经大大缓解。
> 变量如下
> 
> 1. 之前主机用的是bbr plus 129版，换成了新版plus。据说老版本会断流，可能就是因为这个原因。
> 2. 之前的固件我没有编译ChinaDns, 仅编译了xray选项。这次加入了ChinaDns
> 3. DNS设置开启禁用IPV6解析和禁用无效信息缓存，其他的选项默认
> 
> 有同样问题的可以参考一下。
> 
> 感谢大佬回复，目前还在测试中，如果再次出现这个问题就发日志。
> P.S日志等级是不是要调成debug？

测试之后发现确实和ipv6有关，关掉v6解析之后有缓解但节点不稳定时还会有这种情况，如果能和v6完美共存就最好了。

**Comment by CirnoSalt** [comment]
国内域名放行v6解析
GFWlist内域名只返回v4结果并代理
不知道可不可行……

**Comment by yunxi993** [comment]
我用GFW列表 google  youtube  全都打不开，提示没连网，换列表以为就正常了.

**Comment by badgv** [comment]
> 国内域名放行v6解析
> GFWlist内域名只返回v4结果并代理
> 不知道可不可行……

已提交合并申请[#1078](https://github.com/xiaorouji/openwrt-passwall/pull/1078)
如果合并了，代理DNS使用pdnsd即可实现这个功能
国内域名经过dnsmasq之后使用114或其它任意DNS可正常反回ipv6，代理上游DNS使用pdnsd禁用ipv6解析

**Comment by badgv** [comment]
> 国内域名放行v6解析
> GFWlist内域名只返回v4结果并代理
> 不知道可不可行……

临时解决方案：可以使用 开机启动脚本，手动启动一个pdnsd，比如监听在127.0.0.1:5353，配置成禁用ipv6反馈模式，然后将PSW的上游DNS设置为自定义dns ，设置为127.0.0.1:5353。

**Comment by xiaorouji** [comment]
复现的时候 可以在路由器上执行如下几条命令对比一下
nslookup www.baidu.com
nslookup www.baidu.com 127.0.0.1
nslookup www.baidu.com 127.0.0.1#7913
nslookup www.baidu.com 127.0.0.1#7914
nslookup www.baidu.com 223.5.5.5

**Comment by WYC-2020** [comment]
我的也是，如果从外面回来然后去了解一下wifi经常会遇到第一次没法打开，刷新一下就可以，浏览的都是国外的网站，比如youtube google之类的

**Comment by xiaorouji** [comment]
建议检查固件，是不是和某些插件冲突了。
我倒是没发现有问题
