### ISSUE TITLE
开启Passwall 有几率漏掉一些ip代理

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1080]
模式选择的是绕过大陆
开启passwall，有几率会漏掉一些ip的代理，部分ip仍然走直连，导致一些网站打不开，或者打开速度缓慢
完全随机的现象
日志里看不出什么,但是可以确定是某些ip没走代理，DNS解析正确，所以应该和DNS没关系

**Comment by z826540272** [comment]
总是要重启几次才能完全没问题.

**Comment by z826540272** [comment]
网页界面 Google 连通性检查 是没问题的

**Comment by hplee0120** [comment]
差不多情况 重启后日志一直在刷节点异常正在自动切换。但是检测连通性是通的。

**Comment by z826540272** [comment]
> 差不多情况 重启后日志一直在刷节点异常正在自动切换。但是检测连通性是通的。从几个版本之前就有这个问题了，但是日志没什么异常，

而且开启的速度越来越慢了，以前停更那段时间开启速度很快，现在开启一次要十几秒左右
