### ISSUE TITLE
开启passwall主开关之后，TCP和UDP图标依旧显示未运行

### ISSUE THREAD

**Issue by Tonkercke** [xiaorouji/openwrt-passwall#1085]
系统是openwrt 19.07.7官方版本，配置好节点、代理模式等设置后，TCP和UDP图标依旧显示未运行，19.07.06的时候是可以正常显示已运行的。测试了好多个型号的路由器都是这样，但却可以正常翻墙。

**Comment by yunxi993** [comment]
把 passwall 恢复默认一下就可以正常.

**Comment by Tonkercke** [comment]
不知在哪里可以单独恢复passwall的默认设置。一般我都是在openwrt源代码中编译好的固件（passwall的源代码我已经集成到openwrt源代码中了），直接刷到路由器中，并且是不保存路由器所有设置的方式系统的，但试了好多次也都是TCP和UDP图标依旧显示未运行，只有DNS显示已运行。

**Comment by yunxi993** [comment]
在基础页面，小提示下面.

**Comment by Tonkercke** [comment]
重置之后依旧不显示已运行。升级到4-17最新版本后依然是这样，可能是与最新版的openwrt 19.07.7不兼容吧！
