### ISSUE TITLE
向shadowsocks*包添加链接mbedtls选项以支持armv8平台的硬件加速

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#1089]
lean源码刚刚更新了mbedtls库的armv8硬件加速补丁，对r2s/r4s这类平台的的ss性能提升很大，但是passwall提供的shadowsocks*包似乎只能链接到openssl库，不知道可否添加一个链接到mbedtls的选项？

**Comment by xiaorouji** [comment]
最新源码已经加入ss-rust支持，可以尝试下
