### ISSUE TITLE
订阅列表中的部分服务器地址仍然走代理

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1091]
订阅列表中的部分服务器地址仍然走代理

例如 tchk2.speed17.club 这种地址.

正常情况下订阅列表中的服务器应该全部添加到直连列表,不经过代理

查到必须要经过一次nslookup DNS查询后 上面的地址方能通过直连.
如果不查询直接连接对应IP的话是走代理通道
能否优化

**Comment by z826540272** [comment]
查到必须要经过一次nslookup DNS查询后 上面的地址方能通过直连.

**Comment by xiaorouji** [comment]
我这里测试是正常的。
