### ISSUE TITLE
编译出错！麻烦大佬看下！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall#1092]
@xiaorouji 
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
make[2]: *** [package/Makefile:69: package/install] Error 255

x86架构，编译环境：ubuntu 20.04.2 LTS

**Comment by lededev** [comment]
x86_64新增了一个默认选项shadowsocks_rust，进menuconfig对那项选n保存配置，然后make package/luci-app-passwall//{clean,compile} V=s

**Comment by snakwu** [comment]
@lededev  收到，谢谢大佬
