### ISSUE TITLE
默认tcp选中国列表以外不能上网

### ISSUE THREAD

**Issue by csteike** [xiaorouji/openwrt-passwall#1097]
过滤模式选通过pdnsd'通过tcp请求dns，远程dns是谷歌的
默认tcp选中国列表以外，默认udp选游戏模式，无法上外网，如果都选全局模式可以正常上网而且响应速度很快。

TCP默认*代理模式是什么意思，我选全局模式是不是所有网站都用谷歌dns解析，那样速度应该慢才对

**Comment by xiaorouji** [comment]
日志？
