### ISSUE TITLE
shadowsocks-rust mips架构出现upx压缩失败错误

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#1100]
```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /home/hathlife/openwrt/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/sslocal: CantPackException: bad e_shstrndx

Packed 0 files.
```

**Comment by xiaorouji** [comment]
Fix

**Comment by ddzzhen** [comment]
> Fix

mkdir -p /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp
SHELL= flock /home/lede/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-libev-3.3.5/.pkgdir/shadowsocks-libev-ss-redir/. /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/'
touch /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp/.shadowsocks-libev-ss-redir_installed
echo "shadowsocks-libev-ss-redir" >> /home/lede/lede/staging_dir/target-mipsel_24kc_musl/pkginfo/shadowsocks-libev.default.install
mkdir -p /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp
SHELL= flock /home/lede/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-libev-3.3.5/.pkgdir/shadowsocks-libev-ss-server/. /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/'
touch /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp/.shadowsocks-libev-ss-server_installed
echo "shadowsocks-libev-ss-server" >> /home/lede/lede/staging_dir/target-mipsel_24kc_musl/pkginfo/shadowsocks-libev.default.install
make[3]: Leaving directory '/home/lede/lede/feeds/packages/net/shadowsocks-libev'
time: package/feeds/packages/shadowsocks-libev/compile#0.12#0.06#0.20
make[3]: Entering directory '/home/lede/lede/package/lean/simple-obfs'
mkdir -p /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp
SHELL= flock /home/lede/lede/tmp/.root-copy.flock -c 'cp -fpR /home/lede/lede/build_dir/target-mipsel_24kc_musl/simple-obfs//simple-obfs-0.0.5-486bebd9208539058e57e23a12f23103016e09b4/.pkgdir/simple-obfs/. /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/'
touch /home/lede/lede/staging_dir/target-mipsel_24kc_musl/root-ramips/stamp/.simple-obfs_installed
echo "simple-obfs" >> /home/lede/lede/staging_dir/target-mipsel_24kc_musl/pkginfo/simple-obfs.default.install
make[3]: Leaving directory '/home/lede/lede/package/lean/simple-obfs'
time: package/lean/simple-obfs/compile#0.11#0.03#0.16
make[3]: Entering directory '/home/lede/lede/feeds/helloworld/shadowsocks-rust'
rm -f /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built
touch /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built_check
/home/lede/lede/staging_dir/host/bin/upx --lzma --best /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/sslocal
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/sslocal: CantPackException: bad e_shstrndx

Packed 0 files.
Makefile:110: recipe for target '/home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built' failed
make[3]: *** [/home/lede/lede/build_dir/target-mipsel_24kc_musl/shadowsocks-rust-1.9.2/.built] Error 1
make[3]: Leaving directory '/home/lede/lede/feeds/helloworld/shadowsocks-rust'
time: package/feeds/helloworld/shadowsocks-rust/compile#0.09#0.03#0.16
package/Makefile:111: recipe for target 'package/feeds/helloworld/shadowsocks-rust/compile' failed
make[2]: *** [package/feeds/helloworld/shadowsocks-rust/compile] Error 2
make[2]: Leaving directory '/home/lede/lede'
package/Makefile:107: recipe for target '/home/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile' failed
make[1]: *** [/home/lede/lede/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/lede/lede'
/home/lede/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
还是会出错
