### ISSUE TITLE
取消 DNSMASQ 禁止解析IPV6地址 后Passwall延迟暴涨。

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1102]
无论是百度还是Google连接测试，延迟上涨1倍左右.
甚至出现 Google连通测试 直接失败

root@OpenWrt:~# curl -w "@/mnt/sda2/time.txt" -o NUL -s "www.baidu.com"
     time_namelookup:  0.070154s
     time_connect:  0.122168s
     time_appconnect:  0.000000s
     time_pretransfer:  0.122424s
     time_redirect:  0.000000s
     time_starttransfer:  0.175201s
                     ----------
          time_total:  0.185207s

**Comment by z826540272** [comment]
root@OpenWrt:~# curl -w "@/mnt/sda2/time.txt" -o NUL -s "www.baidu.com"
     time_namelookup:  0.001641s
        time_connect:  0.052771s
     time_appconnect:  0.000000s
    time_pretransfer:  0.053034s
       time_redirect:  0.000000s
  time_starttransfer:  0.105092s
                     ----------
          time_total:  0.115298s

打开后延迟回归正常。

**Comment by xiaorouji** [comment]
这个不是我可控制范围

**Comment by z826540272** [comment]
取消 禁用无效信息缓存 后 百度延迟恢复正常
因为查询不到ipv6地址所以不会缓存。
