### ISSUE TITLE
选择dns不过滤后台依然会运行chinadns-ng过滤

### ISSUE THREAD

**Issue by yaott2020-666** [xiaorouji/openwrt-passwall#1103]
如题，想独立启动chinadns-ng分流，就是设置不成功，建议dns设置"不过滤"就不要管dns的问题了

**Comment by lededev** [comment]
可以这样设置
https://github.com/xiaorouji/openwrt-passwall/issues/940

**Comment by yaott2020-666** [comment]
尝试过这么设置，但是解析速度比较慢，之前的passwall版本chinadns-ng的选项，功能上和我的需求一致，解析速度不错

**Comment by badgv** [comment]
过滤和不过滤，影响的是入口dnsmasq的解析策略问题，你的需求是什么说详细点呢

**Comment by yaott2020-666** [comment]
选择"不过滤"之后，passwall不再接管dns设置，只需要根据列表进行国内外分流即可，dns污染交给chinadns-ng独立运行即可

**Comment by yaott2020-666** [comment]
个人觉得与其这样还不如恢复以前的chinadns-ng的选项，dns解析快很多，移动用的很爽

**Comment by badgv** [comment]
> 过滤和不过滤，影响的是入口dnsmasq的解析策略问题，你的需求是什么说详细点呢

我现测试了一把，“不过滤”功能是正常的，过滤模式时候dnsmasq状态如下：
![image](https://user-images.githubusercontent.com/45598380/111399105-a0f31600-86ff-11eb-84ae-753fc8c0fa1f.png)
“不过滤”模式状态如下：
![image](https://user-images.githubusercontent.com/45598380/111399174-c718b600-86ff-11eb-9045-b4ae2d7dcb0d.png)

功能一切正常，没有此种问题

**Comment by badgv** [comment]
> 个人觉得与其这样还不如恢复以前的chinadns-ng的选项，dns解析快很多，移动用的很爽

其实不管你用哪个DNS插件，本质都是一样的，需要走代理解析的，都要走代理解析，不存在什么快不快的问题，首先你要搞清楚OP解析DNS的过程是怎么样的，我的DNS解析逻辑环境如下：
dnsmasq入口－按psw配置将DNS解析请求分为两组，国外的或GFW走代理解析（此时过滤模式为pdnsd，能过滤IPV6），其它的国外的被我adguardhome接管，可以在DNS过滤一定的广告。解析速度也是相当快的

**Comment by yaott2020-666** [comment]
首先，不过滤模式，你看看后台会有一个chinadns-ng的进程，就是在不过滤模式下还是会自动分流

其次，对于adguardhome，我之前是用adguardhome同时解析国内国外，效果不佳，我回去试一下你的方案。

灰常感谢！！！

**Comment by badgv** [comment]
> 首先，不过滤模式，你看看后台会有一个chinadns-ng的进程，就是在不过滤模式下还是会自动分流
> 
> 其次，对于adguardhome，我之前是用adguardhome同时解析国内国外，效果不佳，我回去试一下你的方案。
> 
> 灰常感谢！！！

这些什么chnadns-ng都是没有必要使用东西，我编译的时候根本没有编译这玩意儿，所以我的psw根本不会使用这玩意儿，默认带的这两个功能，足够上网使用了，一个是GFW模式，一个是国外IP模式。
![image](https://user-images.githubusercontent.com/45598380/111400202-cb45d300-8701-11eb-89c8-90e42e2d2222.png)
可能我没编译chinadns这功能是我没这BUG的主要原因。

**Comment by xiaorouji** [comment]
已修复

**Comment by lededev** [comment]
@stztao @xiaorouji 这么修改之后，DNS设置为nouse之后，代理域名表和域名白名单就都不生效了。还不如原来那样，默认启动chiandns-ng，然后可以用smartdns接管过滤部分的域名解析。

**Comment by lededev** [comment]
上一份PR在DNS选项为nonuse时总是不启动chinadns-ng，影响到我这种需要有passwall启动chinadns-ng并更新其相关数据，以及应用代理域名表和域名白名单功能的。为了兼顾双方的需要，增加了一个选项。

按上一份PR的逻辑，配置文件/etc/config/passwall中global小节增加项目always_use_chinadns_ng。
always_use_chinadns_ng如果不存在，则默认为0。
```
config global
        option always_use_chinadns_ng '0'
```
需要有passwall来运行chinadns-ng，在7913端口提供smartdns进行解析，则需自行修改配置文件为：
```
config global
        option always_use_chinadns_ng '1'
```

**Comment by lededev** [comment]
> 尝试过这么设置，但是解析速度比较慢，之前的passwall版本chinadns-ng的选项，功能上和我的需求一致，解析速度不错

用来smartdns之后，打开测试测速，解析速度的确比较慢。但解析慢的原因是对得到的所有域名查询结果IP进行了速度测试造成的，测试需要一定时间。
但是smartdns返回的唯一IP结果，是速度最快的结果，这就造成了目标网站的访问速度是最快的。
你需要持续访问并传输数据的是目标网站，这个才是提升上网速度的大头。
光是域名解析快有P用，难不成有人不浏览数据整天不停做域名解析么。

**Comment by yaott2020-666** [comment]
已经在smartdns第二服务器关闭了和测试有关的所有选项，尽量确保延迟只是由dns查询延迟和线路延迟产生的。但即使这样查询速度依然非常不理想

**Comment by lededev** [comment]
> 已经在smartdns第二服务器关闭了和测试有关的所有选项，尽量确保延迟只是由dns查询延迟和线路延迟产生的。但即使这样查询速度依然非常不理想

smartdns的设计目的就是目标IP最快，不是DNS查询速度最快，需要查询快就别用smartdns做下游啊，你可以把到7913端口的查询请求转给你的adg server嘛，加条iptables规则就行了。
