### ISSUE TITLE
为什么我的passwall编译出来没有本地DNS选项

### ISSUE THREAD

**Issue by kwokkakit** [xiaorouji/openwrt-passwall#1104]
![image](https://user-images.githubusercontent.com/758486/111364026-b5b5b680-86cb-11eb-8c35-4e39e0c61e21.png)

观察目前Passwall启动后，会有一个进程。

/var/etc/passwall/bin/chinadns-ng -v -b 0.0.0.0 -l 7914 -c 运营商DNS

目前是默认先拿LAN配置的DNS服务器，然后再拿运营商的。由于运营商的dns是被污染的，导致我的科学上网一直上不了。
然后我看别人在DNS这个地方，可以指定本地DNS。请教一下如何编译出这个选项？

![image](https://user-images.githubusercontent.com/758486/111366814-fa8f1c80-86ce-11eb-8b36-20efb1450b1e.png)

目前我只能手动执行

/var/etc/passwall/bin/chinadns-ng -v -b 0.0.0.0 -l 7914 -c 114.114.114.114,223.5.5.5 -m /var/etc/passwall/chnlist -M -t 127.0.0.1#7913 -g /var/etc/passwall/gfwlist.txt -f &

**Comment by db-one** [comment]
早取消了

**Comment by xiaorouji** [comment]
配置dnsmasq上游dns后，重启passwall即可
