### ISSUE TITLE
续#1103 , passwall选择不过滤后依然会更改dnsmasq的上游dns

### ISSUE THREAD

**Issue by yaott2020-666** [xiaorouji/openwrt-passwall#1108]
RT，重启passwall后luci--DHCP/DNS中的DNS 转发栏设置失效，需要重新保存并应用DHCP/DNS后才能改回来

**Comment by hplee0120** [comment]
我遇到的状况是开启adg作为dnsmasq上游后，手动点击重连wan后，国内就不通了。谷歌还是通的。必须关闭adg或者重新开启adg和passwall才正常。

**Comment by lededev** [comment]
你们是不是看了某篇文章之后，就执着的一定要把adg用起来啊，其实只需要下游有smartdns就够了，smartdns自定义配置那里加上一行
conf-file /etc/smartdns/anti-ad-smartdns.conf
就可以过滤广告了，至于定期更新广告过滤数据的脚本我也有发过，找不到那个帖子，再发一遍吧，让crontab定时执行这个脚本就行了。
adg挺大的，真心不推荐。
```
cat update-smartdns-anti-ad.sh
#!/bin/sh

AD_PATH=/tmp/anti-ad-for-smartdns.conf
SM_AD_PATH=/etc/smartdns/anti-ad-smartdns.conf

docp=0
/bin/rm -f $AD_PATH
if wget -q -P /tmp https://anti-ad.net/anti-ad-for-smartdns.conf; then
  if cmp -s $SM_AD_PATH $AD_PATH; then
    /bin/rm -f $AD_PATH
    exit 0
  elif [ -s $AD_PATH ]; then
    /bin/mv -f $AD_PATH $SM_AD_PATH
    docp=1
  else # download file size 0
    exit 1
  fi
fi

if [ $docp -eq 1 ]; then
  /etc/init.d/smartdns restart
fi

```

**Comment by yaott2020-666** [comment]
我是想把chinadns作为本地dns查询入口，通过chnlist和gfwlist分流到后端smartdns两个分别用做国内外dns服务器。达到查询国内域名是用国内dns，国外域名用国外dns。

**Comment by lededev** [comment]
> 我是想把chinadns作为本地dns查询入口，通过chnlist和gfwlist分流到后端smartdns两个分别用做国内外dns服务器。达到查询国内域名是用国内dns，国外域名用国外dns。

我在#940里发的设置方法就是你需要的这种方式嘛，把smartdns的国外端口配置成7913就实现分流了。当然现在因为你#1103后的改动，想这么设置，还需要编辑/etc/config/passwal配置文件，在global小节加上一行`option always_use_chinadns_ng '1'`。
就让passwall来维护chiandns-ng的chnlist和gfwlist数据更省事的。

**Comment by yaott2020-666** [comment]
看了一下后台，passwall里的chinadns-ng设置方法，好像是把Luci里的dhcp/dns的上游服务器作为chinadns-ng的国内，把passwall里的设置为国外，然后直接劫持dnsmasq强制设置chinadns-ng作为上游而不修改luci里dhcp/dns里的设置.

**Comment by yaott2020-666** [comment]
我觉得恢复  https://user-images.githubusercontent.com/59167936/107228962-3abc0900-6a58-11eb-9002-70faf884d1e9.png  
里面的选项比较好，然后在修改dnsmasq上游的时候顺便把Luci--DHCP/DNS里的上游选项改了，免得再luci--DHCP/DNS里保存应用就把passwall的劫持又改回去与其中相同

**Comment by lededev** [comment]
欢迎你提交代码，实现一个完美的方案。

**Comment by yaott2020-666** [comment]
按照你上面的做法我这边确实提升不少，突然又感觉没必要回退了。。。就按照你的方案吧，感谢解答！！
