### ISSUE TITLE
<谷歌连接>显示连接失败,但实际上谷歌，油管都是可以访问的

### ISSUE THREAD

**Issue by weweyes** [xiaorouji/openwrt-passwall#1109]
![pallwall](https://user-images.githubusercontent.com/59646715/111603232-1ac5f500-880f-11eb-8db1-abccbba88db0.jpg)

**Comment by yunxi993** [comment]
我的是更换节点，连接正常，但是访问不了google  youtube   ip111 里面测试全都是国内IP,需要等十几分钟才能正常访问.

**Comment by xiaorouji** [comment]
是不是DNS使用了pdnsd？换一种DNS方案试试（如Xray DoH）

**Comment by yunxi993** [comment]
> 是不是DNS使用了pdnsd？换一种DNS方案试试（如Xray DoH）

没有使用pdnsd，用的自定义DNS，PDNSD也尝试过，情况相同.

**Comment by z826540272** [comment]
是不是开了ipv6

**Comment by yunxi993** [comment]
> 是不是开了ipv6

以前也有开启ipv6 没出现过这种情况.
