### ISSUE TITLE
相同的节点在SSR可以用，在PASSWALL不能用咋回事呢？

### ISSUE THREAD

**Issue by slayercjc** [xiaorouji/openwrt-passwall#1111]
Xray 1.4.0 (Xray, Penetrates Everything.) Custom (go1.16.2 linux/amd64)
A unified platform for anti-censorship.
2021/03/19 08:43:14 [Info] infra/conf/serial: Reading config: /var/etc/passwall/TCP.json
2021/03/19 08:43:14 [Warning] core: Xray 1.4.0 started
2021/03/19 08:43:20 192.168.50.195:3619 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:37 192.168.50.195:3620 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:41 192.168.50.195:3621 accepted tcp:172.217.24.202:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:43:53 [Warning] [4149847411] app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [dial tcp: i/o timeout dial tcp: operation was canceled] > common/retry: all retry attempts failed
2021/03/19 08:44:07 192.168.50.88:56997 accepted tcp:172.64.130.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]
2021/03/19 08:44:10 192.168.50.88:58944 accepted tcp:172.64.131.33:443 [da7aae2f2e1d4e8e8727942b2c26abbe]

**Comment by jh0072110** [comment]
处理一下你的IP

**Comment by slayercjc** [comment]
> 处理一下你的IP

哪个IP

**Comment by xiaorouji** [comment]
节点发我邮箱

**Comment by slayercjc** [comment]
> 节点发我邮箱

邮箱地址是哪个？

**Comment by xiaorouji** [comment]
@slayercjc  xiaoroujixxoo@gmail.com

**Comment by slayercjc** [comment]
> @slayercjc [xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

发过去了

**Comment by slayercjc** [comment]
> @slayercjc [xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

是怎么回事，解决了吗

**Comment by xiaorouji** [comment]
更换DNS方案试试？你现在用的是pdnsd模式吗？

**Comment by slayercjc** [comment]
> 更换DNS方案试试？你现在用的是pdnsd模式吗？

对，用的pdnsd模式，几个我都换了 都不行

**Comment by slayercjc** [comment]
![image](https://user-images.githubusercontent.com/14236188/111746374-ed3d8200-88c8-11eb-9cd4-7bbb67ec5d7b.png)
这几个都用了，都不行。。。。都是延时

**Comment by xiaorouji** [comment]
我用了你的节点测试了，一切正常

**Comment by slayercjc** [comment]
> 我用了你的例程测试了，一切正常

正常？那我怎么是延时呢，奇怪了。。。

**Comment by slayercjc** [comment]
这个节点放SSR就没问题。。。

**Comment by hardyhuang818** [comment]
我也遇到了相同的问题，相同的节点SSRP可以使用，但passwall就不能科学上网，passwall开全局又可以。不知道哪里设置的问题。

**Comment by lfm09** [comment]
新版pw确实（部分节点）有这个问题，同一个节点，ssrp和vssr都可以海淘，但pw却无法海淘，开全局也一样。测试此前（20年10月初）的一个旧版pw无此问题。
