### ISSUE TITLE
日志节点内的时间比系统时间晚8个小时

### ISSUE THREAD

**Issue by stvber** [xiaorouji/openwrt-passwall#1113]
基于官方openwrt master 
passwall版本4-16

**Comment by xiaorouji** [comment]
调系统时区啊。。。
怎么感觉问的问题越来越水了。。。

**Comment by jh0072110** [comment]
哈哈哈哈哈哈哈哈哈

**Comment by stvber** [comment]
config system
        option hostname 'OpenWrt'
        option ttylogin '0'
        option log_size '64'
        option urandom_seed '0'
        option timezone 'CST-8'
        option zonename 'Asia/Shanghai'
        option log_proto 'udp'
        option conloglevel '8'
        option cronloglevel '5'

**Comment by stvber** [comment]
> 调系统时区啊。。。
> 怎么感觉问的问题越来越水了。。。

config system
option hostname 'OpenWrt'
option ttylogin '0'
option log_size '64'
option urandom_seed '0'
option timezone 'CST-8'
option zonename 'Asia/Shanghai'
option log_proto 'udp'
option conloglevel '8'
option cronloglevel '5'
系统上的时区如上的

**Comment by jh0072110** [comment]
大概是因为你拿CST（China Standard Time）减了8的缘故（狗头

**Comment by SharerMax** [comment]
@stvber 如果你说的是 xray 的日志时间，你可能缺少了  `zoneinfo-asia` 这个包，详细步骤如下：
> opkg update
> opkg install zoneinfo-asia  （选择对用的州即可，`asia` 此为亚洲，包含了中国的时区信息）
> /etc/init.d/system restart  (也可重启)

Ref: https://stackoverflow.com/questions/54035376/why-running-golangs-time-now-at-openwrt-always-get-utc-time
