### ISSUE TITLE
导入节点时Ws的节点不成功，要手动去改传输方式成websocket

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-passwall#1116]
导入节点时Ws的节点不成功，要手动去改传输方式成websocket

**Comment by xiaorouji** [comment]
用的是最新的源码吗？

**Comment by lllrrr2** [comment]
昨天的源码，

**Comment by lllrrr2** [comment]
vless://c4c72658-cccc-aaaa-8888-6ff91d728e94@domain08.qiu4.ml:443?encryption=none&security=tls&type=ws&host=a.test.com&path=%2fTKnyLfSWJxETws#a.test.com_vless_ws

格式是这样的

**Comment by xiaorouji** [comment]
用刚才提交的最新源码

**Comment by lllrrr2** [comment]
好，马上编译

**Comment by mulder125** [comment]
更新源码后ws解析正常不用手动修改了，另外也支持导入和导出URL了！
但发现一个bug：传输方式为TCP，伪装解析会失效，例如为http，实际解析出来为none

应该就是headerType=http没解析到，我只试了http伪装，不确定其他Type是否也会有异常

**Comment by xiaorouji** [comment]
@mulder125 分享链接发一下，注意改一下服务器地址

**Comment by mulder125** [comment]
节点是Vless (TCP + TLS + http伪装 路径/)，更新原码后用"导出分享URL"产生如下链接 (服务器地址已改为无效)
vless://8942f709-2c78-4a24-b186-x123ac0c796e@abc.vless.com:22217?headerType=http&host=abc.vless.com&path=%2F&type=tcp&encryption=none&security=tls&sni=abc.vless.com#ABC-VLESS(TCPTLS)

**Comment by xiaorouji** [comment]
@mulder125 感谢反馈，已修复

**Comment by mulder125** [comment]
更新原码后Vless URL暂没有发现问题，这issue应可以关闭了
