### ISSUE TITLE
能否优化一下启动速度？

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1119]
前段时间换隔壁Helloworld试了下，启动速度比较快
不过不支持ChinaDNS分流是比较大的问题.

目前Passwall的启动速度是有些慢了
我是mt7621路由器，不知道具体慢在哪里，是不是iptables.sh 导致的启动缓慢

切换服务器能否做到不重启整个逻辑只单独切换服务器节点？

**Comment by xiaorouji** [comment]
i5 x64 秒保存 还怎么优化呢

**Comment by BOBINIUNIU** [comment]
i3 x86, 从点击保存应用到插件运行大约8-10秒，这个速度我觉得是完全可以接受的。切换服务器应该重启整个逻辑，因为节点位置不一样。例如，一个美国节点和一个日本节点访问油管的IP肯定是不一样的，刷新DNS缓存是有必要的。
