### ISSUE TITLE
代理远程lanip

### ISSUE THREAD

**Issue by ygcaicn** [xiaorouji/openwrt-passwall#1121]
比如本地lan 192.168.8.1/24
远程的lan 192.168.6.1/24
远程的lan部署有Xray server，想要在本地lan中代理192.168.6.1/24网段，请问如何才能实现？

**Comment by xiaorouji** [comment]
目前逻辑不允许。你可以修改iptables脚本，添加一条命令到过滤laniplist前

**Comment by alschw** [comment]
@xiaorouji 大佬，我也遇到了同样的问题，使用zerotier组局域网反代流媒体，最后发现是内网ip无法走代理导致无法成功，即使在代理列表proxy_ip中添加了内网IP也不会生效，现在想让10.128.20.0/24强制走当前代理（TCP&UDP），“修改iptables脚本，添加一条命令到过滤laniplist前”，请问这个需要再哪里怎么添加？还望不吝赐教，感谢

**Comment by ygcaicn** [comment]
我的方法是在gen_laniplist中去掉要代理的远程lan

https://github.com/xiaorouji/openwrt-passwall/blob/3c71c34107db65700532b4a15c0787a5e2ab9057/luci-app-passwall/root/usr/share/passwall/iptables.sh#L136-L149

**Comment by alschw** [comment]
> 我的方法是在gen_laniplist中去掉要代理的远程lan
> 
> https://github.com/xiaorouji/openwrt-passwall/blob/3c71c34107db65700532b4a15c0787a5e2ab9057/luci-app-passwall/root/usr/share/passwall/iptables.sh#L136-L149

谢谢，我去掉了10.0.0.0/8，ipset也清除过，试了还是没有OK，同样代理在手机上设置为只bypass mainland china就是可以的，我再调试调试
