### ISSUE TITLE
新版强制使用ChinaDNS-NG后，过滤模式pdnsd不能使用，但xrayDOH可以使用

### ISSUE THREAD

**Issue by ncik20** [xiaorouji/openwrt-passwall#1125]
以下是使用pdnsd的日志，还请麻烦看一下，谢谢了。
2021/03/20 10:12:45 [Debug] [580946538] proxy/dokodemo: processing connection from: 192.168.1.3:61157
2021/03/20 10:12:45 [Info] [580946538] proxy/dokodemo: received request for 192.168.1.3:61157
2021/03/20 10:12:45 [Debug] [1450053478] proxy/dokodemo: processing connection from: 192.168.1.3:31105
2021/03/20 10:12:45 [Info] [1450053478] proxy/dokodemo: received request for 192.168.1.3:31105
2021/03/20 10:12:45 [Info] [580946538] app/dispatcher: default route for tcp:8.8.8.8:53
2021/03/20 10:12:45 [Info] [1450053478] app/dispatcher: default route for tcp:8.8.8.8:53
2021/03/20 10:12:45 [Info] [580946538] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:12:45 [Info] [1450053478] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:12:45 192.168.1.3:61157 accepted tcp:8.8.8.8:53 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:12:45 192.168.1.3:31105 accepted tcp:8.8.8.8:53 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:12:45 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:12:45 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:12:46 [Info] [580946538] proxy/vmess/outbound: tunneling request to tcp:8.8.8.8:53 via tcp:v2rayServer:55555
2021/03/20 10:12:46 [Info] [1450053478] proxy/vmess/outbound: tunneling request to tcp:8.8.8.8:53 via tcp:v2rayServer:55555
2021/03/20 10:12:46 [Debug] [618179403] proxy/dokodemo: processing connection from: 192.168.1.3:23151
2021/03/20 10:12:46 [Info] [618179403] proxy/dokodemo: received request for 192.168.1.3:23151
2021/03/20 10:12:46 [Info] [618179403] app/dispatcher: default route for tcp:8.8.8.8:53
2021/03/20 10:12:46 [Info] [618179403] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:12:46 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:12:46 192.168.1.3:23151 accepted tcp:8.8.8.8:53 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:12:46 [Info] [618179403] proxy/vmess/outbound: tunneling request to tcp:8.8.8.8:53 via tcp:v2rayServer:55555
2021/03/20 10:12:46 [Debug] [822590967] proxy/dokodemo: processing connection from: 192.168.1.3:33751
2021/03/20 10:12:46 [Info] [822590967] proxy/dokodemo: received request for 192.168.1.3:33751
2021/03/20 10:12:46 [Info] [822590967] app/dispatcher: default route for tcp:8.8.8.8:53
2021/03/20 10:12:46 [Info] [822590967] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:12:46 192.168.1.3:33751 accepted tcp:8.8.8.8:53 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:12:46 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:12:46 [Info] [822590967] proxy/vmess/outbound: tunneling request to tcp:8.8.8.8:53 via tcp:v2rayServer:55555
2021/03/20 10:12:47 [Info] [580946538] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/03/20 10:12:47 [Info] [580946538] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/03/20 10:12:47 [Info] [1450053478] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/03/20 10:12:47 [Info] [1450053478] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/03/20 10:12:47 [Info] [618179403] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/03/20 10:12:47 [Info] [618179403] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/03/20 10:12:47 [Info] [822590967] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > context canceled
2021/03/20 10:12:47 [Info] [822590967] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled

这个是使用xrayDOH可以使用的日志
2021/03/20 10:13:48 [Debug] [2079719897] proxy/dokodemo: processing connection from: 192.168.1.3:52586
2021/03/20 10:13:48 [Info] [2079719897] proxy/dokodemo: received request for 192.168.1.3:52586
2021/03/20 10:13:48 [Debug] [1743328316] proxy/dokodemo: processing connection from: 192.168.1.3:52584
2021/03/20 10:13:48 [Info] [1743328316] proxy/dokodemo: received request for 192.168.1.3:52584
2021/03/20 10:13:48 [Info] [1743328316] app/dispatcher: sniffed domain: dns.google
2021/03/20 10:13:48 [Info] [1743328316] app/dispatcher: default route for tcp:dns.google:443
2021/03/20 10:13:48 [Info] [2079719897] app/dispatcher: sniffed domain: dns.google
2021/03/20 10:13:48 [Info] [2079719897] app/dispatcher: default route for tcp:dns.google:443
2021/03/20 10:13:48 [Info] [1743328316] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:13:48 [Info] [2079719897] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:13:48 192.168.1.3:52584 accepted tcp:8.8.8.8:443 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:13:48 192.168.1.3:52586 accepted tcp:8.8.8.8:443 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:13:48 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:13:48 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:13:48 [Info] [1743328316] proxy/vmess/outbound: tunneling request to tcp:dns.google:443 via tcp:v2rayServer:55555
2021/03/20 10:13:48 [Info] [2079719897] proxy/vmess/outbound: tunneling request to tcp:dns.google:443 via tcp:v2rayServer:55555
2021/03/20 10:13:48 [Info] [2079719897] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > context canceled
2021/03/20 10:13:48 [Debug] [594627978] proxy/dokodemo: processing connection from: 192.168.1.3:42512
2021/03/20 10:13:48 [Info] [594627978] proxy/dokodemo: received request for 192.168.1.3:42512
2021/03/20 10:13:48 [Info] [594627978] app/dispatcher: sniffed domain: www.google.com
2021/03/20 10:13:48 [Info] [594627978] app/dispatcher: default route for tcp:www.google.com:443
2021/03/20 10:13:48 [Info] [594627978] transport/internet/websocket: creating connection to tcp:v2rayServer:55555
2021/03/20 10:13:48 192.168.1.3:42512 accepted tcp:216.58.220.196:443 [8989e598887f4bf0b9243460f8af55d4]
2021/03/20 10:13:48 [Debug] transport/internet: dialing to tcp:v2rayServer:55555
2021/03/20 10:13:48 [Info] [594627978] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:v2rayServer:55555

**Comment by xiaorouji** [comment]
用路由器执行下面命令对比一下
nslookup www.google.com 127.0.0.1#7913
nslookup www.google.com 127.0.0.1#7914

**Comment by ncik20** [comment]
> 用路由器执行下面命令对比一下
> nslookup [www.google.com](http://www.google.com) 127.0.0.1#7913
> nslookup [www.google.com](http://www.google.com) 127.0.0.1#7914

以下是设置成pdnsd用nslookup的结果
root@OpenWrt:~# nslookup www.google.com 127.0.0.1#7913
Server:         127.0.0.1
Address:        127.0.0.1#7913

Name:      www.google.com
Address 1: 216.58.220.196
** server can't find www.google.com: SERVFAIL
root@OpenWrt:~# nslookup www.google.com 127.0.0.1#7914
Server:         127.0.0.1
Address:        127.0.0.1#7914

Name:      www.google.com
Address 1: 216.58.220.196
** server can't find www.google.com: SERVFAIL

**Comment by xiaorouji** [comment]
直接 nslookup www.google.com 呢？

**Comment by ncik20** [comment]
> 直接 nslookup [www.google.com](http://www.google.com) 呢？

好像也是差不多的样子
root@OpenWrt:~# nslookup www.google.com
Server:         127.0.0.1
Address:        127.0.0.1#53

Name:      www.google.com
Address 1: 216.58.220.196
** server can't find www.google.com: SERVFAIL

**Comment by xiaorouji** [comment]
那就没问题啊

**Comment by ncik20** [comment]
> 那就没问题啊

刚在pdnsd模式下访问google网页，的确好像是没问题，但passwall测试谷歌连接还是失败的。
之前也这样测试过，实际访问好像也是不行的，所以提了issue，还是感谢大佬及时的回复，非常感谢。

**Comment by xiaorouji** [comment]
@ncik20 你需要更新最新源码。你现在这个情况是不是nslookup的时候要等几秒？这个情况最新源码已经修复了

**Comment by ncik20** [comment]
> @ncik20 你需要更新最新源码。你现在这个情况是不是nslookup的时候要等几秒？这个情况最新源码已经修复了

还真的是这样，原来如此，谢谢大佬，这就去重新编译下。
