### ISSUE TITLE
直连名单添加Amazon.com不起效

### ISSUE THREAD

**Issue by passsd** [xiaorouji/openwrt-passwall#1127]
删除代理列表内默认固有的域名（如abc.com,amazon.com）改填入直连列表后并不生效，而是会同时向本地DNS和远程DNS发出请求。
非代理列表固有域名填入直连列表后可正常生效，只会向本地dns发出请求。

已尝试过清空IPSET,并确认了tmp/etc/dnsmasq-passwall.d下01-direct_host.conf 和99-proxy_host.conf内更改已生效。

**Comment by xiaorouji** [comment]
很大可能被gfwlist命中了

**Comment by passsd** [comment]
> 很大可能被gfwlist命中了

修改gfwlist后确实可以了。原以为直连列表是最高优先级的，没想到后面还有一招大喇叭。

**Comment by xiaorouji** [comment]
我会抽空优化一下

**Comment by passsd** [comment]
> 我会抽空优化一下

多谢大佬🙏
