### ISSUE TITLE
升级xray1.4后无法连接

### ISSUE THREAD

**Issue by YYTB** [xiaorouji/openwrt-passwall#1129]
隔壁xray也有反映，使用passwall升级xray1.4后无法连接，有一样的吗？
普通vmess协议

**Comment by xiaorouji** [comment]
你这什么日志都不提供，怎么帮你解决？

**Comment by lllrrr2** [comment]
昨晚编译的1.4 Vless可以正常使用。

**Comment by hcym** [comment]
今天早上的，普通tcp正常，还有ws也正常，那个velss的还没用过

**Comment by imoldchen** [comment]
> 隔壁xray也有反映，使用passwall升级xray1.4后无法连接，有一样的吗？
> 普通vmess协议

是不是 DNS 用的 Xray DNS(DoH) 选项，我用这一项也无法解析，换成pdnsd正常。
