### ISSUE TITLE
好像发现了一个BUG。在负载均衡中看到的节点尽然少了

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-passwall#1130]
直接上图吧。
![image](https://user-images.githubusercontent.com/61368564/112269025-cdd09b80-8cb2-11eb-9a00-9fc6d992e437.png)
![image](https://user-images.githubusercontent.com/61368564/112269064-d75a0380-8cb2-11eb-982d-e7d04d2dc544.png)
只能看到节点列表中的第一个和最后一个

**Comment by lllrrr2** [comment]
昨天晚上最新源码编译的

**Comment by ma20at** [comment]
那是因为你的列表里的节点ip前面有空格就会这样。

**Comment by lllrrr2** [comment]
仔细看图，我的都是导入的，三个vless的配置都一样只是服务是器地址不同，且不是用的ip都是域名

**Comment by lllrrr2** [comment]
每个节点测试了，可以正常使用，也没有空格。

**Comment by lllrrr2** [comment]
![image](https://user-images.githubusercontent.com/61368564/112289867-a0431c80-8cc9-11eb-8917-a66ea5b693e8.png)
![image](https://user-images.githubusercontent.com/61368564/112289959-bbae2780-8cc9-11eb-9ace-3aed07b61f2d.png)
发现了共同点，只有Vless的点会有影响，只会出现最后一个。前面的都没有了，Trojan的节点就都可以。

**Comment by xiaorouji** [comment]
把配置弄成复现状态，然后把/etc/config/passwall发我邮箱(xiaoroujixxoo@gmail.com)

**Comment by lllrrr2** [comment]
已经发了，请查收
