### ISSUE TITLE
PDNSD模式下，www.youtube.com 不能DNS缓存

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#1132]
每次查询会耗时RTT，google可以缓存，www.youtube.com不能，切换到dns2socks可以正常缓存。

dig -p 53 www.youtube.com

; <<>> DiG 9.16.13 <<>> -p 53 www.youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4538
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1024
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        86400   IN      CNAME   youtube-ui.l.google.com.
youtube-ui.l.google.com. 86400  IN      A       216.58.221.238
youtube-ui.l.google.com. 86400  IN      A       172.217.161.174
youtube-ui.l.google.com. 86400  IN      A       142.250.199.78
youtube-ui.l.google.com. 86400  IN      A       172.217.24.206
youtube-ui.l.google.com. 86400  IN      A       172.217.161.142
youtube-ui.l.google.com. 86400  IN      A       172.217.163.238

;; Query time: 109 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Thu Mar 25 07:33:20 CST 2021
;; MSG SIZE  rcvd: 174

**Comment by xiaorouji** [comment]
因为没有在pdnsd配置文件开启缓存。
一般情况下交给dnsmasq作为缓存就够了

**Comment by z826540272** [comment]
> 因为没有在pdnsd配置文件开启缓存。
> 一般情况下交给dnsmasq作为缓存就够了

实测这个域名不能缓存，每次查询耗时100多ms，其他域名大多正常，可以dig看看

**Comment by yunxi993** [comment]
![image](https://user-images.githubusercontent.com/59167936/112466130-76105e00-8da0-11eb-951e-bdc5aabf09ec.png)
路由器自身 TCP 代理模式
路由器自身 UDP 代理模式
这两个选择默认与选择防火墙表、中国列表以为有什么区别?

**Comment by xiaorouji** [comment]
; <<>> DiG 9.16.13 <<>> -p 53 www.youtube.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 40128
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.youtube.com.               IN      A

;; ANSWER SECTION:
www.youtube.com.        599     IN      A       142.250.179.206
www.youtube.com.        599     IN      A       172.217.20.110
www.youtube.com.        599     IN      A       142.250.179.142
www.youtube.com.        599     IN      A       216.58.214.14
www.youtube.com.        599     IN      A       216.58.208.110
www.youtube.com.        599     IN      A       172.217.17.46
www.youtube.com.        599     IN      A       172.217.168.206

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Apr 06 12:48:10 CST 2021
;; MSG SIZE  rcvd: 156
