### ISSUE TITLE
GRPC模式支持

### ISSUE THREAD

**Issue by wi11iamzhao** [xiaorouji/openwrt-passwall#1136]
V2RAY 4.36和Xray 1.4中引入了新的传输方式gRPC，希望能添加支持

**Comment by xiaorouji** [comment]
私下已经支持了，不过我想等xray出新版本，到时候再提交上来。不然某些人又会说天天频繁更新

**Comment by wi11iamzhao** [comment]
> 私下已经支持了，不过我想等xray出新版本，到时候再提交上来。不然某些人又会说天天频繁更新

OK，等待提交…
不过xray最近更新比较缓慢的样子
