### ISSUE TITLE
订阅设置里丢弃与实际不一致

### ISSUE THREAD

**Issue by wangjianpro** [xiaorouji/openwrt-passwall#1137]
请教一个问题，r2s固件ext4版本更新时未保存系统设置，但是passwall里订阅时设置的丢弃与实际丢弃不一致，把我过去的版本里曾经设置过的丢弃也丢弃了，而且现在还改不回来，这是怎么回事？是不是一定要低格存储卡？

**Comment by xiaorouji** [comment]
不保留配置升级
