### ISSUE TITLE
UDP好像出现了些问题…

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall#1138]
同时选择TCP和UDP节点的话…会导致无法上网…同时软路由后台也会比较难进去…
用的是immortalwrt的18.06-k5.4源码
（开始打猛汉突然发现的bug@.@）

**Comment by xiaorouji** [comment]
日志发一下？
程序日志，TCP，UDP日志都发一下。
我也是这样用，但是我没有复现。

**Comment by jh0072110** [comment]
> 日志发一下？
> 程序日志，TCP，UDP日志都发一下。
> 我也是这样用，但是我没有复现。

等我砍完龙啊😂😂😂

**Comment by jh0072110** [comment]
完蛋，好像又正常了，等出问题再说吧=。=

**Comment by jh0072110** [comment]
我就不重新开issue了，好像跟我上一个问题一样，提交后会随机的不生效，因为随机…所以上回也没查出来……先这么着吧……
