### ISSUE TITLE
编译失败（请问这个问题怎么解決）

### ISSUE THREAD

**Issue by sayakaextra** [xiaorouji/openwrt-passwall#1140]
tar: Exiting with failure status due to previous errors
Makefile:504: recipe for target '/home/ki/lede/build_dir/target-x86_64_musl/boost_1_73_0/.prepared_f0ef1b2d0c2e28698d71e9698eabbffd_6664517399ebbbc92a37c5bb081b5c53' failed
make[2]: *** [/home/ki/lede/build_dir/target-x86_64_musl/boost_1_73_0/.prepared_f0ef1b2d0c2e28698d71e9698eabbffd_6664517399ebbbc92a37c5bb081b5c53] Error 2
make[2]: Leaving directory '/home/ki/lede/feeds/packages/libs/boost'
time: package/feeds/packages/boost/compile#27.25#6.70#30.29
package/Makefile:111: recipe for target 'package/feeds/packages/boost/compile' failed
make[1]: *** [package/feeds/packages/boost/compile] Error 2
make[1]: Leaving directory '/home/ki/lede'
/home/ki/lede/include/toplevel.mk:222: recipe for target 'package/lean/openwrt-passwall/luci-app-passwall/compile' failed
make: *** [package/lean/openwrt-passwall/luci-app-passwall/compile] Error 2

**Comment by zxlhhyccc** [comment]
> tar: Exiting with failure status due to previous errors
> Makefile:504: recipe for target '/home/ki/lede/build_dir/target-x86_64_musl/boost_1_73_0/.prepared_f0ef1b2d0c2e28698d71e9698eabbffd_6664517399ebbbc92a37c5bb081b5c53' failed
> make[2]: *** [/home/ki/lede/build_dir/target-x86_64_musl/boost_1_73_0/.prepared_f0ef1b2d0c2e28698d71e9698eabbffd_6664517399ebbbc92a37c5bb081b5c53] Error 2
> make[2]: Leaving directory '/home/ki/lede/feeds/packages/libs/boost'
> time: package/feeds/packages/boost/compile#27.25#6.70#30.29
> package/Makefile:111: recipe for target 'package/feeds/packages/boost/compile' failed
> make[1]: *** [package/feeds/packages/boost/compile] Error 2
> make[1]: Leaving directory '/home/ki/lede'
> /home/ki/lede/include/toplevel.mk:222: recipe for target 'package/lean/openwrt-passwall/luci-app-passwall/compile' failed
> make: *** [package/lean/openwrt-passwall/luci-app-passwall/compile] Error 2

你这个是boost报错，估计是没开梯子或者梯子不给力。。。。

**Comment by sayakaextra** [comment]
好 謝謝我再試試
