### ISSUE TITLE
passwall的负载均衡打开网页还不错，但下载慢如蜗牛，请问什么原因？

### ISSUE THREAD

**Issue by zxlhhyccc** [xiaorouji/openwrt-passwall#1141]
如题。。。。使用的是haproxy进行负载均衡。。。。

**Comment by hcym** [comment]
这个碰巧是慢的节点吧，下载大家伙还是切回大宽带节点

**Comment by zxlhhyccc** [comment]
> 这个碰巧是慢的节点吧，下载大家伙还是切回大宽带节点

未开负载均衡下载和开启负载均衡下载，速度不一样。。。。

**Comment by shoushi01** [comment]
你只保留1个节点在haproxy里面，再测试速度是否一样。大概率是慢节点拖累了快节点，导致体验差
