### ISSUE TITLE
麻烦能不能把自定义国内DNS的功能回归，现在已经不用smartDNS，但是界面中自定义代理列表dns还是指向了7913端口

### ISSUE THREAD

**Issue by chenxuan5858** [xiaorouji/openwrt-passwall#1142]
![1](https://user-images.githubusercontent.com/33675890/112753941-672de380-900c-11eb-9ba7-a0202e856fb7.PNG)

**Comment by zxlhhyccc** [comment]
q其实可以设置其他端口，只是dns显示未运行，但可以正常使用。。。。

**Comment by badgv** [comment]
其实不需要，在dnsmasq里面－基本设置－DNS转发，就定义了国内DNS功能
