### ISSUE TITLE
4-19编译出错

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#1145]
![image](https://user-images.githubusercontent.com/75249507/113138811-ddbf2100-9258-11eb-94f7-9d5624cc8a38.jpeg)

**Comment by OleStore** [comment]
https://github.com/fw876/helloworld/pull/457/commits/b09f2eb8a6dc0fee366ff551144ad9ade1423f39

**Comment by z1790** [comment]
把xray的hash改成0dfedb6e133f431e9588a84b7a36112e058bf09ced2d10ffe603ab0db6610430 就行了
