### ISSUE TITLE
Xray core编译出来显示1.4.0

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall#1148]
嗯…就是题目上的问题…

**Comment by jh0072110** [comment]
> 不然呢？1.4.1现在还是pre-release，又不是latest

不要为了抬杠而抬杠好么…
![image](https://user-images.githubusercontent.com/50496854/113229521-b8b6c680-92c9-11eb-8e58-95af39acab0a.png)

**Comment by tritu** [comment]
cuz u use the xray in openwrt src, not in passwall repo.

**Comment by BOBINIUNIU** [comment]
今天早上编译的，发现还是1.40.  
feeds.conf.default 里已经增加了 src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main
编译前已经执行过
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
是我哪里操作错了吗？

**Comment by jh0072110** [comment]
如 tritu 所说，问题找到了，优先编译了openwrt源里的core文件，我在actions里rm -rf了源码中的core，现在一切正常了～
