### ISSUE TITLE
PSW 都需要依赖kernel哪些模块？

### ISSUE THREAD

**Issue by matthuo333** [xiaorouji/openwrt-passwall#1155]
之前使用kernel 3.x ,其中网络相关模块，是齐全的。但由于使用第三方新版系统，所带的kernel是精简的（不过最近版本的ipset 模块已经被选择为M 状态），所以导致上层PSW，Clash都不能出海。
当前，已经查看系统内ipset 已经加载（查看下图），但是任然不能出海，所以想请问，还需要依赖哪些模块？好之后安装加载进来。
![image](https://user-images.githubusercontent.com/55862904/113374246-40bad000-939f-11eb-9163-258b8b0dc2f9.png)

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall/blob/d45c3b3119cc774cf7a6602055fdea0fb629110d/luci-app-passwall/Makefile#L88
