### ISSUE TITLE
通过haproxy负载，传输方式为WebSocket 如何设Host

### ISSUE THREAD

**Issue by fscarmen** [xiaorouji/openwrt-passwall#1165]
节点只能用ws方式，多个节点可以相同的uuid和path，但域名不同，请问WebSocket Host和域名如何设？

**Comment by zxlhhyccc** [comment]
> 节点只能用ws方式，多个节点可以相同的uuid和path，但域名不同，请问WebSocket Host和域名如何设？

域名没关系。。。。

**Comment by xiaorouji** [comment]
允许不安全连接
前提是服务端没有开启强制验证
