### ISSUE TITLE
V2ray 4.37.3编译不通过

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#1177]
![无标题](https://user-images.githubusercontent.com/75249507/114666993-82e5f900-9d31-11eb-9a28-9f0d3f2c6619.png)

**Comment by greennyreborn** [comment]
一样的问题

**Comment by xiaorouji** [comment]
Fix.

**Comment by OleStore** [comment]
> Fix.

大佬速度快啊
