### ISSUE TITLE
xray 无法正常启动

### ISSUE THREAD

**Issue by yaott2020-666** [xiaorouji/openwrt-passwall#1378]
更新了最新源码，编译完之后，xray无法正常启动，日志：

mmap: cannot allocate memory

奇怪的是，如果手动执行xray run --config /var/etc/passwall/TCP_*.json
xray正常工作没有报错

**Comment by xiaorouji** [comment]
https://github.com/XTLS/Xray-core/issues/602

**Comment by yaott2020-666** [comment]
成了，多谢
