### ISSUE TITLE
[建议] 建议淘汰插件自身的分流功能，改用*ray分流功能

### ISSUE THREAD

**Issue by yaott2020-666** [xiaorouji/openwrt-passwall#1547]
rt，插件自身的分流功能因规则没有更新失效，*ray分流功能更加强大，配合不断更新的geo*.dat，不仅可以分流国内外  gfw 国内外，还可以分流流媒体，甚至可以搭配geo*.dat分流自己想分流的网站，不仅仅局限在gfw/chinalist之中，希望大佬可以考虑考虑

**Comment by smallprogram** [comment]
你直接xray分流。客户端设置直链不就行了

**Comment by yaott2020-666** [comment]
总是需要分流的吧，国内外 gfwlist 也算分流，如果可以统一使用xray/v2ray分流，可以精简一下功能。

**Comment by smallprogram** [comment]
> 总是需要分流的吧，国内外 gfwlist 也算分流，如果可以统一使用xray/v2ray分流，可以精简一下功能。

你先了解一下 [v2ray-rules-dat](https://github.com/Loyalsoldier/v2ray-rules-dat)

**Comment by yaott2020-666** [comment]
知道啊，规则丰富，可以自定义分流方式

**Comment by ShanStone** [comment]
分流节点我记得是基于v2ray/xray实现的，支持geoip和geosite

**Comment by greennyreborn** [comment]
你可以全局代理，然后自己配规则管理不就好了
