### ISSUE TITLE
建议添加xray默认dns配置

### ISSUE THREAD

**Issue by yaott2020-666** [xiaorouji/openwrt-passwall#1570]
用xray分流的时候经常出现这种情况：

netstat -anp | grep xray | grep :53

udp   162816      0 10.8.0.1:53             0.0.0.0:*                           18998/xray
udp   152832      0 10.8.0.1:53             0.0.0.0:*                           18998/xray

貌似xray请求的dns地址和端口有问题

当设置xray分流模式为 IPOnDemand 或者 IPIfNonMatch 时，建议添加xray默认dns配置
...
{
"dns": {
    "servers": ["localhost"]
}
}
...

**Comment by xiaorouji** [comment]
passwall并不会用解析DNS服务监听53端口，而是使用dnsmasq。

**Comment by xiaorouji** [comment]
你用ps -w 看看 pid 18998是不是passwall调用的xray就知道了
