### ISSUE TITLE
[建议]  添加接口出口

### ISSUE THREAD

**Issue by yaotthaha** [xiaorouji/openwrt-passwall#1616]
## 你的功能请求是否与问题有关？ 请描述。

配合 Wireguard 复杂

## 描述你想要的解决方案 

可以利用 *ray OutBound --- Freedom --- Sockopt 给流量打 mark ，配合几条 ip 规则，完美分流流量到接口

可以参考：https://xtls.github.io/document/level-2/redirect.html

## 描述你考虑过的替代方案

目前方案就这个比较便捷简单，其他方案复杂

**Comment by sjtuross** [comment]
负载均衡设置里绑定节点和接口会自动添加静态路由，尽管你不用负载均衡

**Comment by 0xffffharry** [comment]
建议先点链接进去看看，你误解我的意思了

**Comment by sjtuross** [comment]
我看过，我说的当然不是完全的替代方案

对于代理流量，打了标记，最终还是要代理，路由表的选择决定了节点从哪个接口出去，用我之前说的配合现有的分流规则已经可以实现

对于直连流量，打标记选择出口，其实是干了mwan3的事情，mwan3已经可以实现

**Comment by 0xffffharry** [comment]
你还是没搞懂我的意思，是接口本身作为节点，不是节点走指定出口，还要配合xray分流，和你讲的不一样

**Comment by sjtuross** [comment]
你是要把wireguard出口当节点用是吧？那用mwan3分流不行吗？没必要用passwall了吧

**Comment by 0xffffharry** [comment]
但是我还要用上xray的分流，有教育网流量需要通过socks5转发，不只是gfw分流就可以的
