### ISSUE TITLE
v2ray-core failed to build 

### ISSUE THREAD

**Issue by openips** [xiaorouji/openwrt-passwall#1867]
## 描述bug(必填)
最新的官方master代码编译时提示v2ray-core failed to build  编译失败
## 复现步骤(必填)
更新openwrt git和package

## 你想要实现的目的(必填)
编译官方代码的passwall固件

## 日志信息(必填！)
SHELL= flock /LEDE/openwrt-psw/tmp/.root-copy.flock -c 'cp -fpR /LEDE/openwrt-psw/build_dir/target-x86_64_musl/boost_1_78_0/.pkgdir/boost-system/. /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/'
touch /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/stamp/.boost-system_installed
echo "boost-system" >> /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
mkdir -p /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /LEDE/openwrt-psw/tmp/.root-copy.flock -c 'cp -fpR /LEDE/openwrt-psw/build_dir/target-x86_64_musl/boost_1_78_0/.pkgdir/boost/. /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/'
touch /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/stamp/.boost_installed
echo "boost" >> /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/pkginfo/boost.default.install
make[3]: Leaving directory '/LEDE/openwrt-psw/feeds/packages/libs/boost'
time: package/feeds/packages/boost/compile#1.26#0.76#1.65
make[3]: Entering directory '/LEDE/openwrt-psw/feeds/diy1/trojan-plus'
mkdir -p /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/stamp
SHELL= flock /LEDE/openwrt-psw/tmp/.root-copy.flock -c 'cp -fpR /LEDE/openwrt-psw/build_dir/target-x86_64_musl/trojan-plus-10.0.3/.pkgdir/trojan-plus/. /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/'
touch /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/root-x86/stamp/.trojan-plus_installed
echo "trojan-plus" >> /LEDE/openwrt-psw/staging_dir/target-x86_64_musl/pkginfo/trojan-plus.default.install
make[3]: Leaving directory '/LEDE/openwrt-psw/feeds/diy1/trojan-plus'
time: package/feeds/diy1/trojan-plus/compile#0.13#0.04#0.16
make[3]: Entering directory '/LEDE/openwrt-psw/feeds/diy1/v2ray-core'
rm -f /LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.built
touch /LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.built_check
CONFIG_GOLANG_MOD_CACHE_WORLD_READABLE="" GO_BUILD_CACHE_DIR="/LEDE/openwrt-psw/tmp/go-build" GO_MOD_CACHE_DIR="/LEDE/openwrt-psw/dl/go-mod-cache" GO_MOD_ARGS="-modcacherw" GO_PKG="github.com/v2fly/v2ray-core/v4" GO_INSTALL_EXTRA="" GO_INSTALL_ALL="" GO_SOURCE_ONLY="" GO_BUILD_PKG="github.com/v2fly/v2ray-core/v4/main" GO_EXCLUDES="" GO_GO_GENERATE="" GO_INSTALL_BIN_PATH="/usr/bin" BUILD_DIR="/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0" GO_BUILD_DIR="/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.go_work/build" GO_BUILD_BIN_DIR="/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.go_work/build/bin" GO_BUILD_DEPENDS_PATH="/usr/share/gocode" GO_BUILD_DEPENDS_SRC="/LEDE/openwrt-psw/staging_dir/target-x86_64_musl/usr/share/gocode/src" GOOS="linux" GOARCH="amd64" GO386="" GOAMD64="v1" GOARM="" GOMIPS="" GOMIPS64="" GOPPC64="" CGO_ENABLED=1 CC="x86_64-openwrt-linux-musl-gcc" CXX="x86_64-openwrt-linux-musl-g++" CGO_CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0=v2ray-core-4.44.0 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_CPPFLAGS="-I/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/include -I/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include/fortify -I/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/include" CGO_CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -Wno-error=unused-but-set-variable -Wno-error=unused-result -fmacro-prefix-map=/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0=v2ray-core-4.44.0 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" CGO_LDFLAGS="-L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -znow -zrelro" GOPATH="/LEDE/openwrt-psw/build_dir/target-x86_64_musl/v2ray-core-4.44.0/.go_work/build" GOCACHE="/LEDE/openwrt-psw/tmp/go-build" GOMODCACHE="/LEDE/openwrt-psw/dl/go-mod-cache" GOENV=off /usr/bin/env bash /LEDE/openwrt-psw/feeds/packages/lang/golang//golang-build.sh build -v -trimpath -ldflags "all=-buildid '1648807534' -linkmode external -extldflags '-L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -Wl,-z,now -Wl,-z,relro'"        -ldflags "-s -w -X github.com/v2fly/v2ray-core/v4.build=OpenWrt -X github.com/v2fly/v2ray-core/v4.version=4.44.0 -buildid '1648807534' -linkmode external -extldflags '-L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/usr/lib -L/LEDE/openwrt-psw/staging_dir/toolchain-x86_64_gcc-11.2.0_musl/lib -Wl,-z,now -Wl,-z,relro'"
Finding targets

Building targets

make[3]: Leaving directory '/LEDE/openwrt-psw/feeds/diy1/v2ray-core'
time: package/feeds/diy1/v2ray-core/compile#61.92#11.09#60.18
    ERROR: package/feeds/diy1/v2ray-core failed to build.
make[2]: Leaving directory '/LEDE/openwrt-psw'
make[1]: Leaving directory '/LEDE/openwrt-psw'

## 截图

![image](https://user-images.githubusercontent.com/47168453/161365037-2c011655-9089-4c2a-8bbd-6377c9a0fe6f.png)

## 系统相关信息(必填)

[openwrt-passwall](https://github.com/xiaorouji/openwrt-passwall commit 4f0cdd870872ca02876ad66eab8ac99eeade70bf
[openwrt-passwall](https://github.com/xiaorouji/openwrt-passwall ;luci commit 37f598eec05a463e3ab782e40ee722ba2cb6069e

**Comment by Lienol** [comment]
不支持Golang 1.8
