### ISSUE TITLE
希望能进一步完善自动切换功能

### ISSUE THREAD

**Issue by CirnoSalt** [xiaorouji/openwrt-passwall#614]
目前psw的自动切换功能需要手工添加节点，
虽然可以避免误切换至机场高倍率节点，但对于一些有几十数百个节点的机场/订阅有些不友好。

假设能将【节点订阅】中的“过滤关键字“功能在自动切换中也实现就非常方便了，
这样一来就可以通过设置关键字过滤来做到全自动故障转移的同时还能避免切换至高倍率节点。

**Comment by AnthonyZhai** [comment]
同样需要，自动ping一下最快的节点

**Comment by monokoo** [comment]
目前使用Xray分流自动切换功能还有问题，切换后一直检测有问题，然后就开始频繁顺序切换下去了

**Comment by xiaorouji** [comment]
> 目前使用Xray分流自动切换功能还有问题，切换后一直检测有问题，然后就开始频繁顺序切换下去了
> edit: 排查了一下，发现是xray分流的节点配置被自动清空了，至于为何会被自动清空就需要看脚本逻辑了。。

已修复

**Comment by monokoo** [comment]
> > 目前使用Xray分流自动切换功能还有问题，切换后一直检测有问题，然后就开始频繁顺序切换下去了
> > edit: 排查了一下，发现是xray分流的节点配置被自动清空了，至于为何会被自动清空就需要看脚本逻辑了。。
> 
> 已修复

大佬有tg吗
