### ISSUE TITLE
luci-app-passwall下使用v2ray无法代理IPv6

### ISSUE THREAD

**Issue by tritu** [xiaorouji/openwrt-passwall#620]
luci-app-passwall下使用v2ray（vmess和vless均尝试过）无法代理IPv6。
查看passwall生成的json，发现dokodemo-door的sockopt没有使用tproxy方法而是采用的redirect。而redirect方式不能代理IPv6。
[https://www.v2fly.org/chapter_02/05_transport.html#sockoptobject](url)当 Dokodemo-door 中指定了 followRedirect，且 sockopt.tproxy 为空时，sockopt.tproxy 的值会被设为 "redirect"。
能否考虑增加tproxy选项（当然透明代理的iptables部分也需要相应变化）提供对IPv6代理的支持，谢谢

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/b98fdd502123a5a3c73713feaf8006440949152a
