### ISSUE TITLE
请求增加 禁止境外ipv6 DNS解析 功能

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#688]
电脑手机有ipv6地址，希望在passwall通过代理dns返回数据的时候过滤掉AAAA记录。这样不影响一些ipv6网站访问，
同时也不会影响翻墙速度。
比dnsmasq 过滤 aaaa 功能要好得多。

目标：代理 DNS 只返回 ipv4 结果，国内dns不过滤解析结果。

相关代码参考：
https://github.com/coolsnowwolf/lede/issues/3121
https://github.com/coolsnowwolf/lede/pull/5362

目前的方案和DDNS检测脚本冲突。导致一直错误重试。

**Comment by BGzErol** [comment]
这个好，希望能加上，毕竟现在v6的国内路由也好了起来，B站这些的cdn也支持v6了

**Comment by cabbyjing** [comment]
加一

**Comment by cielpy** [comment]
同样有遇到国外的 IPv6 巨慢的情况，目前使用 SmartDNS 解决了，SmartDNS 可以选择性的屏蔽域名的 AAAA 记录，还不可以批量屏蔽，不过 SmartDNS 还有一个双栈优选功能，能在优选后胜出的 IPv6 地址通常速度还可以

**Comment by xiaorouji** [comment]
有人测试过可用吗
