### ISSUE TITLE
关于DDNS域名解析的一些问题

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-passwall#713]
某一些机场节点的解析地址为域名
而且是动态的DDNS经常切换IP，每当切换IP时passwall都会失效需要重新保存应用
不知道可否增加定时解析域名刷新功能？

另外我看到“自动切换”界面是可以把主节点和备用节点设置成同一个，
不知道这样设置当主和备用节点为同一个时，是否DDNS解析IP刷新时会自动重新解析并连接？

**Comment by xiaorouji** [comment]
另外我看到“自动切换”界面是可以把主节点和备用节点设置成同一个
是的，应该可以
