### ISSUE TITLE
trojan-go无法透明代理

### ISSUE THREAD

**Issue by kxjhcmc** [xiaorouji/openwrt-passwall#736]
配置应该没问题，因为socks能正常使用

**Comment by kxjhcmc** [comment]
使用的是Trojan-Go+Websocket模式。

**Comment by kxjhcmc** [comment]
root@OpenWrt:~# trojan-go -config /var/etc/passwall/TCP_1.json
[INFO]  2020/10/15 01:59:43 trojan-go 0.8.2 initializing
[INFO]  2020/10/15 01:59:43 tls fingerprint firefox applied
[INFO]  2020/10/15 01:59:43 cert is unspecified, using default ca list
[FATAL] 2020/10/15 01:59:43 github.com/p4gefau1t/trojan-go/proxy.(*Option).Handle:option.go:42 tproxy failed to listen tcp | listen tcp 0.0.0.0:1041: bind: address already in use

**Comment by kxjhcmc** [comment]
配置文件应该没问题，最后那个报错应该是已经在运行，使用了1041这个端口，但是透明代理不行。

**Comment by kxjhcmc** [comment]
一下是psw表的内容，看不懂，大神帮忙分析下
Chain PSW_OUTPUT (1 references)
target     prot opt source               destination         
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set laniplist dst
RETURN     tcp  --  0.0.0.0/0            104.26.4.134         /* '网址:443' */ tcp dpt:443
RETURN     tcp  --  0.0.0.0/0            172.67.70.29         /* '网址:443' */ tcp dpt:443
RETURN     tcp  --  0.0.0.0/0            104.26.5.134         /* '网址:443' */ tcp dpt:443
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set vpsiplist dst
RETURN     all  --  0.0.0.0/0            0.0.0.0/0            match-set whitelist dst
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22,25,53,143,465,587,993,995,80,443 match-set shuntlist dst redir ports 1041
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22,25,53,143,465,587,993,995,80,443 match-set blacklist dst redir ports 1041
REDIRECT   tcp  --  0.0.0.0/0            0.0.0.0/0            multiport dports 22,25,53,143,465,587,993,995,80,443 match-set gfwlist dst redir ports 1041

**Comment by kxjhcmc** [comment]
应该是trojan-go透明代理默认走IPV4导致的，不知道怎么解决

**Comment by xiaorouji** [comment]
可以的话提供一下节点（发我的邮箱），我有空再测试，最近几个月或许没什么空

**Comment by kxjhcmc** [comment]
情况是这样，服务器是纯IPV6的服务器才会出现这种情况，后期用了一台既有IPV4又有IPV6的VPS测试，发现透明代理出去默认走的IPv4地址，v2ray透明代理出去默认走了ipv6地址，或许就是这个差异导致了纯ipv6服务器无法透明代理

**Comment by kxjhcmc** [comment]
> 可以的话提供一下节点（发我的邮箱），我有空再测试，最近几个月或许没什么空

不知道你的邮箱地址啊？

**Comment by xiaorouji** [comment]
没有ipv6环境，无法测试，抱歉
