### ISSUE TITLE
Passwall server ssr服务端无法使用加密'none'+协议 'auth_chain_a'的模式

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-passwall#748]
这个问题我之前在另一个关于socks服务端的issue里提到过 #682 
以下测试均尝试使用手机ssr内网进行连接，使用ssr客户端的连接测试
实际情况我直接使用ssr-server二进制文件根据以下passwall生成的config进行测试

```
{
  "protocol": "auth_chain_a",
  "server_port": 1415,
  "password": "password",
  "timeout": 300,
  "obfs": "plain",
  "method": "none",
  "fast_open": false,
  "server": [
    "[::0]",
    "0.0.0.0"
  ]
}
```
得到了如下的运行日志

![Snipaste_2020-10-22_18-02-17](https://user-images.githubusercontent.com/44677306/96856698-c94c5080-1490-11eb-9ecc-5a331837f087.png)

很明显ssr-server的确不支持 加密`'none'`，并且会自动将其转换为加密`'rc4-md5'`，并且在`'rc4-md5'`加密下`'auth_chain_a'`协议也无法加载
![Snipaste_2020-10-22_18-01-09](https://user-images.githubusercontent.com/44677306/96856854-f436a480-1490-11eb-9cde-32463f458f57.png)

之后我尝试使用加密`'rc4-md5'`切换其他协议，也不行
![Snipaste_2020-10-22_18-11-05](https://user-images.githubusercontent.com/44677306/96857790-fea56e00-1491-11eb-8ba9-1dd6c2cac210.png)

发现似乎只有协议`'origin'`，加密非`'none'`的情况下ssr-server才能正常使用，手机客户端的连通测试正常
![Snipaste_2020-10-22_17-59-57](https://user-images.githubusercontent.com/44677306/96857138-395ad680-1491-11eb-8199-20479da6fe6d.png)

**Comment by xiaorouji** [comment]
似乎是的
