### ISSUE TITLE
It  lost tls configuration  when I  try to import  trojan-go  share link 导入trojan-go分享链接时会丢失tls设置

### ISSUE THREAD

**Issue by vagrantflyway** [xiaorouji/openwrt-passwall#769]
I  tried  to import a standard  trojan-go share link,as the  image shown ,the tls configuration  was lost .
我尝试导入一个trojan-go的标准的分享链接，如图所示，它的tls设置被丢弃了
<a href="https://ibb.co/9rgv2vc"><img src="https://i.ibb.co/W253F3G/2020-11-07-9-24-52.png" alt="2020-11-07-9-24-52" border="0"></a>
Additionally ,protocol such as trojan ,trojan-go and vless use  and in most occasion only use tls for safety,should only be permitted using  tls(or xtls) by default for safety and to avoid configuration  mistakes .
thanks very much. 
另外，类似trojan，trojan-go和vless的大多数情况仅使用tls来保证安全的协议应当默认仅仅允许选择tls（或xtls）来防呆。
非常感谢作者。🙏

**Comment by xiaorouji** [comment]
BUG，过段时间抽空再修复下

**Comment by xiaorouji** [comment]
尝试最新源码
