### ISSUE TITLE
trojan-go校验和错误

### ISSUE THREAD

**Issue by Dimitri2020007** [xiaorouji/openwrt-passwall#772]
编译平台x86-64
分支19.07

以下是错误日志：

Finding targets
verifying github.com/shadowsocks/go-shadowsocks2@v0.1.0/go.mod: checksum mismatch
        downloaded: h1:SiGEqep4n+bS5wCZwi6ZgX1MAGRV9erk0zsVOXZ7QvA=
        go.sum:     h1:/0aFGbhK8mtOX4J/6kTJsPLZlEs9KnzKoWCOCvjd7vk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

Building targets
verifying github.com/shadowsocks/go-shadowsocks2@v0.1.0/go.mod: checksum mismatch
        downloaded: h1:SiGEqep4n+bS5wCZwi6ZgX1MAGRV9erk0zsVOXZ7QvA=
        go.sum:     h1:/0aFGbhK8mtOX4J/6kTJsPLZlEs9KnzKoWCOCvjd7vk=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.

For more information, see 'go help module-auth'.

Cleaning module download cache (golang/go#27455)

make[3]: *** [Makefile:92: /home/dimitri/openwrt/build_dir/target-x86_64_musl/trojan-go-0.8.2-d051cf4c8852d708769ca1c4e514306a88da830b/.built] Error 1
make[3]: Leaving directory '/home/dimitri/openwrt/feeds/diy1/package/trojan-go'
time: package/feeds/diy1/trojan-go/compile#3.32#0.85#11.65
make[2]: *** [package/Makefile:113: package/feeds/diy1/trojan-go/compile] Error 2
make[2]: Leaving directory '/home/dimitri/openwrt'
make[1]: *** [package/Makefile:107: /home/dimitri/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/dimitri/openwrt'
make: *** [/home/dimitri/openwrt/include/toplevel.mk:227: world] Error 2

**Comment by qiaohewei** [comment]
同问！！！

**Comment by Dimitri2020007** [comment]
这个和线路没关系，在编译之前已经反复检查过了
