### ISSUE TITLE
package/v2ray/Makefile硬编码GOPROXY

### ISSUE THREAD

**Issue by liaoya** [xiaorouji/openwrt-passwall#773]
`package/v2ray/Makefile`硬编码`GOPROXY`

```Makefile
ifeq ($(CONFIG_V2RAY_COMPRESS_GOPROXY),y)
export GO111MODULE=on
export GOPROXY=https://goproxy.io
#export GOPROXY=https://mirrors.aliyun.com/goproxy/
endif
```

很多程序员会设置自己的`GOPROXY`，该服务器可能是私有服务器，硬编码`GOPROXY`无法使用最佳的`GOPROXY`。

一个可能的实现可以是使用环境变量中的`GOPROXY`，没有在猜测使用`https://goproxy.io`

**Comment by Mattraks** [comment]
你这个问题有些莫名其妙
你可以选择开或者不开
不开就用自己解决代理问题
开了就用预设GOPROXY

**Comment by liaoya** [comment]
首先感谢您能够关注这个issue。

说一下我的编译环境，为了加速编译我会搭建一些cache服务

- <https://github.com/jonasmalacofilho/git-cache-http-server> 缓存github
- <https://www.sonatype.com/>缓存<https://gocenter.io/>

就像您在文件中`#export GOPROXY=https://mirrors.aliyun.com/goproxy/`，可能在某些情况下使用<https://mirrors.aliyun.com/goproxy>是更快的。具体的实现我扎到一个例子<https://stackoverflow.com/questions/24263291/define-a-makefile-variable-using-a-env-variable-or-a-default-value/24264930>

我用如下的`Makefile`进行了测试
```Makefile
ifeq ($(CONFIG_V2RAY_COMPRESS_GOPROXY),y)
export GO111MODULE=on
GOPROXY := $(or ${GOPROXY },${GOPROXY },https://goproxy.io)
export GOPROXY
endif
```

我用如下的代码进行测试

```Makefile
GOPROXY := $(or ${GOPROXY},${GOPROXY},https://goproxy.io)
all :
        @echo ${GOPROXY}
```

正如下面的输出，代码首先使用系统预定义的`GOPROXY`，当然我相信该方法只有一部分人会使用。

```bash
make
http://10.113.69.40/nexus3/repository/gocenter/

unset GOPROXY
make
https://goproxy.io
```

**Comment by Mattraks** [comment]
怎么说呢，自己设置过GOPROXY其实就没有必要开启选择这个选项，因为不开就会使用自己设置好的GOPROXY
也不用担心会覆盖原本GOPROXY配置

**Comment by liaoya** [comment]
非常感谢您的澄清！
