### ISSUE TITLE
咨询一下老哥，请问是否可以对luci-app-ipsec-vpnserver-manyusers的每一个用户从虚拟地址池分配出固定的虚拟IP？

### ISSUE THREAD

**Issue by fox85** [xiaorouji/openwrt-passwall#774]
应用场景为配合 QoS Nftables 版，希望实现为每一个ipsec隧道的账户从虚拟地址池内分配出一个指定的虚拟IP地址，
进而便可以在QOS Nftables里对指定的IP地址进行限速

目前的每一个用户每次分配到的虚拟IP地址都是随机的，无法有针对性的对指定用户进行限速，希望老哥能协助增加此功能，谢谢！

**Comment by fox85** [comment]
Google搜索相关的解决方案，其中有一个可能比较接近的答案，参考这里的mailing list，似乎需要对ikev1_xauth.c打patch

https://lists.libreswan.org/pipermail/swan/2015/001166.html

**Comment by fox85** [comment]
why closed ? any comments plz ?

**Comment by xiaorouji** [comment]
@fox85 请发给Lienol，我不维护这个，谢谢
