### ISSUE TITLE
大佬，能不能将luci-app-trojan-server或passwall中的trojan改成支持同443端口多用户。

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-passwall#776]
用443端口比较安全的，用其他端口，怕被墙封。

**Comment by lllrrr2** [comment]
期待加入naiveproxy 服务器功能。像luci-app-trojan-server和luci-app-trojan-v2ray这样分开。不行的话放在passwall中也没问题，谢谢

**Comment by xiaorouji** [comment]
支持多用户的

**Comment by lllrrr2** [comment]
我试了，支持多用户不同端口，同端口就不支持，多用户同时用443端口会安全点。

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/104023790-1f61a200-51fd-11eb-8c01-1d04f15fe56e.png)
