### ISSUE TITLE
PassWall 的直连/代理名单页面似乎有bug

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#786]
编辑直连/代理名单后点保存并应用会显示“没有待应用的更改”，规则也没有即时生效，但是手动关闭passwall再打开后可以生效。

**Comment by xiaorouji** [comment]
did you use luci 19 ?

**Comment by hathlife** [comment]
> did you use luci 19 ?

LuCI openwrt-19.07 branch git-20.287.57033-3d52019

**Comment by xiaorouji** [comment]
使用luci19好像会这样子，新特征问题吧
使用老的luci是没有问题的，lienol的魔改luci也是可以用的

**Comment by Fegor** [comment]
lienol魔改luci固件哪里可以下载？
