### ISSUE TITLE
variable for Xray path初始化为空值

### ISSUE THREAD

**Issue by RoninYuan-WY** [xiaorouji/openwrt-passwall#789]
发现编译好固件中的passwall中虽然显示了xray path 为/usr/bin/xray，但其变量初始化为空值，因此无法显示版本信息，也无法手动更新，因为无法将xray组件移动到空路径。

解决方法：在组件更新页面，再次保存xray path即可

**Comment by Myoko** [comment]
先保存应用一次就可以了

**Comment by xiaorouji** [comment]
你保存配置升级就会这样，因为旧的配置文件里面没有xray路径，你需要在更新组件页面保存应用一下才行。
