### ISSUE TITLE
xray节点的xtls在启动的时候在日志里报xray找不到

### ISSUE THREAD

**Issue by zcluo** [xiaorouji/openwrt-passwall#790]
xray节点的xtls在启动的时候在日志里报xray找不到，固件里同时又ssrp,,,但是切换其他的节点类型没问题可以启动。

**Comment by xiaorouji** [comment]
你保存配置升级就会这样，因为旧的配置文件里面没有xray路径，你需要在更新组件页面保存应用一下才行。

**Comment by RoninYuan-WY** [comment]
恩，有道理，启动时可以再赋一遍值吗？
