### ISSUE TITLE
v20201128x86_64passwallOpenWRT这个版本的passwall的trojan-plus不能用

### ISSUE THREAD

**Issue by cc9897** [xiaorouji/openwrt-passwall#791]
v20201128x86_64passwallOpenWRT这个版本的passwall的trojan-plus不能用，passwall页面的google和github测试，均失败
![image](https://user-images.githubusercontent.com/73336230/100596645-d6712080-3315-11eb-82d9-2e9bd5f20052.png)

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/792
