### ISSUE TITLE
最新版passwall 3.9-76 服务器端无法使用xray及v2ray

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#793]
经过多次试验，最新版的passwall在服务器端无法使用v2ray和xray，我尝试了xtls tls+ws，tcp等，都不成，应用后显示大红叉。上一个版本的时候是可以正常用的。xray和v2ray版本4.32.1和4.33都无法创建服务端。请大佬看一下是不是哪里有问题，谢谢。![image](https://user-images.githubusercontent.com/75249507/100622996-82d5f580-335c-11eb-9fc3-5047507aac70.jpeg)

**Comment by xiaorouji** [comment]
Fix in https://github.com/xiaorouji/openwrt-passwall/commit/39724d4aea40dedf2f04ff99afbbf6b30c21cee9

**Comment by HeiSeven** [comment]
我是开启了，但是手机ssr设置好连接无网络，无法回家
