### ISSUE TITLE
haproxy-2.2.4 编译通不过

### ISSUE THREAD

**Issue by gswangmd-gssi** [xiaorouji/openwrt-passwall#795]
X86-64

**Comment by gswangmd-gssi** [comment]
make[3]: Leaving directory '/home/gswangmd/lede/package/utils/lua5.3'
time: package/utils/lua5.3/compile#0.24#0.08#0.29
make[3]: Entering directory '/home/gswangmd/lede/feeds/packages/net/haproxy'
touch /home/gswangmd/lede/build_dir/target-x86_64_musl/haproxy-ssl/haproxy-2.2.4/.prepared_c5460ac0d7a45c205cd9f53b35a26d58_6664517399ebbbc92a37c5bb081b5c53_check
. /home/gswangmd/lede/include/shell.sh; gzip -dc /home/gswangmd/lede/dl/haproxy-2.2.4.tar.gz | tar -C /home/gswangmd/lede/build_dir/target-x86_64_musl/haproxy-ssl/haproxy-2.2.4/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /home/gswangmd/lede/build_dir/target-x86_64_musl/haproxy-ssl/haproxy-2.2.4

Applying ./patches/000-OPENWRT-BUILD-make-dladdr1-depend-on-glibc-version-and-not-__USE_GNU.patch using plaintext: 
can't find file to patch at input line 15
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|commit 62af9c83f9ed2b25e0061798e29e3cccfce5fbdc
|Author: Willy Tarreau <w@1wt.eu>
|Date:   Tue Mar 10 07:51:48 2020 +0100
|
|    BUILD: make dladdr1 depend on glibc version and not __USE_GNU
|    
|    Technically speaking the call was implemented in glibc 2.3 so we must
|    rely on this and not on __USE_GNU which is an internal define of glibc
|    to track use of GNU_SOURCE.
|
|diff --git a/src/standard.c b/src/standard.c
|index e0ea8328e..d16eebfea 100644
|--- a/src/standard.c
|+++ b/src/standard.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Patch failed!  Please fix ./patches/000-OPENWRT-BUILD-make-dladdr1-depend-on-glibc-version-and-not-__USE_GNU.patch!
Makefile:152: recipe for target '/home/gswangmd/lede/build_dir/target-x86_64_musl/haproxy-ssl/haproxy-2.2.4/.prepared_c5460ac0d7a45c205cd9f53b35a26d58_6664517399ebbbc92a37c5bb081b5c53' failed
make[3]: *** [/home/gswangmd/lede/build_dir/target-x86_64_musl/haproxy-ssl/haproxy-2.2.4/.prepared_c5460ac0d7a45c205cd9f53b35a26d58_6664517399ebbbc92a37c5bb081b5c53] Error 1
make[3]: Leaving directory '/home/gswangmd/lede/feeds/packages/net/haproxy'
time: package/feeds/packages/haproxy/ssl/compile#0.26#0.13#0.32
package/Makefile:111: recipe for target 'package/feeds/packages/haproxy/compile' failed
make[2]: *** [package/feeds/packages/haproxy/compile] Error 2
make[2]: Leaving directory '/home/gswangmd/lede'
package/Makefile:107: recipe for target '/home/gswangmd/lede/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/gswangmd/lede/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gswangmd/lede'
/home/gswangmd/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2
gswangmd@gssiwmd_server:~/lede$

**Comment by hcym** [comment]
不可能啊，今天晚上还编译的，出错基本是go程序，原因也是代理问题

**Comment by martin-xj** [comment]
同样的问题，无法编译通过。

**Comment by xiaorouji** [comment]
你发错地方了。

**Comment by xsmzhzy** [comment]
反复编译了3次，也是报这样的错误，该怎么解决啊？

**Comment by hcym** [comment]
大雕的库吧？我是用官方master没问题，大雕的可能是冲突，不要选择luci的haproxy应该可以，乱七八糟的插件互相冲突容易引起过敏
