### ISSUE TITLE
Node timeout

### ISSUE THREAD

**Issue by lexin8** [xiaorouji/openwrt-passwall#796]
passwall添加订阅后更新规则默认配置状态，然后开启节点节点列表就超时，可以访问外网（偶尔异常无法访问）
![2](https://user-images.githubusercontent.com/61616502/100959760-f2fd9a80-3559-11eb-8e0a-a0728eb98a86.jpg)
![1](https://user-images.githubusercontent.com/61616502/100959758-ef6a1380-3559-11eb-97db-03349a2d84e1.jpg)
![3](https://user-images.githubusercontent.com/61616502/100965708-378f3300-3566-11eb-88e1-dbff05936536.jpg)
![4](https://user-images.githubusercontent.com/61616502/100965712-3b22ba00-3566-11eb-85ea-a4244c5648d9.jpg)

SSR就没这问题！ https://github.com/Lienol/openwrt 19.07 源码

**Comment by xiaorouji** [comment]
把ajax请求超时时间改大一点试试
