### ISSUE TITLE
x86_64 Passwall在nginx下无法启动

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-passwall#798]
版本信息
* passwall version : 3.9-76
* openwrt version : Lean R20.10.20 
* nginx version : nginx/1.19.0 (x86_64-pc-linux-gnu)

复现
1. 进入passwall随意设置，点击启动
2. 出现能够正常启动dns服务，但无法启动tcp、udp服务的情况
3. 使用`ps | grep passwall`也只能看到dns的服务，看不到tcp、udp的服务
4. 可以使用`service passwall restart`启动

当把Nginx换为uhttpd一切正常

**Comment by xiaorouji** [comment]
非passwall问题，你应该问固件源码反馈
