### ISSUE TITLE
不能获取V2ray和Xray版本

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#799]
再组件更新处不能获取已安装的版本，分析原因为程序路径错误，需要指定到/usr/bin/xray/xray或者/usr/bin/v2ray/v2ray

**Comment by jdnt** [comment]
感谢分享，我刚编译openwrt并复位过passwall，发现xray被移到/usr/bin下面了，v2ray倒是还有个文件夹。解决方式和楼主一样。

**Comment by tianiue** [comment]
迭代还是需要修复这个问题，每次都改也不好

**Comment by xiaorouji** [comment]
感觉你们是因为用了lean的源码编译的，lean那边还没合并 @Mattraks 提交的xray和v2ray的PR

**Comment by WYC-2020** [comment]
@xiaorouji ok收到

**Comment by jelly0925** [comment]
辛苦了。

**Comment by yzq124757** [comment]
v2ray显示更新成功，可是面板上又沒有显示版本，还是空的
