### ISSUE TITLE
关于 直连/代理名单管理 的BUG！

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall#804]
如果把要代理的域名加到代理列表可以走代理生效，如果加到代理列表2和代理列表3，这里加进的域名不走代理，不生效！希望可以修复，谢谢！

**Comment by monokoo** [comment]
这个代理列表2/3 是对应tcp2 tcp3节点的，文字提示上不太友好

**Comment by snakwu** [comment]
> 这个代理列表2/3 是对应tcp2 tcp3节点的，文字提示上不太友好

原来是这样，我就说，好的，谢谢！
