### ISSUE TITLE
Bug Report:添加节点未保存节点列表会出现空节点

### ISSUE THREAD

**Issue by wi11iamzhao** [xiaorouji/openwrt-passwall#807]
版本:不知道在哪看版本号...24个小时前编译Lienol固件时自带的
路由器:X86-64软路由，运行于ESXI7虚拟机
路由器系统:OpenWrt 19.07-SNAPSHOT / LuCI 17.01 Lienol (git-78679eb)
故障描述:在passwall->节点列表页面点击添加按钮，未填写任何信息直接放弃（直接退出页面或返回概况皆可)会导致节点列表中出现一个空的节点。
似乎在点击添加的时候一个空的节点已经被加入了

**Comment by xiaorouji** [comment]
是这样的

**Comment by wi11iamzhao** [comment]
> 是这样的

这不是bug么……

**Comment by xiaorouji** [comment]
不是
