### ISSUE TITLE
点<编辑当前节点>找不到页面。版本4-1

### ISSUE THREAD

**Issue by weweyes** [xiaorouji/openwrt-passwall#810]
![1](https://user-images.githubusercontent.com/59646715/101272397-be424b00-37c6-11eb-9234-4822b995788b.jpg)
<img width="605" alt="2" src="https://user-images.githubusercontent.com/59646715/101272400-c4382c00-37c6-11eb-874c-3fd230f794b8.png">

**Comment by xiaorouji** [comment]
fix.
