### ISSUE TITLE
备份配置时，直连列表没有被保存

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#812]
不知道是passwall这边的问题还是openwrt那边的问题,备份配置的时候，直连列表文件：/usr/share/passwall/rules/direct_ip 和/usr/share/passwall/rules/direct_host没有备份在配置文件中，代理列表文件倒是保存下来了。

**Comment by Portan** [comment]
可以自己把这个路径加到备份配置里去吧，
系统--备份/升级--配置

**Comment by ddnsoft** [comment]
> 可以自己把这个路径加到备份配置里去吧，
> 
> 系统--备份/升级--配置

为啥我打开配置是只读的呢 无法添加呀
