### ISSUE TITLE
passwall_server中转到节点时出错

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#813]
大佬 请看一下 passwall连接vps使用xtls-rprx-splice，passwall_server使用xtls-rprx-direct，并中转到上述节点，点击应用保存后显示正常。但当使用手机客户端连接到这个passwall_server节点后，使用状态变成红叉。如果passwall连接vps使用xtls-rprx-direct模式就一切正常。

**Comment by xiaorouji** [comment]
看起来应该是xray出异常导致进程挂掉了，最好看下xray运行日志

**Comment by ddnsoft** [comment]
不知道运行日志在哪看呀

**Comment by xiaorouji** [comment]
那就更新最新源码，界面化了，挂了的时候就点日志查看

**Comment by ddnsoft** [comment]
已经是最新源码，查看了图形化的系统日志、内核日志、passwall日志、passwall_server日志，均不见错误提示，但问题依旧。ssh到router，用find命令也查不到xray的相关日志

**Comment by xiaorouji** [comment]
你不会用....
是服务端用户列表里面的日志...........

**Comment by ddnsoft** [comment]
> 你不会用....
> 是服务端用户列表里面的日志...........

Xray 1.1.2 (OpenWrt) Custom (go1.15.5 linux/amd64)
A unified platform for anti-censorship.
2020/12/08 17:34:54 [Info] main/jsonem: Reading config: /var/etc/passwall_server/1963ef177637408295aff0d0abb707bc.json
panic: XTLS Splice: not TCP inbound

goroutine 30 [running]:
github.com/xtls/xray-core/proxy/vless/encoding.ReadV.func1(0xc0000100b8, 0x1010a40, 0xc00007e7b0, 0x0, 0x0, 0x100ebc0, 0xc0000100c8, 0xc0001bde08, 0xffae80, 0xc00007ec00, ...)
github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:208 +0x734
github.com/xtls/xray-core/proxy/vless/encoding.ReadV(0xffaa60, 0xc000282160, 0xffbd60, 0xc000010088, 0xffae80, 0xc00007ec00, 0xc0000100b8, 0x100ebc0, 0xc0000100c8, 0x0, ...)
github.com/xtls/xray-core/proxy/vless/encoding/encoding.go:234 +0xcf
github.com/xtls/xray-core/proxy/vless/outbound.(*Handler).Process.func3(0x0, 0x0)
github.com/xtls/xray-core/proxy/vless/outbound/outbound.go:227 +0x3de
github.com/xtls/xray-core/common/task.OnSuccess.func1(0xc0000a63b4, 0x0)
github.com/xtls/xray-core/common/task/task.go:12 +0x2f
github.com/xtls/xray-core/common/task.Run.func1(0xc0000100d8, 0xc00007a960, 0xc000276760)
github.com/xtls/xray-core/common/task/task.go:28 +0x2b
created by github.com/xtls/xray-core/common/task.Run
github.com/xtls/xray-core/common/task/task.go:27 +0xdc

**Comment by xiaorouji** [comment]
panic: XTLS Splice: not TCP inbound.
把用户日志等级调到debug，再复现一下，看看详细的日志
然后将这个日志发给xray那边看看

**Comment by xiaorouji** [comment]
如果那边要求带上配置文件的话
cat /var/etc/passwall_server/1963ef177637408295aff0d0abb707bc.json

**Comment by ddnsoft** [comment]
> panic: XTLS Splice: not TCP inbound.
> 
> 把用户日志等级调到debug，再复现一下，看看详细的日志
> 
> 然后将这个日志发给xray那边看看

请问这个怎么调到debug等级

**Comment by xiaorouji** [comment]
> > panic: XTLS Splice: not TCP inbound.
> > 把用户日志等级调到debug，再复现一下，看看详细的日志
> > 然后将这个日志发给xray那边看看
> 
> 请问这个怎么调到debug等级

就配置用户里面啊

**Comment by ddnsoft** [comment]
> > > panic: XTLS Splice: not TCP inbound.
> 
> > > 把用户日志等级调到debug，再复现一下，看看详细的日志
> 
> > > 然后将这个日志发给xray那边看看
> 
> > 
> 
> > 请问这个怎么调到debug等级
> 
> 
> 
> 就配置用户里面啊

找到了 不过我现在就是调试等级的日志 调试就是debug吧

**Comment by xiaorouji** [comment]
请将日志和配置文件发给Xray那边。
这个我也不知道是BUG还是内核不支持

**Comment by ddnsoft** [comment]
> 请将日志和配置文件发给Xray那边。
> 
> 这个我也不知道是BUG还是内核不支持

好的 多谢
