### ISSUE TITLE
能否增加像clash那样的自动连接延时最短节点的功能？

### ISSUE THREAD

**Issue by Warden630** [xiaorouji/openwrt-passwall#815]
如题，每隔一会测速一下各个节点，选择延时最短的节点连接。
最近GCP 香港比较抽风，平时都挺好，ping只有40左右，时不时的突然ping值会变到一两百，而且丢包严重。因此我放了个备用节点。现有的自动切换功能是在主节点连接不上时候才会切换，但我这个情况主节点网络恶化却还能连上，所以大部分时候他也不切换。看能否增加自动测速，自动切换功能呢

**Comment by jh0072110** [comment]
老哥我认为你的这个建议不可取，不停的跳节点对于很多场景来说都是毁灭性打击（比方说netflix），手动换一换吧…

**Comment by lllrrr2** [comment]
我觉得可以，设置时段使用哪个节点。这样会更好。

**Comment by AU-Linsanity** [comment]
> 老哥我认为你的这个建议不可取，不停的跳节点对于很多场景来说都是毁灭性打击（比方说netflix），手动换一换吧…
增加可选项 不想用可以不选
