### ISSUE TITLE
开启chinadns-ng后，国内国外都无法连接

### ISSUE THREAD

**Issue by lbsnake** [xiaorouji/openwrt-passwall#820]
12月10号早上最新源码编译，开启chinadns-ng选项后，无论选择哪种DNS方案都不通。关闭chinadns-ng后，一切正常。

**Comment by xiaorouji** [comment]
哪个方案能用用哪个

**Comment by jh0072110** [comment]
这貌似是个bug，在 347aac5 之前都不会复现这个问题，使用chinadns会失败，使用doh也会百分百失败，希望肉鸡大佬能研究研究

**Comment by ddnsoft** [comment]
我也是这个问题，关掉chinadns-ng才能用

**Comment by jh0072110** [comment]
> 这貌似是个bug，在 [347aac5](https://github.com/xiaorouji/openwrt-passwall/commit/347aac56160c647e645a580ab9e247617ebcadbd) 之前都不会复现这个问题，使用chinadns会失败，使用doh也会百分百失败，希望肉鸡大佬能研究研究

BTW.我有重置过插件&固件，问题百分百复现才跟着这位老哥回的issue，辛苦肉鸡大佬了。

**Comment by xiaorouji** [comment]
已修复
