### ISSUE TITLE
最新的源码，passwall_server 只要开启中转到此节点功能，就无法开启这个节点

### ISSUE THREAD

**Issue by ddnsoft** [xiaorouji/openwrt-passwall#821]
最新的源码，passwall_server 只要开启中转到此节点功能，就无法开启这个节点，不开启中转功能就可以启动。采用的Xray的xtls，试过v2ray的vless vmess也是这个问题，只要开启中转节点，就会出错。另外日志也看不了，显示未启用日志，其实是启用了的。请大佬看一下咋回事

**Comment by xiaorouji** [comment]
已修复
