### ISSUE TITLE
编译时同时勾选"include v2ray/xray"报错

### ISSUE THREAD

**Issue by Yofo-me** [xiaorouji/openwrt-passwall#822]
编译时同时勾选"include v2ray/xray"报错

**Comment by xwcoco** [comment]
检查一下设置，看看报错是什么信息，我刚编译完，没问题

**Comment by zhucaidan** [comment]
我也是，提示https://goproxy.io/github.com/google/go-cmp/@v/v0.5.3.mod SSL握手失败

看了下https://goproxy.io站根本打不开，这个网站在V2RAY的makefile里面

**Comment by getkg** [comment]
> 我也是，提示 https://goproxy.io/github.com/google/go-cmp/@v/v0.5.3.mod SSL握手失败
> 
> 看了下 https://goproxy.io 站根本打不开，这个网站在V2RAY的makefile里面

me too
