### ISSUE TITLE
新源码负载均衡启动不了

### ISSUE THREAD

**Issue by assasec** [xiaorouji/openwrt-passwall#824]
新源码负载均衡启动不了

**Comment by hcym** [comment]
是的，退回了，

**Comment by WYC-2020** [comment]
好像还真是4.3好像负载均衡都没法用，能启动起来但是没法用

**Comment by rrrwwwkkk** [comment]
试了确实好像无法使用，单个节点都正常，负载均衡了之后就无法连接了

**Comment by CMJ781** [comment]
负载均衡能启动但是无法正常工作

**Comment by xiaorouji** [comment]
测试没有问题，请问负载的节点类型是什么，是否有tls？

**Comment by YWWei1988** [comment]
SSR,未启用tls，负载能够开启，但是负载节点实际不工作，出不去

**Comment by CMJ781** [comment]
SSR, 未启用 tls，负载能够开启，但是负载节点实际不工作，出不去

**Comment by hcym** [comment]
以前两种节点都可以，tls和普通tcp，这次不知道怎么回事，启动不了。暂时用的老版本

**Comment by hcym** [comment]
今天早上的可以了，怪事，可能和官方master有关
