### ISSUE TITLE
Passwall中的DNS问题

### ISSUE THREAD

**Issue by M33FT** [xiaorouji/openwrt-passwall#826]
抱歉，我必须使用Google翻译此文本。
一周前，我使用P3TERX / Actions-OpenWrt方法完成了Linksys WRT1200v2，Linksys WRT1900ACS，Linksys WRT32X, RaspberryPi3B,RaspberryPi4B（精简版git + xiaorouji / openwrt-passwall）的整个固件。
但是昨天和今天，我重新编译了整个项目，并在设备上重新安装了固件（我将其安装干净）。 我陷入了DNS问题。 因为我一直使用DOH，所以到目前为止没有任何问题。 但是我不知道以前版本中运行的DNS服务现在发生了什么情况。
我看到其他人也有我的问题。
我为您上传了设置的照片。
谢谢。

![DOH](https://user-images.githubusercontent.com/63062740/101900787-4fe5fa00-3bc5-11eb-9a96-e4beb9c04923.jpg)

**Comment by M33FT** [comment]
让我说，我应用了您的最新版本，该版本是4个小时前完成的，并重新编译了ROM，但问题仍然存在。

**Comment by xiaorouji** [comment]
do you use the latest version (4-3) ?

**Comment by M33FT** [comment]
I think I messed up xD
You are right. It is on 4.2, not 4.3.
I will compile again and leave the answer here.

![Passwall](https://user-images.githubusercontent.com/63062740/101909791-3a77cc80-3bd3-11eb-93f3-6a9d41f2280b.jpg)

**Comment by M33FT** [comment]
In version 4-3, everything was fixed.
Thanks bro ;-)

![Passwall_02](https://user-images.githubusercontent.com/63062740/101923010-196ba780-3be4-11eb-9568-335fde7167a2.jpg)
