### ISSUE TITLE
负载均衡 Trojan-go 如果Trojan-go节点设置中打开了Mux，则负载均衡失效，无法打开任何网页

### ISSUE THREAD

**Issue by holywen** [xiaorouji/openwrt-passwall#828]
选择节点配置中，选择 Xray 类型负载均衡，然后选择trojan-go节点。
如果其中一个trojan-go节点配置打开了mux，则xray 的TCP_1.json配置中也会打开mux，导致无法打开任何网页。

**Comment by xiaorouji** [comment]
应该不会，一个节点一个outbound
