### ISSUE TITLE
luci 4-3设置v2ray自定义bin文件路径工作异常

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#829]
平台：newifi d2 OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-20.341.57626-51f55b5
luci界面修改v2ray文件路径到外置u盘上后，能够显示出版本号但是无法正常启动服务；软连接到/usr/bin在恢复默认路径后启动服务v2ray工作正常，但是界面显示红x，取消勾选已启动选项或切换成ssr节点，提交应用后也无法停止；htop显示是直接执行/usr/bin/v2ray而不是/var/etc/passwall/bin/v2ray
![image](https://user-images.githubusercontent.com/19867269/102015261-63e05600-3d95-11eb-80ee-c2d610398a73.png)
![image](https://user-images.githubusercontent.com/19867269/102015345-0b5d8880-3d96-11eb-9861-861b8d2370a6.png)

**Comment by xiaorouji** [comment]
程序路径不能是文件夹目录，
填主程序的绝对路径试试

**Comment by hathlife** [comment]
> 程序路径不能是文件夹目录，
> 填主程序的绝对路径试试

之前填的是`/mnt/sda1/system/usr/bin/v2ray`，然后日志里面提示找不到v2ray bin文件权限是对的

**Comment by xiaorouji** [comment]
已修复

**Comment by hzceo** [comment]
可以给个包来安装吗

**Comment by hzceo** [comment]
> 平台：newifi d2 OpenWrt 19.07.5 r11257-5090152ae3 / LuCI openwrt-19.07 branch git-20.341.57626-51f55b5
> 
> luci界面修改v2ray文件路径到外置u盘上后，能够显示出版本号但是无法正常启动服务；软连接到/usr/bin在恢复默认路径后启动服务v2ray工作正常，但是界面显示红x，取消勾选已启动选项或切换成ssr节点，提交应用后也无法停止；htop显示是直接执行/usr/bin/v2ray而不是/var/etc/passwall/bin/v2ray
> 
> ![image](https://user-images.githubusercontent.com/19867269/102015261-63e05600-3d95-11eb-80ee-c2d610398a73.png)
> 
> ![image](https://user-images.githubusercontent.com/19867269/102015345-0b5d8880-3d96-11eb-9861-861b8d2370a6.png)
> 
> 

可以给个包来安装吗
