### ISSUE TITLE
延迟问题

### ISSUE THREAD

**Issue by tporwx** [xiaorouji/openwrt-passwall#832]
![屏幕截图 2020-12-14 213930](https://user-images.githubusercontent.com/18187690/102088219-96518800-3e55-11eb-84d7-b59500182dbc.png)

最新源码编译，延迟取数好像错了。

**Comment by zxlhhyccc** [comment]
同样问题。。。简直惨不忍睹。。。。

**Comment by Myoko** [comment]
是你自己的问题吧
![QQ截图20201214222753](https://user-images.githubusercontent.com/3013386/102093019-a53b3900-3e5b-11eb-8e1b-19ce255cef1b.jpg)

**Comment by jliveusa** [comment]
![image](https://user-images.githubusercontent.com/42428798/102153914-38538d80-3eb3-11eb-989c-b3d0d8c381c1.png)

**Comment by sbily1988** [comment]
> 是你自己的问题吧
> ![QQ截图20201214222753](https://user-images.githubusercontent.com/3013386/102093019-a53b3900-3e5b-11eb-8e1b-19ce255cef1b.jpg)

你这延迟明显不对吧，百度的延迟怎可能会那么高

**Comment by zxlhhyccc** [comment]
> 是你自己的问题吧
> ![QQ截图20201214222753](https://user-images.githubusercontent.com/3013386/102093019-a53b3900-3e5b-11eb-8e1b-19ce255cef1b.jpg)

又不是个例。。。。

**Comment by tporwx** [comment]
这个情况是最新源码编译才出现的，之前是正常的。
上面几位也是最新源码编译的？

**Comment by zxlhhyccc** [comment]
> 这个情况是最新源码编译才出现的，之前是正常的。
> 上面几位也是最新源码编译的？

我是最新源码编译的。。。。

**Comment by leafsay** [comment]
我编译了直接就开始卡网了，不得已换了另一个

**Comment by lexin8** [comment]
我的速度最快，你们都是渣渣
![2](https://user-images.githubusercontent.com/61616502/102332455-11867b80-3fc7-11eb-9afe-12944205d6fa.jpg)
