### ISSUE TITLE
Passwall里面的trojan-go采用中转模式时sni错误

### ISSUE THREAD

**Issue by GickThomas** [xiaorouji/openwrt-passwall#833]
软件说明：

- 【2020.12.12 #Hyird 编译】
- 【luci-app-passwall_4-3_all.ipk】
- 【编译 (https://github.com/hyird/openwrt-actions/actions)】
- 此版本采用的作者是https://github.com/xiaorouji/openwrt-passwall

采用的模式：

- 客户端和服务端正确搭建trojan-go，采用brook中转机中转。

描述:

- TLS:选中
- 会议Ticket:留空
-  指纹伪造:firefox/disable (两个都试过)
- 域名:服务端域名yyyyyy.cf

服务端报错：

- trojan-go[335929]: [ERROR] 2020/12/14 22:39:02 github.com/p4gefau1t/trojan-go/tunnel/tls.(*Server).acceptLoop.func1:server.go:135 tls handshake failed | sni mismatched: xxxxxxx.tk, expected: yyyyyy.cf

采用xray里面的trojan协议中转， TLS:选中，域名:服务端域名yyyyyy.cf，运行正常。

**Comment by xiaorouji** [comment]
证书有无过期等？试试勾选 允许不安全连接
