### ISSUE TITLE
passwall 是否提供局域网可以访问的 http proxy 或者socks5 proxy 端口？

### ISSUE THREAD

**Issue by ferocknew** [xiaorouji/openwrt-passwall#835]
如题

**Comment by Ljzkirito** [comment]
![image](https://user-images.githubusercontent.com/66788052/102195857-14676a80-3efa-11eb-9d45-9926fbc1612b.png)
这个不是吗？

**Comment by ferocknew** [comment]
感谢回答，麻烦再告知一下，如下菜单内是哪个tab 进去？

![image](https://user-images.githubusercontent.com/2178683/102196328-b9824300-3efa-11eb-836f-af93bfc9a9f8.png)

**Comment by zxlhhyccc** [comment]
> 感谢回答，麻烦再告知一下，如下菜单内是哪个tab 进去？
> 
> ![image](https://user-images.githubusercontent.com/2178683/102196328-b9824300-3efa-11eb-836f-af93bfc9a9f8.png)

在模式里。。。。

**Comment by Ljzkirito** [comment]
> 感谢回答，麻烦再告知一下，如下菜单内是哪个tab 进去？

就在基本设置下面

**Comment by ferocknew** [comment]
> > 感谢回答，麻烦再告知一下，如下菜单内是哪个tab 进去？
> > ![image](https://user-images.githubusercontent.com/2178683/102196328-b9824300-3efa-11eb-836f-af93bfc9a9f8.png)
> 
> 在模式里。。。。

![image](https://user-images.githubusercontent.com/2178683/102282023-eec67980-3f6a-11eb-861c-35eb2275fb4a.png)
![image](https://user-images.githubusercontent.com/2178683/102282065-fd149580-3f6a-11eb-9ca2-5329f5600abc.png)

**Comment by ferocknew** [comment]
> > 感谢回答，麻烦再告知一下，如下菜单内是哪个tab 进去？
> 
> 就在基本设置下面

可能我的版本太旧？的确没有找到

**Comment by xiaorouji** [comment]
你这用的不是最新版本。。又来问不是有点搞笑？...

**Comment by ferocknew** [comment]
> 你这用的不是最新版本。。又来问不是有点搞笑？...

软件界面上并没有展示版本号的地方，这个repositories 也没有release ，如果这样你还用”搞笑“这个词，是不是太玻璃了？
随便吧
