### ISSUE TITLE
链接测试

### ISSUE THREAD

**Issue by jackson-lx** [xiaorouji/openwrt-passwall#836]
![111](https://user-images.githubusercontent.com/61775032/102182160-c432dd00-3ee6-11eb-809b-643427f42aba.jpg)

**Comment by lexin8** [comment]
我的速度最快，你们都是渣渣
![2](https://user-images.githubusercontent.com/61616502/102332455-11867b80-3fc7-11eb-9afe-12944205d6fa.jpg)

**Comment by zxlhhyccc** [comment]
看样子很多人出现延迟问题了，dalao修复一下呗。。。。
