### ISSUE TITLE
能否增加代理链的功能

### ISSUE THREAD

**Issue by EsuRt** [xiaorouji/openwrt-passwall#837]
在Xray/V2ray的分流规则填入geosite:geolocation-!cn后，结合规则的前置代理能够实现部分代理链，但在规则中排除大陆ip比较困难，没有geosite:geolocation-!cn这样类似的写法，能否在主开关处增加一个前置代理的功能？
用途：主要利用机场的线路中转自己服务器的流量，兼顾速度与隐私，很多机场有中转线路，但也会记录用户的访问记录，代理链能够保证不被获取详细的访问记录。

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/107151196-40541900-699c-11eb-9b2f-0abd0e3b0122.png)
这样是否能够满足你的需求？

**Comment by shoushi01** [comment]
> ![image](https://user-images.githubusercontent.com/60100640/107151196-40541900-699c-11eb-9b2f-0abd0e3b0122.png)
> 这样是否能够满足你的需求？

非常感谢。同时有个疑问：如果使用“服务器端”功能，似乎并不能选择这种链式代理。请问有办法解除类似的限制吗？另外，链式代理支持VLESS+TLS或者VLESS+XTLS吗？这方面内容讨论较少

**Comment by xiaorouji** [comment]
@shoushi01  能，思考一下就知道怎样做了。客户端同时开启监听Socks（与TCP节点相同），端口自定义。
新建一个节点，Xray类型的Socks协议填写这个Socks的地址和端口保存，服务端中转到这个新建的Socks节点即可。

**Comment by xiaorouji** [comment]
@shoushi01 支持的，你可以试试就知道了，不行的话，就给被代理的分流节点配置TLS域名

**Comment by shoushi01** [comment]
> @shoushi01 能，思考一下就知道怎样做了。客户端同时开启监听Socks（与TCP节点相同），端口自定义。
> 新建一个节点，Xray类型的Socks协议填写这个Socks的地址和端口保存，服务端中转到这个新建的Socks节点即可。

感谢您的帮助，已解决。XTLS链式代理也已调试好。

**Comment by xiaorouji** [comment]
finish.
