### ISSUE TITLE
首页节点检测的地方检测不到Trojan节点

### ISSUE THREAD

**Issue by ulifuqiang** [xiaorouji/openwrt-passwall#838]
首页节点检测的地方检测不到Trojan节点，我有3个节点，但是首页检测的地方只检测刀2个节点。Trojan节点没检测到。
固件版本 | OpenWrt R20.12.12 Compilde by gd772 / LuCI Master (git-20.343.54716-6fc079f)
-- | --
内核版本 | 5.4.83-flippy-50+o

![Snipaste_2020-12-17_13-21-32](https://user-images.githubusercontent.com/25083314/102447414-e5bcd180-406a-11eb-9dbe-ef2423c4583a.png)
![Snipaste_2020-12-17_13-22-41](https://user-images.githubusercontent.com/25083314/102447465-f5d4b100-406a-11eb-93e6-74df88cdc4ee.png)

**Comment by xiaorouji** [comment]
Fix.
