### ISSUE TITLE
能否增加拦截广告域名的功能

### ISSUE THREAD

**Issue by EsuRt** [xiaorouji/openwrt-passwall#850]
AdGuard Home能拦截广告域名，但只能设置一个dns，在dns分流的情况下，拦截效果较差，能否直接在passwall中添加拦截广告域名的功能，类似在v2ray中用geosite:category-ads-all的规则进行阻断。

**Comment by hcym** [comment]
规则目录有那个AD域名，还不少，就是没看到开关电源键😂

**Comment by xiaorouji** [comment]
使用dnsmasq实现的 adblock 吗？

**Comment by hcym** [comment]
是的，不知道开关，只能用hosts，也够用😹

**Comment by xiaorouji** [comment]
finish.
