### ISSUE TITLE
到处节点配置失败

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#856]
![image](https://user-images.githubusercontent.com/34025388/103195575-8473e880-491d-11eb-81c7-cf4162a8c89e.png)

**Comment by zhicylee** [comment]
试了下 导出配置信息 同样的失败提示

**Comment by zhicylee** [comment]
![2040](https://user-images.githubusercontent.com/63227888/103259275-a0d25c80-49d3-11eb-97e6-748d1393f83d.jpg)
导入配置信息时弹出bug提示，但点击确定后节点可以添加成功

**Comment by xiaorouji** [comment]
是不支持的，PR这个功能的作者没完善

**Comment by xiaorouji** [comment]
最新源码已支持，请测试反馈。
