### ISSUE TITLE
用官方原版openwrt19.07编译报错，请达人指点下

### ISSUE THREAD

**Issue by starambler** [xiaorouji/openwrt-passwall#857]
编译环境：github云编译
官方原版openwrt19.07
多次测试后仍然报错

输出信息：

Finding targets

Building targets

/workdir/openwrt/staging_dir/host/bin/upx --lzma --best /workdir/openwrt/build_dir/target-x86_64_musl/trojan-go-0.8.2-d051cf4c8852d708769ca1c4e514306a88da830b/.go_work/build/bin/trojan-go
bash: /workdir/openwrt/staging_dir/host/bin/upx: No such file or directory
make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/trojan-go-0.8.2-d051cf4c8852d708769ca1c4e514306a88da830b/.built] Error 127
Makefile:87: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/trojan-go-0.8.2-d051cf4c8852d708769ca1c4e514306a88da830b/.built' failed
make[3]: Leaving directory '/workdir/openwrt/package/passwall/trojan-go'
time: package/passwall/trojan-go/compile#2.79#0.90#3.51
package/Makefile:111: recipe for target 'package/passwall/trojan-go/compile' failed
make[2]: *** [package/passwall/trojan-go/compile] Error 2
make[2]: Leaving directory '/workdir/openwrt'
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
package/Makefile:107: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: Leaving directory '/workdir/openwrt'
make: *** [world] Error 2
/workdir/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
Error: Process completed with exit code 2.

**Comment by xiaorouji** [comment]
golang版本太低
建议使用lienol lean ctcgfw的源码编译，用官源出问题的自己排错。。
