### ISSUE TITLE
解锁过奈非的节点在clash上可以解锁，在passwall上却无效

### ISSUE THREAD

**Issue by dzhl** [xiaorouji/openwrt-passwall#861]
节点采用了商家提供的解锁服务，我在节点机上使用dnsmaps进行了分流，节点部署在clash，奈非app上显示已经解锁，可以播放非自制剧，我把节点部署在passwall上，奈非app上却只能加载自制剧，就跟没解锁之前完全一样，也就是说在passwall上节点的解锁是无效的，请问我该怎么解决呢，我听有的网友说在passwall是可以的，难道是我哪里设置错误吗？
@xiaorouji ，大佬，需要的话，我可以提供节点供测试

**Comment by xiaorouji** [comment]
DNS
