### ISSUE TITLE
路由规则提议

### ISSUE THREAD

**Issue by doegeenon** [xiaorouji/openwrt-passwall#862]
作者大佬会考虑后续加入类似图片这种路由规则吗？因为现有的我发现分流里只能设置黑名单不能设置白名单（域名），然后后面的优先级最高的直连代理里只能填写域名例如baidu.com或者IP之类的，无法填写geosite:cn、geoip:cn这种规则；以及只有直连和代理，没有阻断，不能设置阻断广告域名（geosite:category-ads-all），然后顺带添加一个更新geosite.dat和geoip.dat的按键，就一个小提议吧，因为我是想设置类似白名单和广告过滤，其余一律走代理这种设置，但好像实现不了，希望大佬考虑，也非常感谢大佬的付出
![微信图片_20201231114250](https://user-images.githubusercontent.com/35756327/103393385-5bda3180-4b5d-11eb-9d7f-ee8fb8b78c2d.png)

**Comment by xiaorouji** [comment]
Future will consider.

**Comment by doegeenon** [comment]
十分感谢为我们用户带来这么好用的工具

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/107411268-4dfad180-6b49-11eb-85a1-eb1fce2fcc27.png)
![image](https://user-images.githubusercontent.com/60100640/107411291-54894900-6b49-11eb-950e-3c1ce5059b7b.png)
已经可以愉快的玩耍了

**Comment by doegeenon** [comment]
> ![image](https://user-images.githubusercontent.com/60100640/107411268-4dfad180-6b49-11eb-85a1-eb1fce2fcc27.png)
> ![image](https://user-images.githubusercontent.com/60100640/107411291-54894900-6b49-11eb-950e-3c1ce5059b7b.png)
> 已经可以愉快的玩耍了

感动，永远滴神，马上编译一波

**Comment by doegeenon** [comment]
> ![image](https://user-images.githubusercontent.com/60100640/107411268-4dfad180-6b49-11eb-85a1-eb1fce2fcc27.png)
> ![image](https://user-images.githubusercontent.com/60100640/107411291-54894900-6b49-11eb-950e-3c1ce5059b7b.png)
> 已经可以愉快的玩耍了

可以说是非常舒服了，使用起来没有问题，太感谢了；我看源码好像geo database用的是v2官方的，我这边平时用的是增强版：https://github.com/Loyalsoldier/v2ray-rules-dat，如果大哥可以加个自定义填写库的功能就更nice了，当然现在已经很赞很满足了

**Comment by xiaorouji** [comment]
年后会更新。

**Comment by xiaorouji** [comment]
已经有人PR了，已经合并。

**Comment by doegeenon** [comment]
> 已经有人PR了，已经合并。

用上了，无敌，感谢大佬，真正意义上完全替代设备上的客户端了
