### ISSUE TITLE
大佬，passwall直连名单设置好像没有作用……

### ISSUE THREAD

**Issue by ywyha** [xiaorouji/openwrt-passwall#863]
反复折腾尝试关闭再次开启，依然没有效果……
比如steampowered.com
或者imdb.com

**Comment by garypang13** [comment]
https://github.com/xiaorouji/openwrt-passwall/pull/864/files

**Comment by ywyha** [comment]
> https://github.com/xiaorouji/openwrt-passwall/pull/864/files

谢谢garypang13大佬，这是修复补丁吗，没想到刚纠结的问题，这么快就有了解决办法，怎么觉得大佬是不是换头像了 ，同时感谢大佬的固件。

**Comment by assasec** [comment]
> https://github.com/xiaorouji/openwrt-passwall/pull/864/files

编译了一下 试了试直连列表还是无效  在负载均衡模式下

**Comment by ywyha** [comment]
> > https://github.com/xiaorouji/openwrt-passwall/pull/864/files
> 
> 编译了一下 试了试直连列表还是无效 在负载均衡模式下

我也试了下最新的，直连名单也是依然不生效，用的是LEDE X86 64，trajon-go，未开启负载均衡……

**Comment by ywyha** [comment]
> > https://github.com/xiaorouji/openwrt-passwall/pull/864/files
> 
> 编译了一下 试了试直连列表还是无效 在负载均衡模式下

我也试了下最新版的passwall，依然直连名单无效，用的是大屌的LEDE x86 64

**Comment by ywyha** [comment]
又试了下昨天的passwall4-5版本，直连域名名单依然无效,用的是LEDE x86 64 trajon-go GFW模式

**Comment by ywyha** [comment]
> > > https://github.com/xiaorouji/openwrt-passwall/pull/864/files
> > 
> > 
> > 编译了一下 试了试直连列表还是无效 在负载均衡模式下
> 
> 我也试了下最新版的passwall，依然直连名单无效，用的是大屌的LEDE x86 64

不开启负载均衡也无效……

**Comment by xiaorouji** [comment]
清空ipset再试试

**Comment by ywyha** [comment]
> 清空ipset再试试
大佬，我先去试试，我现在用的是1月3日版本的passwall，当时编译的固件是不保存配置全新安装的，如果不行，我再去试试最新的passwall，到时候再来反馈。

**Comment by xiaorouji** [comment]
修复了

**Comment by ywyha** [comment]
> 修复了

大佬，还是不行啊，如imdb我已经加入了直连名单内，但是现在依然访问美国，如果关闭passwall就会访问日本，相同环境下其他设置没有任何变更的情况我尝试切换同路由下的SSR+插件，立马正常，而且从smartdns中能看出端倪，如果用passwall，在IMDB.com加入直连名单的情况下依然会返回3个IP，如果切换SSR，就会正常的返回1个IP，并且访问的是日本的节点 ，换passwall就变成了美国IP，而且是跟节点IP是一个城市的网站地址。关了passwall或者切换成ssr+就正常…………

**Comment by assasec** [comment]
> > 修复了
> 
> 大佬，还是不行啊，如imdb我已经加入了直连名单内，但是现在依然访问美国，如果关闭passwall就会访问日本，相同环境下其他设置没有任何变更的情况我尝试切换同路由下的SSR+插件，立马正常，而且从smartdns中能看出端倪，如果用passwall，在IMDB.com加入直连名单的情况下依然会返回3个IP，如果切换SSR，就会正常的返回1个IP，并且访问的是日本的节点 ，换passwall就变成了美国IP，而且是跟节点IP是一个城市的网站地址。关了passwall或者切换成ssr+就正常…………

一样的情况 直连名单依然无效

**Comment by ywyha** [comment]
> > > 修复了
> > 
> > 
> > 大佬，还是不行啊，如imdb我已经加入了直连名单内，但是现在依然访问美国，如果关闭passwall就会访问日本，相同环境下其他设置没有任何变更的情况我尝试切换同路由下的SSR+插件，立马正常，而且从smartdns中能看出端倪，如果用passwall，在IMDB.com加入直连名单的情况下依然会返回3个IP，如果切换SSR，就会正常的返回1个IP，并且访问的是日本的节点 ，换passwall就变成了美国IP，而且是跟节点IP是一个城市的网站地址。关了passwall或者切换成ssr+就正常…………
> 
> 一样的情况 直连名单依然无效

对啊，这个问题困扰依旧，访问一些网站无法直连会导致出现很多问题，真希望大佬彻底修复这个问题，还有我记得头一阶段使用 chongshengB大佬的pandavan固件内的ssr插件也是存在直连名单失效的问题（记不清是直连名单失效还是代理名单失效了，反正有一个失效的……），我不知道是不是相同的因素导致的类似问题。也希望其他因直连名单失效导致困扰的兄弟们也来反馈下，让大佬看到……

**Comment by xiaorouji** [comment]
日志发一下
清空IPSET试过没？

**Comment by xiaorouji** [comment]
命令行输入看看是什么
cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf

**Comment by assasec** [comment]
> 命令行输入看看是什么
> cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf

 can't open '/tmp/etc/dnsmasq-passwall.d/00-direct_host.conf': No such file or directory

**Comment by ywyha** [comment]
> 命令行输入看看是什么
> cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf

~# cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf
cat: /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf: No such file or directory

大佬，点那个清空IPSET试过很多次了，并且最近几版的passwall我都是重新编译固件，重刷，并且每次刷完都恢复出厂设置一次，我也是最近不到一个月才开始使用passwall的……现在用的是LEDE X86 64 trajon-go GFW模式，   只要开启passwall，访问设置直联的steam IMDB等网站立马变成跟我节点一样城市的网站IP……并且用nslookup查看也是返回3个IP，用smartdns应该只返回一个IP的，关了passwall，或者换ssr+直连名单就正常

**Comment by xiaorouji** [comment]
> > 命令行输入看看是什么
> > cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf
> 
> can't open '/tmp/etc/dnsmasq-passwall.d/00-direct_host.conf': No such file or directory

你这是没开吧

**Comment by ywyha** [comment]
> > > 命令行输入看看是什么
> > > cat /tmp/etc/dnsmasq-passwall.d/00-direct_host.conf
> > 
> > 
> > can't open '/tmp/etc/dnsmasq-passwall.d/00-direct_host.conf': No such file or directory
> 
> 你这是没开吧

![image](https://user-images.githubusercontent.com/38624632/104017309-da387280-51f2-11eb-8f92-3d55528d2547.png)

**Comment by xiaorouji** [comment]
开着的状态下输入：
ls /tmp/etc/dnsmasq-passwall.d/

**Comment by ywyha** [comment]
> 开着的状态下输入：
> ls /tmp/etc/dnsmasq-passwall.d/

抱歉啊大佬，刚才着急进错主机了…………我又重新输入了命令
![image](https://user-images.githubusercontent.com/38624632/104018988-b32f7000-51f5-11eb-985b-5ef1e95ad8c4.png)

**Comment by xiaorouji** [comment]
你默认DNS是什么？

**Comment by ywyha** [comment]
> 你默认DNS是什么？
如图，smartdns作为上游，用nslookup命令查看，smartdns是生效的，唯独加直连的IMDB域名返回3个IP，关了passwall或者换成SSR插件就返回一个IP
![image](https://user-images.githubusercontent.com/38624632/104019176-0f928f80-51f6-11eb-9032-1b50f8084858.png)
![image](https://user-images.githubusercontent.com/38624632/104019208-1e794200-51f6-11eb-99dc-3937e30d892d.png)
![image](https://user-images.githubusercontent.com/38624632/104019275-38b32000-51f6-11eb-8111-a1df91f5f4ac.png)

**Comment by ywyha** [comment]
我开着passwall访问设置直连的steam和IMDB，访问的这两个网站目标IP指向的都是亚特兰大，我的小鸡节点就在亚特兰大……刚才我又尝试关闭passwall，steam马上变成访问印度，imdb变成访问日本。使用ShadowSocksR Plus+设置直连域名也是正常。
这么多天尝试了很多个版本的passwall， 设置直连名单没有一次能正常直连的……

**Comment by xiaorouji** [comment]
设置搭配有问题，smartdns这样设置会和passwall冲突

**Comment by xiaorouji** [comment]
我不用smartdns，无法解答

**Comment by xiaorouji** [comment]
而且你这个lan我看不懂你为什么这样设置，如果你是pppoe，lan口的网关广播DNS都不用填的。。。

**Comment by ywyha** [comment]
> 而且你这个lan我看不懂你为什么这样设置，如果你是pppoe，lan口的网关广播DNS都不用填的。。。

大佬，那个LAN口设置是编译带的示例我忘记删了……大佬，smartdns对这里还挺好用的…… ，比如访问steam、tmdb API等一些网站，直连的访问速度都要比代理访问速度要快，比如steam如果不用smartdns不用代理直接访问的地址可能跑欧洲去了，如果用的话就会跑香港，延迟100毫秒之内……
如果大佬能让smartdns和passwall不冲突就好了……很喜欢passwall和功能。

大佬，我对技术一丁点都不懂，甚至一个月前都不知道编译是啥，不知道现在的问题是不是跟passwall自带的DNS防污染有关联，

按理说逻辑上设置直连的域名不应该再通过passwall的DNS防污染请求DNS解析，因为这样会通过远程节点请求DNS，这样的话本机就不会访问延迟最短的服务器……所以导致直连域名的名单访问速度变慢。

关于smartdns我看大佬也说过这个问题https://github.com/coolsnowwolf/lede/issues/2551

所以大佬，设置直连的域名可不可以不通过远程节点解析DNS……这样更合理一些，大佬passwall很好用，就差一哆嗦了……

**Comment by WYC-2020** [comment]
@ywyha 自己设置问题，我也是负载均衡也是smart＋psw没遇到你这个问题
$ nslookup steampowered.com
Server:         8.8.8.8
Address:        8.8.8.8#53
Non-authoritative answer:
Name:   steampowered.com
Address: 2.20.27.179
$ nslookup imdb.com
Server:         8.8.8.8
Address:        8.8.8.8#53
Non-authoritative answer:
Name:   imdb.com
Address: 52.94.225.248
$ nslookup imdb.com
Server:         8.8.8.8
Address:        8.8.8.8#53
Non-authoritative answer:
Name:   imdb.com
Address: 52.94.225.248
$ nslookup steampowered.com
Server:         8.8.8.8
Address:        8.8.8.8#53
Non-authoritative answer:
Name:   steampowered.com
Address: 23.195.215.63

**Comment by ywyha** [comment]
> @ywyha 自己设置问题，我也是负载均衡也是smart＋psw没遇到你这个问题
> $ nslookup steampowered.com
> Server: 8.8.8.8
> Address: 8.8.8.8#53
> Non-authoritative answer:
> Name: steampowered.com
> Address: 2.20.27.179
> $ nslookup imdb.com
> Server: 8.8.8.8
> Address: 8.8.8.8#53
> Non-authoritative answer:
> Name: imdb.com
> Address: 52.94.225.248
> $ nslookup imdb.com
> Server: 8.8.8.8
> Address: 8.8.8.8#53
> Non-authoritative answer:
> Name: imdb.com
> Address: 52.94.225.248
> $ nslookup steampowered.com
> Server: 8.8.8.8
> Address: 8.8.8.8#53
> Non-authoritative answer:
> Name: steampowered.com
> Address: 23.195.215.63

兄弟，你这个smartdns是设置的分组？兄弟你这个解析出来的IP明显也不理想啊，比如现在我访问IMDB网站是访问日本的99.84.50.12，访问steam网站解析出的IP是23.53.64.199，延迟基本在100毫秒左右，有时候甚至有时候80毫秒之内，你这个解析出来的几个IP延迟都达到了快300毫秒了，明显很影响访问速度，比如我现在直连访问github，延迟只有120左右，有时候只有70毫秒

**Comment by WYC-2020** [comment]
@ywyha 我这个是有开启代理和没开启代理测试的，我只是说明解析是只会返回一个ip至于理想不理想那是和个人所处网络环境有关系ok，只要解析出来的地址是那个地方的就行懂不

**Comment by ywyha** [comment]
> @ywyha 我这个是有开启代理和没开启代理测试的，我只是说明解析是只会返回一个ip至于理想不理想那是和个人所处网络环境有关系ok，只要解析出来的地址是那个地方的就行懂不

好的，大佬，我知道了，但是，有点跑题了。现在的问题是直连名单失效的问题，smartdns分组设置也许能解决返回多个IP的问题，但是解决不了直连问题，因为分组设置即使能返回一个IP也是速度不理想的IP

**Comment by ywyha** [comment]
passwall的功能真的很有创意，很喜欢，但是到现在为止luci-app-passwall | 4-8版本，我这里直连名单设置后依然是无效的……一旦直连无效，访问一些网站就会被跨区，一旦被强制跨区就无法正常使用……难受……

我不知道这个BUG是不是跟加入直连名单后，设置直连的域名没有排除通过passwall的DNS代理解析导致的……我感觉加入直连的域名依然会通过passwall的防污染功能去解析域名，但是如果真是这样的话，这是不合理的，既然加入直连就应该用系统默认的DNS去解析，而不是通过passwall的远程DNS去解析。

大佬，难受哇@@

**Comment by xiaorouji** [comment]
更新最新源码4-9再试下咯

**Comment by ywyha** [comment]
> 更新最新源码4-9再试下咯

大佬，我很感动！我明天起床后编译后再去试试。我会一直追逐大佬到地老天荒，直到直连名单生效 o(╥﹏╥)o，我一直在被“美国”地区居住，哭晕在厕所。

**Comment by xiaorouji** [comment]
请务必使用passwall内置的dns方案去复现问题，如果是自己搭配的第三方dns导致的问题我也无法解决。

**Comment by ywyha** [comment]
> 请务必使用passwall内置的dns方案去复现问题，如果是自己搭配的第三方dns导致的问题我也无法解决。

大佬，这是我最矛盾的地方，我直连的目的是为了更快的访问目标网站和让目标网站正确识别我的地区。但是我的常用节点在美国，但是我访问的直连的网站没有被墙只是被污染了，使用默认运营商DNS会被解析到美国或者其他很远的地方，而使用smartdns会被解析到台湾、香港、或者日本。所以，使用直连配合smartdns访问速度能达到最快与最稳定。如果不使用smartdns，那么默认会被解析到美国，这样的话即使直连生效，也违背了使用直连的目的-访问速度与正确识别我的地区。

所以大佬，我真是无比抓狂。

大佬，我发现在passwall使用GFW模式运行smartdns后，所有gwf列表的域名解析都会被passwall的DNS“拦截”去强制解析，而非GFW列表中的域名则能正常使用smartdns解析。这样的结果会造成通过TCP节点去解析域名，而TCP的节点解析的结果都是距离TCP最近的解析IP地址，如果TCP节点在月球，那么即使能直连，本机访问月球的速度必然是很慢的……

所以，大佬，这个BUG会不会是因为，域名加入直连名单后，逻辑上没有同时解除这个域名passwall的“DNS”解析拦截造成的？

因为现在貌似所有非GFW中的域名smartdns的解析都不会受到影像，受影响的只有GFW列表。

我真怀疑逻辑上加入直连名单的域名后同时解除passwall的“DNS”拦截解析，这个BUG没准就修复了。

…如果自己的节点在香港等亚洲地区，直不直连真无所谓，但是如果节点在美国等其他地区，直连名单依然使用远程TCP节点解析，那对网站的访问速度影像真的挺大的……



最后祈祷大佬试试smartdns…

**Comment by Fegor** [comment]
刷luci17试试

**Comment by ywyha** [comment]
> 刷luci17试试
我这些天断断续续在刷 包括最新的luci: 4-12，在使用smartdns+trajon-go的情况下直连名单依然没效果，其他模式我没试过。需求直连是因为有些网站必须直连才能正常访问，而smartdns保证直连的防污染，所以smartdns是必备品，真没办法舍弃哎。

**Comment by Fegor** [comment]
> > 刷luci17试试
> > 我这些天断断续续在刷 包括最新的luci: 4-12，在使用smartdns+trajon-go的情况下直连名单依然没效果，其他模式我没试过。需求直连是因为有些网站必须直连才能正常访问，而smartdns保证直连的防污染，所以smartdns是必备品，真没办法舍弃哎。

1. 添加好直连域名，保存生效
2. 重启软路由
3. 然后电脑刷新DNS，命令是ipconfig /flushdns
4. 然后打开chrome的访客模式 再试试。
我弄了下 这样是有效的

**Comment by ywyha** [comment]
> > > 刷luci17试试
> > > 我这些天断断续续在刷 包括最新的luci: 4-12，在使用smartdns+trajon-go的情况下直连名单依然没效果，其他模式我没试过。需求直连是因为有些网站必须直连才能正常访问，而smartdns保证直连的防污染，所以smartdns是必备品，真没办法舍弃哎。
> 
> 1. 添加好直连域名，保存生效
> 2. 重启软路由
> 3. 然后电脑刷新DNS，命令是ipconfig /flushdns
> 4. 然后打开chrome的访客模式 再试试。
>    我弄了下 这样是有效的

HI，谢谢！~我回家后去试试，谢谢你~ 我这些天我也一直在用酸酸乳plus，并且passwall更新后偶尔会去刷固件尝试是否有修复，来回折腾，passwall有些设计很好用，只是开启smartdns的直连名单不正常的问题以我的使用用途环境来说是致命的硬伤。
