### ISSUE TITLE
负载均衡经常异常出现断线情况

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#865]
不知道是什么原因，负载均衡经常出现ping不同导致，节点切换，可以肯定的是节点很稳的，因为如果单独用负载均衡中某一个节点是完全没问题，整合到负载均衡后，就会出现这个问题，大佬有时间可以看下吗，辛苦了

**Comment by hcym** [comment]
我用的没有问题，这个源码最好的就是负载均衡稳定方便，其他方面还是大雕的略胜一筹

**Comment by WYC-2020** [comment]
@hcym 我也不知道是什么鬼。看延迟都是0，但是就是要切换，换回老版本了

**Comment by xiaorouji** [comment]
使用最新源码再试试
