### ISSUE TITLE
完善对Xray(v1.2.0)的支持

### ISSUE THREAD

**Issue by xcyll** [xiaorouji/openwrt-passwall#867]
Xray更新到1.2了，集成了四种协议 。期待加入xray里的ss trojan节点订阅支持 
passwall目前支持订阅Xray：[V2ray]       期待加入Xray：[SS]   ;  Xray：[Trojan]
![2449](https://user-images.githubusercontent.com/63227888/103456397-bb3c6b00-4d30-11eb-9a6c-f6a4d369739f.jpg)
![2014](https://user-images.githubusercontent.com/63227888/103456395-b4adf380-4d30-11eb-9adc-fa47fb241e7b.jpg)

**Comment by xiaorouji** [comment]
It's better to keep it.
