### ISSUE TITLE
更新V2组件提示无法移动到/usr/bin/v2ray/

### ISSUE THREAD

**Issue by linxuankent** [xiaorouji/openwrt-passwall#870]
更新V2组件提示无法移动到/usr/bin/v2ray/

**Comment by Myoko** [comment]
把后面的/去掉

**Comment by linxuankent** [comment]
> 把后面的/去掉

无法移动新文件到：/usr/bin/v2ray

**Comment by xiaorouji** [comment]
容量是否足够？

**Comment by linxuankent** [comment]
不是容量问题，重新编译最新的固件后才出现的问题

**Comment by xcyll** [comment]
昨天的源码 编译时没选v2 在插件里直接更新的   ![532](https://user-images.githubusercontent.com/63227888/103972850-e8fa3780-51a8-11eb-9220-4d67f1a2ff30.jpg)
![714](https://user-images.githubusercontent.com/63227888/103972852-ea2b6480-51a8-11eb-9c71-37af24d74406.jpg)

**Comment by linxuankent** [comment]
> 昨天的原始码编译时没选v2在插件里直接更新的 ![532](https://user-images.githubusercontent.com/63227888/103972850-e8fa3780-51a8-11eb-9220-4d67f1a2ff30.jpg)
> ![714](https://user-images.githubusercontent.com/63227888/103972852-ea2b6480-51a8-11eb-9c71-37af24d74406.jpg)

我是修改了存储位置就可以了

**Comment by dengzg2002** [comment]
同样的问题，改到什么路径？

**Comment by linxuankent** [comment]
> 同样的问题，改到什么路径？

我直接在根目录创建了个文件夹给权限就好了
