### ISSUE TITLE
chinadns-ng 规则更新后，代理接口没有更新

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#872]
开启chinadns-ng后，规则接口如下图
![image](https://user-images.githubusercontent.com/34025388/103719121-52404600-5003-11eb-8c30-b9152186b9d0.png)
d
然后再界面上进行规则更新查看，如下图
![image](https://user-images.githubusercontent.com/34025388/103719157-63895280-5003-11eb-9bb4-acc2c6e0b661.png)
还原到没有进行任何设置的初始状态
同时该目录下/tmp/etc/dnsmasq-passwall.d 另外几个文件也存在类似的问题，望大佬修复

**Comment by xiaorouji** [comment]
有什么问题吗？直接用chinadns-ng作为默认DNS了，无需再为每个dnsmasq分流域名配置dns
