### ISSUE TITLE
关于passwall中使用v2ray节点问题

### ISSUE THREAD

**Issue by meloncn** [xiaorouji/openwrt-passwall#874]
在当前最新版本中（2020.1.6）使用passwall（xray替代v2ray组件）订阅v2ray节点后无法使用：
当主节点选择vmess节点后，客户机器无法获取外网网站的dns解析地址，终端中表现为提示SERVFAIL。此现象仅在使用vmess节点中出现。当使用ssr节点时又正常。
请求得到帮助，谢谢

**Comment by hcym** [comment]
手动改改完事了，瓦工机场的订阅正常，不过是在6简单的v2

**Comment by meloncn** [comment]
> 手动改改完事了，瓦工机场的订阅正常，不过是最简单的v2

你好，我这边订阅是没问题的，也是最简单的v2。但是使用V2节点的时候我怀疑内置dns没有转发相对应的报文导致我的机器获取不到dns信息。以上问题仅在使用v2ray节点时出现，使用ssr相同设置一点问题也没有。v2ray节点也正常，我使用桌面软件可上网

**Comment by xiaorouji** [comment]
查看节点日志

**Comment by meloncn** [comment]
> 查看节点日志

您好！我检查了路由器日志与passwall日志，均未发现错误产生。多次试验后还是这个问题甚至重新编译更换固件源后依然存在此问题。即使用V2Ray节点时无法访问外网，使用SSR节点即可。我使用硬件为newifi3D2。

**Comment by meloncn** [comment]
> 查看节点日志

我甚至怀疑Xray的问题。本人也尝试了ssrplus等，通过与网友交流得知使用新版本编译均出现此问题。老版本可行
![image](https://user-images.githubusercontent.com/54462952/103779240-6ec59800-506e-11eb-884d-6d0c68d07010.png)

**Comment by xiaorouji** [comment]
节点日志
![image](https://user-images.githubusercontent.com/60100640/103783837-2ad59180-5074-11eb-9714-f809cf0fd06f.png)

**Comment by meloncn** [comment]
> 节点日志
> ![image](https://user-images.githubusercontent.com/60100640/103783837-2ad59180-5074-11eb-9714-f809cf0fd06f.png)

你好，现设置为debug级别调试日志如下
`Xray 1.2.0 (OpenWrt) Custom (go1.15.6 linux/mipsle)
A unified platform for anti-censorship.
2021/01/07 01:13:28 [Info] main/json: Reading config: /var/etc/passwall/TCP.json
2021/01/07 01:13:28 [Debug] app/log: Logger started
2021/01/07 01:13:28 [Debug] app/proxyman/inbound: creating stream worker on 0.0.0.0:1041
2021/01/07 01:13:28 [Info] transport/internet/tcp: listening TCP on 0.0.0.0:1041
2021/01/07 01:13:28 [Warning] core: Xray 1.2.0 started
2021/01/07 01:13:35 [Debug] [448753565] proxy/dokodemo: processing connection from: 192.168.1.231:50956
2021/01/07 01:13:35 [Info] [448753565] proxy/dokodemo: received request for 192.168.1.231:50956
2021/01/07 01:13:35 [Info] [448753565] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:35 [Info] [448753565] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:35 [Info] [448753565] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:35 192.168.1.231:50956 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:35 [Info] [448753565] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:35 [Debug] [3475699909] proxy/dokodemo: processing connection from: 192.168.1.231:50957
2021/01/07 01:13:35 [Info] [3475699909] proxy/dokodemo: received request for 192.168.1.231:50957
2021/01/07 01:13:35 [Info] [3475699909] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:35 [Info] [3475699909] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:35 [Info] [3475699909] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:35 192.168.1.231:50957 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:36 [Info] [3475699909] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:39 [Info] [448753565] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:39 [Info] [448753565] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:39 [Debug] [2404476582] proxy/dokodemo: processing connection from: 192.168.1.231:50958
2021/01/07 01:13:39 [Info] [2404476582] proxy/dokodemo: received request for 192.168.1.231:50958
2021/01/07 01:13:39 192.168.1.231:50958 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:39 [Info] [2404476582] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:39 [Info] [2404476582] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:39 [Info] [2404476582] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:40 [Info] [3475699909] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:40 [Info] [3475699909] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:40 [Debug] [344028790] proxy/dokodemo: processing connection from: 192.168.1.231:50959
2021/01/07 01:13:40 [Info] [344028790] proxy/dokodemo: received request for 192.168.1.231:50959
2021/01/07 01:13:40 192.168.1.231:50959 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:40 [Info] [344028790] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:40 [Info] [344028790] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:40 [Info] [344028790] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:40 [Info] [2404476582] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:40 [Info] [344028790] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:42 [Debug] [230850151] proxy/dokodemo: processing connection from: 192.168.1.231:50960
2021/01/07 01:13:42 [Info] [230850151] proxy/dokodemo: received request for 192.168.1.231:50960
2021/01/07 01:13:42 192.168.1.231:50960 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:42 [Info] [230850151] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:42 [Info] [230850151] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:42 [Info] [230850151] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:42 [Info] [230850151] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:44 [Info] [2404476582] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:44 [Info] [2404476582] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:44 [Info] [344028790] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:44 [Info] [344028790] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:44 [Debug] [372641767] proxy/dokodemo: processing connection from: 192.168.1.231:50962
2021/01/07 01:13:44 [Info] [372641767] proxy/dokodemo: received request for 192.168.1.231:50962
2021/01/07 01:13:44 192.168.1.231:50962 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:44 [Info] [372641767] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:44 [Info] [372641767] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:44 [Info] [372641767] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:44 [Info] [372641767] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:46 [Info] [230850151] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:46 [Info] [230850151] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:46 [Debug] [3524195487] proxy/dokodemo: processing connection from: 192.168.1.231:50963
2021/01/07 01:13:46 [Info] [3524195487] proxy/dokodemo: received request for 192.168.1.231:50963
2021/01/07 01:13:46 192.168.1.231:50963 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:46 [Info] [3524195487] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:46 [Info] [3524195487] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:46 [Info] [3524195487] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:47 [Info] [3524195487] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:48 [Info] [372641767] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:48 [Info] [372641767] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe
2021/01/07 01:13:48 [Debug] [3277966068] proxy/dokodemo: processing connection from: 192.168.1.231:50964
2021/01/07 01:13:48 [Info] [3277966068] proxy/dokodemo: received request for 192.168.1.231:50964
2021/01/07 01:13:48 [Info] [3277966068] app/dispatcher: sniffed domain: www.google.com
2021/01/07 01:13:48 [Info] [3277966068] app/dispatcher: default route for tcp:www.google.com:443
2021/01/07 01:13:48 [Info] [3277966068] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:48 192.168.1.231:50964 accepted tcp:172.217.31.228:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:48 [Info] [3277966068] proxy/vmess/outbound: tunneling request to tcp:www.google.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:49 [Debug] [2999966259] proxy/dokodemo: processing connection from: 192.168.1.231:50965
2021/01/07 01:13:49 [Info] [2999966259] proxy/dokodemo: received request for 192.168.1.231:50965
2021/01/07 01:13:49 192.168.1.231:50965 accepted tcp:52.114.159.22:443 [738c9f97c540419ab9039021264e6228]
2021/01/07 01:13:49 [Info] [2999966259] app/dispatcher: sniffed domain: self.events.data.microsoft.com
2021/01/07 01:13:49 [Info] [2999966259] app/dispatcher: default route for tcp:self.events.data.microsoft.com:443
2021/01/07 01:13:49 [Info] [2999966259] transport/internet/websocket: creating connection to tcp:gd.*****.icu:1103
2021/01/07 01:13:49 [Info] [2999966259] proxy/vmess/outbound: tunneling request to tcp:self.events.data.microsoft.com:443 via tcp:gd.*****.icu:1103
2021/01/07 01:13:51 [Info] [3524195487] app/proxyman/outbound: failed to process outbound traffic > proxy/vmess/outbound: connection ends > proxy/vmess/outbound: failed to read header > proxy/vmess/encoding: Unable to Read Header Len > websocket: close 1000 (normal)
2021/01/07 01:13:51 [Info] [3524195487] app/proxyman/inbound: connection ends > proxy/dokodemo: connection ends > proxy/dokodemo: failed to transport response > io: read/write on closed pipe`
感谢您的回复

**Comment by meloncn** [comment]
> 节点日志
> ![image](https://user-images.githubusercontent.com/60100640/103783837-2ad59180-5074-11eb-9714-f809cf0fd06f.png)

你好，现截取debug日志如下，感谢您的回复！
![image](https://user-images.githubusercontent.com/54462952/103839485-6e5aea80-50ca-11eb-9beb-3aa6a08230bc.png)
![image](https://user-images.githubusercontent.com/54462952/103839527-87639b80-50ca-11eb-84e0-58ec8b440a98.png)

**Comment by xiaorouji** [comment]
能否提供节点测试？

**Comment by meloncn** [comment]
> 能否提供节点测试？

当然可以，可否提供一个可通讯方式？

**Comment by xiaorouji** [comment]
xiaoroujixxoo@gmail.com

**Comment by meloncn** [comment]
> [xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

已将相关信息发送至您的邮箱，请查收！十分感谢

**Comment by winstonleee** [comment]
同样的问题，v2节点无法访问

**Comment by Remix123** [comment]
检查下路由器时间是否正确
