### ISSUE TITLE
xray未使用分流节点却会被规则代理

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-passwall#878]
使用1月10日编译的4-6版本
tcp使用中国列表以外，udp使用gfw
本地passwall使用xray trojan+xtls协议连接远端passwall server
在客户端规则管理中添加了哔哩哔哩动画的国内分流规则，但主节点未启用分流节点
访问哔哩哔哩会被直接使用主节点代理，可以在服务端查到访问日志
删除掉规则管理中的分流规则后一切正常
已尝试过重启路由器
![Snipaste_2021-01-11_14-25-46](https://user-images.githubusercontent.com/44677306/104152185-c9b61100-5419-11eb-8e0b-d0e0c88def34.png)
![Snipaste_2021-01-11_14-32-47](https://user-images.githubusercontent.com/44677306/104152230-e6eadf80-5419-11eb-9f0f-e8dc4f51fe47.png)

**Comment by xiaorouji** [comment]
已修复
