### ISSUE TITLE
存在奈飞无网络的反馈，可能是 iptables 规则与新版 Xray-core UDP 冲突

### ISSUE THREAD

**Issue by rprx** [xiaorouji/openwrt-passwall#879]
目前的反馈为：同样是 Xray-core v1.2.1，最新 passwall TV 奈飞显示发生错误，ssrp 可以打开

推测可能是 passwall 设置的 iptables 规则与新版 Xray-core UDP 冲突

**Comment by rprx** [comment]
还有一个反馈是 passwall 提供的 socks 通不了 udp，Xray-core 和 v2fly-core 都是这样

**Comment by rprx** [comment]
补充：这个现象（passwall 无法访问、ssrp 可以访问）有多人反馈，应该是 100% 能复现的，与特定的路由器型号无关

希望遇到问题的朋友在这里发一些日志

**Comment by tritu** [comment]
> 补充：这个现象（passwall 无法访问、ssrp 可以访问）有多人反馈，应该是 100% 能复现的，与特定的路由器型号无关
> 
> 希望遇到问题的朋友在这里发一些日志

Confirmed this issue with xray 1.2.1 and passwall 4.7

**Comment by quango-web** [comment]
刚用aws-ec2安装xray1.22，对应arm架构客户端passwall-xray1.22，谷歌tv的油管及奈飞显示无网络

**Comment by hcym** [comment]
油管tv肯定没问题，奶飞不知道了，arm和x86都正常的

**Comment by slippersheepig** [comment]
将DNS从默认的8.8.4.4修改为8.8.8.8，问题解决。至少我是这样解决的

**Comment by hcym** [comment]
没改过，这个源码有一个优点，我一个原生盒子用大雕不能看油管只能看腾讯😂

**Comment by rprx** [comment]
大家试试这个 commit https://github.com/XTLS/Xray-core/commit/ae98dc75cf30451d3f29684977ff7324e0fc26e4

**Comment by xiaorouji** [comment]
大可能是规则问题，没有走代理。应该与iptables的UDP无关，因为我联机玩游戏没有受到影响。
奈飞TV版不知道，我没有账号也没有设备，无法测试。但有人测试过手机APP端没有问题，TV版未知。

**Comment by rprx** [comment]
@xiaorouji 大概和 PassWall 的奈飞分流实现有关，Xray-core v1.1.5 还是没问题的，v1.2.0 改了透明代理 UDP，可能奈飞分流那里查不到 DNS 了。这个 commit https://github.com/XTLS/Xray-core/commit/ae98dc75cf30451d3f29684977ff7324e0fc26e4 或许解决了问题，但目前还没有人来测试。

**Comment by rprx** [comment]
据群友早上测试反馈，对于 TV Netflix，情况如下：

1. 旧版固件 + Xray-core v1.2.2，问题存在
2. 旧版固件 + https://github.com/XTLS/Xray-core/commit/ae98dc75cf30451d3f29684977ff7324e0fc26e4 ，问题存在
3. 2020.1.20 版固件 + Xray-core v1.2.2，问题存在
4. 2020.1.20 版固件 + https://github.com/XTLS/Xray-core/commit/ae98dc75cf30451d3f29684977ff7324e0fc26e4 ，**问题解决**

麻烦 @xiaorouji 先 bump Xray 至 https://github.com/XTLS/Xray-core/commit/ae98dc75cf30451d3f29684977ff7324e0fc26e4 ，大家用新版本即可解决问题

应该是之前 Xray 任意门往回写 UDP 时对 53 端口的伪造存在可能的来源地址偏差，且对不同环境、使用方式的影响程度不同

**Comment by xiaorouji** [comment]
@rprx passwall透明代理使用的dns方案为外置，配合dnsmasq + ipset 实现分流。而并非直接使用Xray的UDP DNS。所以还是规则问题，因为最新源码更新了规则。

**Comment by rprx** [comment]
@xiaorouji 感觉有些玄学，总之最新 commit https://github.com/XTLS/Xray-core/commit/b60cf0260354dc96340fe9575c010ad08b71e141 进一步优化了 TPROXY UDP，会出现在周五的版本中

BTW，有多人反映 2020.1.20 版固件的 ssrp 分流模式打不开奈飞，旧版或不分流均正常，麻烦 @Mattraks

**Comment by xiaorouji** [comment]
@rprx Netflix似乎不需要用到UDP

**Comment by rprx** [comment]
@xiaorouji 应该与 udp 无关，是 ssrp 代码的问题，lean openwrt 今天的源代码更新已修复 ssrp 奈飞分流

**Comment by xiaorouji** [comment]
@rprx 是否可以考虑给Xray内置DNS支持DNS over TCP，用TCP请求DNS？目前passwall默认DNS方案为pdnsd tcp去请求，因为有些节点可能会不支持UDP转发。（虽然可以用DoH）。如果Xray能直接支持的话，又可以减去一个依赖了。

**Comment by rprx** [comment]
@xiaorouji 正好昨天也有人提到，我研究一下
