### ISSUE TITLE
希望主界面加入快速编辑当前分流节点的功能

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#880]
之前的多节点特性可以在基本设置页面统一切换各节点配置文件，更换到xray分流方案之后需要先进入节点列表再选择分流节点更改，而某些低配置设备若订阅的节点数很多节点列表加载会很慢，消耗很多无谓的时间，若能在基本设置页面的节点选框旁加入”编辑当前节点“按钮会更方便一些。

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/104819167-af8b9100-5866-11eb-956d-59202b87f4d0.png)

**Comment by hathlife** [comment]
是上面图这个意思，但是我更新了4-8源码没看到啊，卸载luci删config重装也没看到。。。
![image](https://user-images.githubusercontent.com/19867269/104831325-b7791e80-58c2-11eb-8e63-1397a968a925.png)

**Comment by xiaorouji** [comment]
可能不兼容新版luci
