### ISSUE TITLE
Passwall 组件更新 手动填写组件地址,不生效.

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#881]
比如我编译Passwall时不选xray, 组件更新里手动填写xray的文件路径, Passwall仍然认为我没有安装xray,无法正确调用xray二进制文件.
由于空间限制,我只能外置xray等软件,但是编译时不选xray的话,生成的固件就无法调用xray.

**Comment by xiaorouji** [comment]
测试没有问题

**Comment by z826540272** [comment]
> 测试没有问题

不选xray编译之后，手动填写xray地址，软件也无法正常调用xray，编译xray的情况下，软件是可以正常调用手动填写的xray的

**Comment by xiaorouji** [comment]
日志发一下？

**Comment by z826540272** [comment]
[image: QQ截图20210207090342.jpg]
您说的是passwall里面的日志选项吗,看了下正常的,没有别的信息
举个例子,我编译的时候没有选择Brook,但是组件更新里填写了brook,也可以正常识别
添加节点的时候却不可以调用Brook
[image: QQ截图20210207090435.jpg]
[image: QQ截图20210207090757.jpg]

>

**Comment by z826540272** [comment]
[img]https://p.pstatp.com/origin/13855000427ea03de0f18[/img]
[img]https://p.pstatp.com/origin/139090000313b934394b8[/img]
[img]https://p.pstatp.com/origin/138370003dfab79b70129[/img]

**Comment by xiaorouji** [comment]
已修复
