### ISSUE TITLE
请求考虑修改自动切换页面的主节点逻辑

### ISSUE THREAD

**Issue by hplee0120** [xiaorouji/openwrt-passwall#882]
个人看法 觉得自动切换页面的“主节点”没有存在的意义，这样会造成跟正在运行的节点变成双“主节点”的现象。或者应该直接让他跟随我们指定的正在运行的节点。举个例子，我全局使用的是节点1，启用自动切换后我需要将自动切换的主节点再设置成节点1，然后备用节点2，节点3。但是如果比如最近我使用的节点1发现不好用，我已经将tcp节点设置成节点4使用，保留2.3备用节点。此时我还需要另外去调整一下自动切换的“主节点”，这一步感觉是多余的或者繁琐。如果不同时调整这两个节点，1分钟过后会自动跳转到自动切换的主节点。所以比较合理的应该是让自动切换的主节点跟随我们设置的tcp节点。主节点就应该是我们自己设置的那个正在运行的节点，而不是双主节点。

**Comment by greennyreborn** [comment]
说的挺有道理

**Comment by xiaorouji** [comment]
请尝试使用最新源码。
