### ISSUE TITLE
使用新版本4-6以后，使用Xray内核出错

### ISSUE THREAD

**Issue by e703** [xiaorouji/openwrt-passwall#884]
正常配置没问题，不定时出现，客户端无法获取DNS信息问题。
即，配置后服务工作正常，过一段时间后，路由器上DNS查询正常，可是客户端无法获取DNS信息。
X64软路由，使用大雕的源码编译，最新版本。
执行service passwall restart后出现如下错误提示。
ip6tables: Chain already exists.
ip6tables: Chain already exists.
ip6tables: Chain already exists.
ip6tables: Chain already exists.
但是客户端查询DNS恢复正常。

过段时间后错误再现。

**Comment by rprx** [comment]
试试 https://github.com/xiaorouji/openwrt-passwall/issues/879#issuecomment-763509357
