### ISSUE TITLE
pdnsd.cache大小始终为0，缓存不生效

### ISSUE THREAD

**Issue by 2785303357** [xiaorouji/openwrt-passwall#890]
根据网上说的，加上 echo -ne "pd13\000\000\000\000" 的版本标识符也不行。
pdnsd获取dns倒是工作正常，系统也不报错，就是没缓存每次都要重新查

**Comment by xiaorouji** [comment]
dnsmasq有缓存就行

**Comment by 2785303357** [comment]
查了下，dnsmasq缓存时间使用min-cache-ttl，限制为最高1小时，还是pdnsd靠谱啊。pdnsd就是以缓存和tcp为主要用途的啊
