### ISSUE TITLE
访问控制对 Google tv / Google home 无效，疑似不能添加防火墙规则？

### ISSUE THREAD

**Issue by artxia** [xiaorouji/openwrt-passwall#894]
问题是：
当 TCP默认*代理模式 设置为 中国列表外，关闭所有访问控制时。所有设备和网站正常访问。
当 TCP默认*代理模式 设置为 不代理，开启访问控制（如下图）时。Google tv 不能访问外网，剩余设备所有访问正常。
![image](https://user-images.githubusercontent.com/50513568/105488359-72068800-5cec-11eb-946f-8b40d6d2bb8c.png)
下面附一些开启访问控制时的配置截图
DNS配置如下
![image](https://user-images.githubusercontent.com/50513568/105488820-34562f00-5ced-11eb-92d5-3dba12c2d797.png)
日志显示访问控制是设置成功的（MAC 结尾为 77 这个）
![image](https://user-images.githubusercontent.com/50513568/105489113-b0507700-5ced-11eb-8a6e-19d99d1a38b4.png)
**但是在防火墙表里面并没有这条规则**
![image](https://user-images.githubusercontent.com/50513568/105489345-0b826980-5cee-11eb-82d2-7e9c5f00a711.png)

以上，还请帮忙看看

**Comment by artxia** [comment]
找到原因了，居然是`Google tv`这个名字不能用，不知道会和啥冲突。 改成其他任何名字就解决了。
希望检查修复一下吧

**Comment by xiaorouji** [comment]
刚才试了一下，的确是。不能带有空格，最新源码优化了一下
https://github.com/xiaorouji/openwrt-passwall/commit/318f37e619385dae3c18bd15705cd8c4e69841c6
