### ISSUE TITLE
WAN口重新拨号后无法代理

### ISSUE THREAD

**Issue by xiaobaishu1** [xiaorouji/openwrt-passwall#895]
定时任务设置* * * * *  /sbin/ifup wan 以后重新获取IP后发现无法代理 显示谷歌是通的但是就是连接不上 需要重新点一下保存才能正常使用 希望能改一下IP有变化后重启一下

**Comment by xiaobaishu1** [comment]
![image](https://user-images.githubusercontent.com/53339509/105569930-f1de3200-5d80-11eb-8002-8ecf995b8590.png)

**Comment by xiaobaishu1** [comment]
在定时任务后面加上passwall的restart都没解决 要先用stop再用boot才能正常 这也算暂时解决问题了

**Comment by xiaorouji** [comment]
理论上重新拨号后，防火墙会重新加载规则，passwall会自动重启的。
