### ISSUE TITLE
dns选择xray,选择通过socks节点，点击保存应用会出现Request Entity Too Large

### ISSUE THREAD

**Issue by kxjhcmc** [xiaorouji/openwrt-passwall#896]
当然把选项卡切换到第一个，点击确认保存，不会报错。

**Comment by kxjhcmc** [comment]
chrome请求头信息如下：
POST /cgi-bin/luci/admin/services/passwall HTTP/1.1
Host: 192.168.0.1
Connection: keep-alive
Content-Length: 4096
Cache-Control: max-age=0
Origin: http://192.168.0.1
Upgrade-Insecure-Requests: 1
DNT: 1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryLvfLHB6IvosfyBdl
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Referer: http://192.168.0.1/cgi-bin/luci/admin/services/passwall
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,zh-TW;q=0.8
Cookie: sysauth=a25fdbcbe4e53bd6db2b538fb0331ce3

**Comment by xiaorouji** [comment]
用了nginx？

**Comment by kxjhcmc** [comment]
用的lean的源码，编译的x64的固件，是j1900的软路由。

**Comment by yunxi993** [comment]
还有个问题，本地DNS 选择Xray  腾讯的DOH、百度检测不通，阿里的可以通
并且腾讯的还会导致Docker跑脚 找不到API 没网络
换成阿里的就正常了，不知道是不是我这的问题，是不是就我这样。
升级插件版本的时候，有恢复默认.

**Comment by snakwu** [comment]
@xiaorouji  借个地方请教一下，这个xray DNS有什作用的，谢谢

**Comment by kxjhcmc** [comment]
今天编译了最新版本，这个问题又神奇的消失了，可能和lean源码有关系，我也不知道。
