### ISSUE TITLE
4-10版本Xray DNS

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall#898]
昨天上午升级的4-10版本，升级后有恢复默认。

本地DNS：Xray DNS(Doh)
Doh请求地址：DNSPod
出现百度检测不通、并且使用Docker跑脚本提示：API请求失败、请检查网络
开始以为脚本或者Docker出了问题，全部都重新部署过，还是同样的问题

Doh请求地址：AliDNS
百度检测是通的
使用Docker跑脚本也没有问题

**Comment by xiaorouji** [comment]
你意思是说DNSPod的DoH无法使用吧，应该是换了IP，不是119.29.29.29了。
你尝试选择自定义输入：https://doh.pub/dns-query,162.14.21.178
再试试

**Comment by yunxi993** [comment]
> 你的意思是说DNSPod的DoH无法使用吧，应该是换了IP，不是119.29.29.29了。
> 你尝试选择自定义输入：[https](https://doh.pub/dns-query,162.14.21.178) :
> //doh.pub/dns-query,162.14.21.178再试试

嗯，换了“https://doh.pub/dns-query,162.14.21.178”  百度检测通了.
