### ISSUE TITLE
节点列表将手动添加节点按钮与其他按钮放到一起

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#899]
现在要手动添加节点需要拉到页面底部，如果使用大机场（几百个节点）订阅的话体验会很不舒服。将手动新增的按钮放到顶部应该不会影响使用逻辑，而且方便设置分流。

**Comment by xiaorouji** [comment]
下一个版本就有

**Comment by xiaorouji** [comment]
见最新源码
![image](https://user-images.githubusercontent.com/60100640/105630848-45867380-5e86-11eb-9767-25e597b9cd95.png)
