### ISSUE TITLE
新版本好像出问题了

### ISSUE THREAD

**Issue by czxinshui** [xiaorouji/openwrt-passwall#900]
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'trojan-plus', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'trojan-go', which does not exist
WARNING: Makefile 'package/feeds/passwall/luci-app-passwall/Makefile' has a dependency on 'chinadns-ng', which does not exist

**Comment by xiaorouji** [comment]
没有 你重拉源码即可
