### ISSUE TITLE
自動切換亂碼

### ISSUE THREAD

**Issue by Jerry198384** [xiaorouji/openwrt-passwall#903]
最近幾個版本 每當重新訂閱節點後 自動切換裡設置好的節點都會變成“42568f0ebeb64c48a6ef0b963b5f6241”這樣子的亂碼 求解決 謝謝

**Comment by xiaorouji** [comment]
試下更新最新源碼進行測試

**Comment by Jerry198384** [comment]
最新4-12都是這樣，現在只能用回4-3正常。

**Comment by xiaorouji** [comment]
這個問題可能是因為你訂閱節點更新了，舊的節點無法匹配到新的節點。
還有可能是因為你訂閱前先清空節點了，然後再訂閱
