### ISSUE TITLE
切换节点无法联网

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall#904]
不知道是普遍现象还是只有我这样，基于最新版本136c186编译，每次（几乎每次）在切换节点保存并应用后会出现谷歌连接可以检测（有ping值）却无法联网的情况…基本上都需要开开关关好几次才可以解决这个问题……
本来以为是chinadns-ng的问题（我有编译进去），最后发现开关chinadns-ng并没有什么影响……
总之…我也不知道哪里出问题了（也重置过一次psw）…

**Comment by jh0072110** [comment]
整个重置了一下软路由，还是有这个问题ಠ_ಠ

**Comment by xiaorouji** [comment]
请提供 设备机型 逻辑运行日志 TCP节点日志
或是把/etc/config/passwall配置文件发往我的邮箱

**Comment by microdockman** [comment]
> 整个重置了一下软路由，还是有这个问题ಠ_ಠ

https-dns-proxy
luci-app-https-dns-proxy
这个安装包会出现ping的通不联网的现象，重启也不行。症状有点类似

**Comment by jh0072110** [comment]
> 请提供 设备机型 逻辑运行日志 TCP节点日志
> 或是把/etc/config/passwall配置文件发往我的邮箱

sorry好尴尬，打开tcp日志了，可是…这个日志在哪里……

**Comment by jh0072110** [comment]
![image](https://user-images.githubusercontent.com/50496854/106342058-69104a80-62da-11eb-83e3-15ab946701a9.png)
在等大佬回复的同时发一张比较直观（也许吧）的截图……

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/106350114-6b8c9780-630e-11eb-823e-c68d2019102b.png)
或者你直接把配置文件发我邮箱吧

**Comment by jh0072110** [comment]
> ![image](https://user-images.githubusercontent.com/60100640/106350114-6b8c9780-630e-11eb-823e-c68d2019102b.png)
> 或者你直接把配置文件发我邮箱吧

好呀好呀，请教一下您的邮箱是？还有配置中的节点信息需要全部保留吗？

**Comment by xiaorouji** [comment]
@jh0072110 要的，不然我无法测试，xiaoroujixxoo@gmail.com

**Comment by jh0072110** [comment]
> @jh0072110 要的，不然我无法测试，[xiaoroujixxoo@gmail.com](mailto:xiaoroujixxoo@gmail.com)

已发

**Comment by jh0072110** [comment]
虽然大佬没有刻意修…但是最新源码编译的…好了……

**Comment by jh0072110** [comment]
唉，看起来还是关不掉这个issue…

**Comment by xiaorouji** [comment]
还有问题？

**Comment by jh0072110** [comment]
> 还有问题？

可不是么，到现在的dev问题都没解决，唉…

**Comment by jh0072110** [comment]
@xiaorouji 问题变得越来越…有趣了……
![image](https://user-images.githubusercontent.com/50496854/107111407-e1eb4580-688a-11eb-805b-281227a8528d.png)
![IMG_8552DD05F50E-1](https://user-images.githubusercontent.com/50496854/107111411-ec0d4400-688a-11eb-940d-5792a047e21a.jpeg)
给我整的有点茫然了…我确实不知道哪里出问题了……

**Comment by xiaorouji** [comment]
试试把QUIC给关掉？

**Comment by jh0072110** [comment]
最近暂时没复现问题，等再出现了再说吧……
