### ISSUE TITLE
一人血书，请不要移除v2ray。

### ISSUE THREAD

**Issue by user1121114685** [xiaorouji/openwrt-passwall#907]
v2ray与x2ray兼容存在巨大问题，这v2ray vless tls 在x2ray上一半都跑不到。好好的又没冲突。恳请回档补药移除v2ray。他们以后也是两个东西。

**Comment by rprx** [comment]
不评价主题，只是想说一下，Xray 都写成 x2ray 了，要么没认真用过/测试过，要么用的是盗版。

另外由于 VLESS 是我写的，我可以明确说 Xray 的 VLESS 和 v2fly 的是兼容的，且 Xray 的比 v2fly 的性能更好。

**Comment by Myoko** [comment]
现在有了XRAY V2 已经没有什么意义了！V2有的XRAY都有！有些甚至更好

**Comment by user1121114685** [comment]
> 不评价主题，只是想说一下，Xray 都写成 x2ray 了，要么没认真用过/测试过，要么用的是盗版。
> 
> 另外由于 VLESS 是我写的，我可以明确说 Xray 的 VLESS 和 v2fly 的是兼容的，且 Xray 的比 v2fly 的性能更好。

可以使用，只是tls模式下性能差距很大，我想大概是每次都优先尝试xtls的原因。

**Comment by user1121114685** [comment]
> 现在有了XRAY V2 已经没有什么意义了！V2有的XRAY都有！有些甚至更好

这里不是讨论passwall的地方吗？

**Comment by jh0072110** [comment]
不做评价，单纯看到你把r大引来了吃个瓜～
不过从理论上来说，不应该会存在你说的问题，如果你服务端设置的tls他怎么会去优先尝试xtls……

**Comment by user1121114685** [comment]
> 不做评价，单纯看到你把r大引来了吃个瓜～
> 不过从理论上来说，不应该会存在你说的问题，如果你服务端设置的tls他怎么会去优先尝试xtls……


可能有人造谣吧！其实我这说的是兼容问题，也很好测试。并不是对xray有什么意见。只是想着passwall多兼容一样是一样。况且以后肯定v2fly与xray是两个方向的东西。

**Comment by jh0072110** [comment]
> > 不做评价，单纯看到你把r大引来了吃个瓜～
> > 不过从理论上来说，不应该会存在你说的问题，如果你服务端设置的tls他怎么会去优先尝试xtls……
> 
> 可能有人造谣吧！其实我这说的是兼容问题，也很好测试。并不是对xray有什么意见。只是想着passwall多兼容一样是一样。况且以后肯定v2fly与xray是两个方向的东西。

造谣的意思是…你木有实测过，只是用听说来提的issue吗…有点随性啊…
我觉得现在功能并未产生分叉的情况下只保留一个也是为了维护方便吧，如果产生分叉了肉鸡大佬应该会加回去的…

**Comment by user1121114685** [comment]
> > > 不做评价，单纯看到你把r大引来了吃个瓜～
> > > 不过从理论上来说，不应该会存在你说的问题，如果你服务端设置的tls他怎么会去优先尝试xtls……
> > 
> > 
> > 可能有人造谣吧！其实我这说的是兼容问题，也很好测试。并不是对xray有什么意见。只是想着passwall多兼容一样是一样。况且以后肯定v2fly与xray是两个方向的东西。
> 
> 造谣的意思是…你木有实测过，只是用听说来提的issue吗…有点随性啊…
> 我觉得现在功能并未产生分叉的情况下只保留一个也是为了维护方便吧，如果产生分叉了肉鸡大佬应该会加回去的…

实测过了。没有去翻源码看

**Comment by jh0072110** [comment]
> > > > 不做评价，单纯看到你把r大引来了吃个瓜～
> > > > 不过从理论上来说，不应该会存在你说的问题，如果你服务端设置的tls他怎么会去优先尝试xtls……
> > > 
> > > 
> > > 可能有人造谣吧！其实我这说的是兼容问题，也很好测试。并不是对xray有什么意见。只是想着passwall多兼容一样是一样。况且以后肯定v2fly与xray是两个方向的东西。
> > 
> > 
> > 造谣的意思是…你木有实测过，只是用听说来提的issue吗…有点随性啊…
> > 我觉得现在功能并未产生分叉的情况下只保留一个也是为了维护方便吧，如果产生分叉了肉鸡大佬应该会加回去的…
> 
> 实测过了。没有去翻源码看

实测如果真的性能差距明显的话…其实可以去xray-core区提issue，不是吹的，r大就是个写码机器，每天三四点都还在肝，应该会很快处理掉你的问题的…（只是一个小建议）

**Comment by rprx** [comment]
@user1121114685 

> 可以使用，只是tls模式下性能差距很大，我想大概是每次都优先尝试xtls的原因。

解决潜在问题 & 答疑

1. 请附上测试方式及对比数据
2. 选 TLS 时不会用 XTLS

**Comment by user1121114685** [comment]
> @user1121114685
> 
> > 可以使用，只是tls模式下性能差距很大，我想大概是每次都优先尝试xtls的原因。
> 
> 解决潜在问题 & 答疑
> 
> 1. 请附上测试方式及对比数据
> 2. 选 TLS 时不会用 XTLS

好的大佬，我会在近期进行测试，并到xray提交issue。
