### ISSUE TITLE
自动切换节点后tcp那里会显示不运行，节点无法连通

### ISSUE THREAD

**Issue by vie72** [xiaorouji/openwrt-passwall#909]
x86，4-12，开启自动切换节点后，等节点检查完，tcp哪里会显示未运行，必须重新开启passwall，才会正常，之前4-6没有这样的问题。

![微信图片_20210130134540](https://user-images.githubusercontent.com/69401701/106348471-7ab91880-6301-11eb-8a73-98ee4b9756ac.png)
![微信图片_20210130134548](https://user-images.githubusercontent.com/69401701/106348472-7c82dc00-6301-11eb-9e7a-56dea5ef0711.png)
![微信图片_20210130134544](https://user-images.githubusercontent.com/69401701/106348474-7d1b7280-6301-11eb-9dc3-d3d97aa13253.png)

**Comment by vie72** [comment]
关闭自动切换节点后，没有问题

**Comment by xiaorouji** [comment]
更新源码再试下？
