### ISSUE TITLE
I am confused about the DNS problem

### ISSUE THREAD

**Issue by M33FT** [xiaorouji/openwrt-passwall#912]
Hi . . .
Thanks for your great program and support.

For two weeks now, my proxy **(VLESS + TCP + TLS / xtls-rprx-splice)** has been down on my openwrt devices like **RaspberryPI4**, 
**RaspberryPi3B**, **WRT1900ACS**, **WRT1200**, **WRT32X**. I have to say that I have this proxy on PC right now
(With v2rayN-Core client) and Android phone (with V2rayNG client) I use without any problem.

I did a lot of different tests and did not understand why my proxy failed on all these devices at the same time. But I'm sure my 
problem is with the DNS settings. Passwall is a very powerful program, but unfortunately it has no Documenty (or maybe I did not find it).
I do not live in China, but where I am, the filtering system is very strong and very close to GFW, and they use **Deep packet 
inspection (DPI)** technology in layer 7 in their firewalls.

Anyway, I do not know the settings of the DNS section of Passwall to transfer DNS requests through the same xray tunnel and I 
do not know exactly how to do these settings.

Someone told me that I should change the DNS Forwarding in Dnsmasq, but I do not know how to do that?
Can you please imagine that I am a "noob" and explain very simply to a noob how to do these DNS settings?

Server side config:

VLESS+TCP+TLS/xtls-rprx-splice
===============================

Server: topsecret.com
Port: 443
Protocol: VLESS
Stream Security: XTLS
ID: d301635e-fae9-468b-8877-cd1b526caa13
Transport Protocol: TCP
Flow: xtls-rprx-splice

I will show all my settings below.

![01](https://user-images.githubusercontent.com/63062740/106377956-ee1c6200-63b5-11eb-9953-4821265c2634.jpg)

### I tested different DNS settings but found that you recommend this setting to others

![02](https://user-images.githubusercontent.com/63062740/106377961-f5437000-63b5-11eb-8bbd-28ef04f91a12.jpg)

![03 1](https://user-images.githubusercontent.com/63062740/106378054-aa762800-63b6-11eb-9a41-e6077c0ab2bc.jpg)

![03](https://user-images.githubusercontent.com/63062740/106378087-f628d180-63b6-11eb-8d78-0507a8912f38.jpg)

### I do not use any of these programs normally.

![04](https://user-images.githubusercontent.com/63062740/106378153-86ffad00-63b7-11eb-9b95-fbc87cb44808.jpg)

### Do I have to do anything here?

![05](https://user-images.githubusercontent.com/63062740/106378162-9aab1380-63b7-11eb-81c2-588cda24f683.jpg)

### Is it normal?

![06](https://user-images.githubusercontent.com/63062740/106378182-e6f65380-63b7-11eb-8ba9-e645c9d69a81.jpg)

### I am using the latest version of Coolwoolf + Passwall (14.12) on all my devices.

![07](https://user-images.githubusercontent.com/63062740/106378217-4d7b7180-63b8-11eb-89fa-b2888fc110b5.jpg)

**Comment by jh0072110** [comment]
It doesn't seem like a wise option for you to make all your server information public ......

**Comment by M33FT** [comment]
> It doesn't seem like a wise option for you to make all your server information public ......

Thanks man, but I think you did not read my post carefully. This information is not real

**Comment by M33FT** [comment]
@xiaorouji

**Comment by M33FT** [comment]
Boss, can you help me? 
@xiaorouji

**Comment by xiaorouji** [comment]
Try to change local DNS ?
Unfortunately, the default rule is only has china list, so I am not sure if it can be used normally in other countries.
Maybe you can try to use GFW mode.

**Comment by M33FT** [comment]
Boss, I did whatever configuration I knew (I mean Local DNS). 
My problem is exactly the same as our friend's problem  #911 that their DNS is hijacked in port 53.
That's why I used luci-app-https-dns next to Passwall, which worked, but I don't know what happened, it doesn't work anymore.
Interestingly, NaiveProxy works but I can not use it because I have to use it on a variety of platforms.
What else can I do in DNS?
	
Boss, I'm going crazy and I don't know what to do (▱˘︹˘▱)
@xiaorouji

**Comment by Mattraks** [comment]
Add dns ip to the mandatory proxy list

**Comment by xiaorouji** [comment]
However, in general, if you use the built-in dns of passwall, you do not need to add it to the proxy IP list. If the transparent proxy of dns cannot be used, you can use dns2socks or doh and socks to query.

**Comment by M33FT** [comment]
I have never used dns2socks.
Are there any special server-side settings that need to be done?
Because now I made these settings in the photo, but it didn't work.
I did not understand this part of DNS. Is it possible to explain more easily?
Thanks @xiaorouji 


![01](https://user-images.githubusercontent.com/63062740/106388030-debb0a00-63f1-11eb-8ff7-fca8ce5e8288.jpg)



![02](https://user-images.githubusercontent.com/63062740/106388035-e4185480-63f1-11eb-85e8-1bb4476f7093.jpg)

**Comment by xiaorouji** [comment]
yes, but you socks Main switch need to check.

**Comment by M33FT** [comment]
@xiaorouji Thank you for taking the time to answer me.
I tried but it still did not work.
It is possible to see this Log, maybe it is something ordinary.


![03](https://user-images.githubusercontent.com/63062740/106390102-0911c500-63fc-11eb-9470-2164ff0b5064.jpg)

**Comment by xiaorouji** [comment]
I think (maybe) it is possible that your domain name entered the proxy list, causing a loopback.
You try to add you domain to rule list the direct list.
Or you try to edit the node, Address use ip address, and Domain use your domain.

**Comment by M33FT** [comment]
All devices failed. Is it possible ?!
God, why is this problem not solved?
I just want to cry

![1111](https://user-images.githubusercontent.com/63062740/106395561-19379d80-6418-11eb-8836-9430933dc1e9.gif)

**Comment by xiaorouji** [comment]
You can try to use other application.

**Comment by M33FT** [comment]
I also checked SSR, VSSR and it did not work.
Can I understand why I can easily use V2rayN core on PC?

**Comment by chenxuan5858** [comment]
Check Ur firewall settings about 53 port hijack

**Comment by M33FT** [comment]
### Do you think my firewall settings are correct now?
### Do I have to add a new rule?

@chenxuan5858 @xiaorouji 

![01](https://user-images.githubusercontent.com/63062740/106738740-90924a80-662d-11eb-8930-679b48f9b113.jpg)


![02](https://user-images.githubusercontent.com/63062740/106738748-925c0e00-662d-11eb-81a9-3984e7a8f073.jpg)


![03](https://user-images.githubusercontent.com/63062740/106738759-9556fe80-662d-11eb-9419-1b4f652dc7bb.jpg)


![04](https://user-images.githubusercontent.com/63062740/106738762-96882b80-662d-11eb-8826-3de607cce458.jpg)

**Comment by chenxuan5858** [comment]
![image](https://user-images.githubusercontent.com/33675890/106744478-c994e400-665a-11eb-86fb-c59272529dcf.jpeg)

**Comment by M33FT** [comment]
### Thank you very much for answering me.
### As you said, I deleted that value and also set the value "127.0.0.1:53" for
### the internal Passwall Resolver and set the following settings but it did not work.
### I have given descriptions on the photos. Thank you for guiding me.

![01](https://user-images.githubusercontent.com/63062740/106751823-fa672000-663e-11eb-99d7-25e73bcac7eb.jpg)



![02](https://user-images.githubusercontent.com/63062740/106752422-add01480-663f-11eb-91d1-698210bee90a.jpg)



![03](https://user-images.githubusercontent.com/63062740/106751833-005d0100-663f-11eb-8d20-3e554042c755.jpg)



![04](https://user-images.githubusercontent.com/63062740/106751869-0c48c300-663f-11eb-83d9-05239f093b31.jpg)



![05](https://user-images.githubusercontent.com/63062740/106751884-0fdc4a00-663f-11eb-8718-6fb46204370e.jpg)



### Sorry if I asked too many questions because many things are unclear to me.

### Thanks buddy

**Comment by chenxuan5858** [comment]
I leave all my settings here, hope helpful
![Snipaste_2021-02-03_21-26-55](https://user-images.githubusercontent.com/33675890/106753850-2f876880-6667-11eb-82de-65cd8e2fa5df.png)
![Snipaste_2021-02-03_21-27-22](https://user-images.githubusercontent.com/33675890/106753852-30b89580-6667-11eb-8213-43c491a9d99c.png)
![Snipaste_2021-02-03_21-27-44](https://user-images.githubusercontent.com/33675890/106753855-31512c00-6667-11eb-99e1-df1a0d54506c.png)
![Snipaste_2021-02-03_21-28-11](https://user-images.githubusercontent.com/33675890/106753856-31e9c280-6667-11eb-996c-6e7c981e5a90.png)
![Snipaste_2021-02-03_21-28-26](https://user-images.githubusercontent.com/33675890/106753858-32825900-6667-11eb-9593-cd8db190e879.png)
![Snipaste_2021-02-03_21-28-43](https://user-images.githubusercontent.com/33675890/106753860-331aef80-6667-11eb-8cf3-9175188de303.png)
![Snipaste_2021-02-03_21-29-09](https://user-images.githubusercontent.com/33675890/106753862-33b38600-6667-11eb-8c01-26967db5dbe1.png)
![Snipaste_2021-02-03_21-29-34](https://user-images.githubusercontent.com/33675890/106753865-344c1c80-6667-11eb-8f65-f3432cde75c0.png)
![Snipaste_2021-02-03_21-30-53](https://user-images.githubusercontent.com/33675890/106753868-34e4b300-6667-11eb-835d-f022c8a69570.png)

**Comment by M33FT** [comment]
Thanks Buddy

![1111](https://user-images.githubusercontent.com/63062740/106754555-5aab9100-6642-11eb-8963-42b64962d159.gif)

**Comment by chenxuan5858** [comment]
Firstly, if you use dnsmasq as resolver, you need to set the public dns in forwardings and check the ignore resolve files box which means that the ISP DNS will not been set in system.

**Comment by chenxuan5858** [comment]
If you use the SMARTDNS,just set as what I do

**Comment by chenxuan5858** [comment]
I am hightly recommend to set the WAN DNS to 127.0.0.1

**Comment by M33FT** [comment]
It was great man / it was completely clear to me what I should do / I am going to compile SmartDNS with the latest version of Snapshot from coolwoolf. / Thanks and good luck bro ;-)

**Comment by chenxuan5858** [comment]
Cheers!

**Comment by xiaorouji** [comment]
Good luck, this issue is closed because there is no new reply for more than 1 month. If you encounter any problems, welcome back.
