### ISSUE TITLE
关于规则管理的自动更新功能。

### ISSUE THREAD

**Issue by snakwu** [xiaorouji/openwrt-passwall#913]
在设置规则自动更新时，在系统的计划任务里会生成一个定时任务，当重启op后，这个定时任务就消失了，然后又要手动在pass里开关一下自动更新，这样才又会在系统的计划任务生成这个定时任务，希望修复一下，谢谢

**Comment by snakwu** [comment]
同时发现，当那个系统的定时任务一消失，就不能fq了，估计是和什么月冲突，然后passwall崩溃了，然后点清理一下ipset，就又正常了，那个定时更新规则的任务又出来了，这个应该是和我之前提到过的，经常启动不能fq，要点一下清理ipset是同一个问题！  @xiaorouji

**Comment by xiaorouji** [comment]
我无法复现，可能是和什么插件冲突了吧？

**Comment by snakwu** [comment]
> 我无法复现，可能是和什么插件冲突了吧？

我用的是openwrt最新的源码，我感觉应该是和Dnsmasq 有冲突，我的Dnsmasq 版本是dnsmasq-full | 2.84~~test3-1

**Comment by snakwu** [comment]
@xiaorouji  现在基本每次启动都需要手动点击清理ipset，才能正常访问国外，用的是你的最新源码加op官方master源码，插件也就是一个解锁网易云灰色音乐，其他也没什么了，希望可早日修复这问题，谢谢！

**Comment by xiaorouji** [comment]
官源似乎有锁，防火墙重启规则的时候似乎好容易会卡住

**Comment by snakwu** [comment]
@xiaorouji  是这个现像，另外发现的是，在pass的设置页面上，测试google和github是正常，但下面的设备不能访问国外，国内正常，等重启完，手动清一下ipset下面的设备才正常访问

**Comment by snakwu** [comment]
@xiaorouji  我现在的临时解决办法是，写一个sh文件，里面写：
sleep 10
/etc/init.d/passwall stop
sleep 3
/etc/init.d/passwall start
然后放到op的启动项里，每次启动自动执行一次，这样来解决
