### ISSUE TITLE
关于搭配chinadns-ng使用的方案探讨

### ISSUE THREAD

**Issue by garypang13** [xiaorouji/openwrt-passwall#914]
建议将 chinadns-ng 作为默认依赖, 大陆白名单模式如果不搭配chinadns-ng的话, 就只有gfwlist里的域名才会通过代理解析DNS,等于除gfwlist外的其他国外网站的CDN都无效了.

另外如果使用的是gfwlist模式的话,就不应该可选chinadns-ng了, 对于国外网站, chinadns-ng选择的永远是离代理节点最近的CDN,而gfwlist模式除了gfwlist里的域名外,其他所有国外网站都是从本地直连的. 从本地应该直连离本地最近的CDN才对.

**Comment by xiaorouji** [comment]
应该是chnlist吧

**Comment by garypang13** [comment]
TCP代理选择的是美国节点 模式是中国列表外
实测结果如下
![ip](https://user-images.githubusercontent.com/48883331/106844698-34d6c880-66e4-11eb-9407-27666012a2f5.png)

中国列表外模式下 www.yahoo.com走的是美国代理,那查询到的CDN应该也是美国IP才对, 而实际不开chinadns-ng的话得到的IP却是离本地最近的台湾IP

**Comment by xiaorouji** [comment]
你说的也并不是没有道理，gfw模式列表的确是不需要用到

**Comment by hplee0120** [comment]
初步想到的建议是将dns设置页面将chinadns-ng和chnlist去除。在默认代理模式下方增加一个附属框，选中gfw模式不会出现这个附属框。选中大陆白名单后出现
默认代理模式:大陆白名单
代理分流模式:默认
                        大陆白名单+chinadns-ng
                        大陆白名单+chnlist
不知是否合理

**Comment by xiaorouji** [comment]
可以试试用 dev分支 https://github.com/xiaorouji/openwrt-passwall/commit/4ec9aaf661a70dbc15d29e947fd3416e37dd04a3

**Comment by xiaorouji** [comment]
见4-13
用了好几天，应该没有什么大问题。

**Comment by garypang13** [comment]
> 见4-13
> 用了好几天，应该没有什么大问题。

chinadns-ng选项都不显示了,确定有安装chinadns-ng,

**Comment by lededev** [comment]
默认使用chinadns-ng我没意见，因为我也在用chinadns-ng。
但请在设置为：本地DNS(UDP)【自定义】的时候不要启动chinadns-ng，因为那样我就没法使用自己的配置启动chinadns-ng了。以前版本的行为是这种设置下不会启动chinadns-ng的。
因为我采用的方案是
chinadns-ng->smartdns china port
          L->smartdns us  port
并没用到passwall提供的DNS方案。

**Comment by xiaorouji** [comment]
> > 见4-13
> > 用了好几天，应该没有什么大问题。
> 
> chinadns-ng选项都不显示了,确定有安装chinadns-ng,
> 目前最大的问题就是中国列表外模式,除了gfwlist,其他国外网站的DNS解析结果都是离本地最近的, 国外网站既然走了代理,那DNS结果也应该是离代理最近的CDN才对, 也不是非得用chinadns-ng, 不过chinadns-ng是实现这个需求的一个现成且简单的解决方案.
> 我前面的图应该说的很清楚了, 同一个域名,开不开chinadns-ng,得到的IP完全不一样.

自适应启动

**Comment by xiaorouji** [comment]
> 默认使用chinadns-ng我没意见，因为我也在用chinadns-ng。
> 但请在设置为：本地DNS(UDP)【自定义】的时候不要启动chinadns-ng，因为那样我就没法使用自己的配置启动chinadns-ng了。以前版本的行为是这种设置下不会启动chinadns-ng的。
> 因为我采用的方案是
> chinadns-ng->smartdns china port
> L->smartdns us port
> 并没用到passwall提供的DNS方案。

https://github.com/xiaorouji/openwrt-passwall/commit/f399e4891bc6ccdacf1554b2e5d77b2a352334e9

**Comment by WYC-2020** [comment]
4.12这版本用起来没啥问题，我就是ng+smart，中国列表外，现在很多人都是流量过剩，根本就不会在乎防火墙模式还是中国列表外，防火墙这个模式基本没啥用了

**Comment by lededev** [comment]
> 4.12这版本用起来没啥问题，我就是ng+smart，中国列表外，现在很多人都是流量过剩，根本就不会在乎防火墙模式还是中国列表外，防火墙这个模式基本没啥用了

我觉得适当的外网非GFW网站直连名单，应该更有必要一点。这样可以让用户的出国TCP连接显得比较丰富，可以一定程度上掩护出国TLS代理服务器。要是只对单个国外IP产生大量流量，就太明显了。

**Comment by garypang13** [comment]
> > > 见4-13
> > > 用了好几天，应该没有什么大问题。
> > 
> > 
> > chinadns-ng选项都不显示了,确定有安装chinadns-ng,
> > 目前最大的问题就是中国列表外模式,除了gfwlist,其他国外网站的DNS解析结果都是离本地最近的, 国外网站既然走了代理,那DNS结果也应该是离代理最近的CDN才对, 也不是非得用chinadns-ng, 不过chinadns-ng是实现这个需求的一个现成且简单的解决方案.
> > 我前面的图应该说的很清楚了, 同一个域名,开不开chinadns-ng,得到的IP完全不一样.
> 
> 自适应启动

可以了,建议将Makefile中 chinadns-ng 的 default n 改为 y 大部分人并不知道chinadns-ng具体的用处.
