### ISSUE TITLE
157a90d 编译失败

### ISSUE THREAD

**Issue by exLuLu** [xiaorouji/openwrt-passwall#919]
Configuring xray-core.
Configuring luci-app-passwall.
Collected errors:
 * check_data_file_clashes: Package xray wants to install file /home/aaa/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/xray
	But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
 * check_data_file_clashes: Package xray wants to install file /home/aaa/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/xray
	But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package xray.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/aaa/lede'
package/Makefile:108: recipe for target '/home/aaa/lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/aaa/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/aaa/lede'
/home/aaa/lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by xiaorouji** [comment]
缝合怪...可以关了

**Comment by exLuLu** [comment]
用 b0756f9 这个就没有问题，你是大佬你厉害，但不要出口就缝合怪，比你厉害的人多的是

**Comment by jh0072110** [comment]
> 用 [b0756f9](https://github.com/xiaorouji/openwrt-passwall/commit/b0756f9b2c479397b971762d9c420ca02c14f332) 这个就没有问题，你是大佬你厉害，但不要出口就缝合怪，比你厉害的人多的是

话糙理不糙吧，俩插件单拎出来都没问题，你做mix做出问题了，那当然是你自己去解决问题咯…

**Comment by WYC-2020** [comment]
重复而已，有能力自己折腾就要时刻准备好已经解决，自己修改后的问题

**Comment by xiaorouji** [comment]
https://github.com/fw876/helloworld/commit/81579ea5db1297a3908e95c9f3b71d22f5c31e1f

**Comment by xylz0928** [comment]
我看到passwall, vssr, helloworld 这两天都更新了使用xray-core，但是编译时还是出现问题，想请问一下是不是所有删除其他包内的xray-core，只保留一个包里面的xray-core就行了？我今天试了一天也没试出来
