### ISSUE TITLE
Passwall 编译

### ISSUE THREAD

**Issue by jyy5206** [xiaorouji/openwrt-passwall#921]
半年前，我从 https://github.com/Lienol/openwrt 成功编译了 Passwall 给我的红米2100.
现在想更新下，发现 make menuconfig 里面找不到Passwall了。
连发 Issue 的地方都没有了。

请教这里的大侠们：
我现在该去哪里编译？

谢谢！

**Comment by xiaorouji** [comment]
git clone

**Comment by jyy5206** [comment]
> git clone

谢谢大侠回复！

按您指导，我尝试了以下2个方法，在 make menuconfig 里还是没找到 Pass wall。。。

方法1）
sudo apt-get update 
sudo apt-get -y install build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
git clone -b main --single-branch https://github.com/Lienol/openwrt openwrt
**git clone https://github.com/xiaorouji/openwrt-passwall**
cd openwrt
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig

方法2）
sudo apt-get update 
sudo apt-get -y install build-essential asciidoc binutils bzip2 curl gawk gettext git libncurses5-dev libz-dev patch python3.5 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf
git clone -b main --single-branch https://github.com/Lienol/openwrt openwrt
cd openwrt
**git clone https://github.com/xiaorouji/openwrt-passwall**
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig

本人非 IT 人士，只会依样画葫芦。。。
还望大侠拨冗指导下。
谢谢！

**Comment by xiaorouji** [comment]
修改 feeds.conf.default 文件
添加一行
`src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main`
保存然后
./scripts/feeds clean
./scripts/feeds update -a
./scripts/feeds install -a
make menuconfig

**Comment by jyy5206** [comment]
> 修改 feeds.conf.default 文件
> 添加一行
> `src-git passwall https://github.com/xiaorouji/openwrt-passwall.git;main`
> 保存然后
> ./scripts/feeds clean
> ./scripts/feeds update -a
> ./scripts/feeds install -a
> make menuconfig

现在 make menuconfig 里有 passwall 啦！
编译ing。。。

鞠躬致谢！

**Comment by jyy5206** [comment]
终于升级好了。
作为小白，累死我了。。。

这次红米 AC2100 升级 Passwall 固件，掉进了 4 个坑。特别是头2个坑。

1）原厂固件时，刷机前先不要联网。（特别是不要长时间联网）
我先把路由器刷回了原厂，打算第二天再刷机。联网过了一夜。
结果第二天死活卡在了 telnet 上。
后来发现红米路由器半夜偷偷的在后台自动把固件升级了。
升级后的新固件不支持 telnet 刷机了。
手动降级后才成功。
能刷机的老固件： https://lanzous.com/icgst5a 

2）原有的底包和2天前编译的最新固件不兼容。
兼容的新底包：https://pan.baidu.com/s/1W1SK_OOlFXNgPU8l5L8pVQ
提取码: c9pv
其中文件名中带有redmi字样的是红米的。

3）老固件的存档配置和新固件不兼容。
需要重新配置所有设定。特别是新固件没有了V2ray，只有Xray了。
节点里所有用V2ray的节点设定全乱了，需要一一手动改为Xray。
我一开始以为一样，直接把老固件配置存档直接恢复，结果变砖了。
只好从breed开始从头来过。

4）新固件Wifi的2.4G和5G都“未关联”。
国家改为US后好了。
但是5G只能开到80MHz。切换到160MHz后就没信号了。

汇报给大家共勉参考。

顺祝大家春节愉快！

再次感谢 @xiaorouji 的指导！
