### ISSUE TITLE
xray编译出现问题

### ISSUE THREAD

**Issue by aasunaa** [xiaorouji/openwrt-passwall#922]
Collected errors:
 * check_data_file_clashes: Package xray-core wants to install file /home/asu/openwrt19/build_dir/target-x86_64_musl/root-x86/usr/bin/xray
        But that file is already provided by package  * xray
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * check_data_file_clashes: Package xray-core wants to install file /home/asu/openwrt19/build_dir/target-x86_64_musl/root-x86/usr/bin/xray
        But that file is already provided by package  * xray
 * opkg_install_cmd: Cannot install package xray-core.
 * 
 * 似乎是xray-core起冲突导致编译失败，望修复

**Comment by xiaorouji** [comment]
......又来

**Comment by xiaorouji** [comment]
我看ssrplus也跟上更新了
https://github.com/fw876/helloworld/commit/81579ea5db1297a3908e95c9f3b71d22f5c31e1f
你可能需要更新源码
