### ISSUE TITLE
2021-02-04编译出错

### ISSUE THREAD

**Issue by e703** [xiaorouji/openwrt-passwall#923]
之前软路由使用的是openclash，现在已经全部删除了；make clean也使用过了。扶墙的工具就剩passwall了。现在编译依旧出错。
Configuring luci-i18n-nlbwmon-zh-cn.
Collected errors:
 * check_data_file_clashes: Package v2ray wants to install file /home/aka/lean-lede/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
        But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package v2ray.
package/Makefile:65: recipe for target 'package/install' failed
make[2]: *** [package/install] Error 255
make[2]: Leaving directory '/home/aka/lean-lede'
package/Makefile:108: recipe for target '/home/aka/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_install' failed
make[1]: *** [/home/aka/lean-lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/aka/lean-lede'
/home/aka/lean-lede/include/toplevel.mk:222: recipe for target 'world' failed
make: *** [world] Error 2

**Comment by snakwu** [comment]
xray已改名为xray-coer，删除重新clone

**Comment by viagram** [comment]
你应该是用github action编译，重新生成.config就OK

**Comment by e703** [comment]
本地安装的乌班图Server 版本；.config文件中查找了也没有openclash的内容。

**Comment by xiaorouji** [comment]
固件源码 插件源码都已经更新到最新了嘛？

**Comment by e703** [comment]
都更新到最新了，只要git pull了passwall的就会报错，哪怕是之后重建.config也是这样；晚点打算重新部署下编译环境：ubuntu-18.04.5-live-server-amd64.iso,只添加大雕的源码和passwall再看看。估计02:00有结果。感谢百忙中抽出时间回复。

**Comment by e703** [comment]
BTW：只是更新passwall之后会出错，其他插件和固件的源码更新后编译正常。

**Comment by LittleNewton** [comment]
我今天也是编译出错。

配置如下：

Target: WRT1900AC v2 路由器，马牌的 CPU，应该是比较少见。
[路由器详情](https://openwrt.org/toh/hwdata/linksys/linksys_wrt1900ac_v2)

Clone 了官方的最新版本 OpenWRT 仓库，非 Lean 的仓库。然后在 `package/` 下面建立了一个文件夹，在该文件夹里 `git clone` 了本 passwall 的源代码。

`make menuconfig` 成功扫描到了 Makefile，并识别到了 Passwall.

然后无脑编译，但是提示找不到 Trojan-go 的某些编译产物。目前正在重新编译，希望大佬能指点一下。

**Comment by e703** [comment]
现在软路由上固件环境：

Intel(R) Celeron(R) CPU J1900 @ 1.99GHz : 4 Core 4 Thread (CpuMark : 26251.416980 Scores)
固件版本：OpenWrt R21.2.1 / LuCI Master (git-20.343.54716-6fc079f)
内核版本：5.4.92
passwall版本：luci-app-passwall | 4-12
现在版本在我这儿的问题：
1.隔一段时间就会出现DNS服务除了软路由自己，其他局域网无法获取DNS。
   之前的解决方法是没4小时使用命令重启passwall服务。service passwall restart；
   2月1日升级新的固件后。service passwall restart不能正常工作。出现假死。只能通过网页再次重启passwall服务。
  今天看到又有更新，所以升级下看看，结果如上。

**Comment by e703** [comment]
Trojan-go 的某些编译产物，一般是Go语言的问题。参考：[https://github.com/p4gefau1t/trojan-go/issues/217](url)

**Comment by RookieZoe** [comment]
我这也报错

部分日志：

```
...
 * check_data_file_clashes: Package v2ray wants to install file /home/runner/work/openwrt-builder/openwrt-builder/openwrt/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
	But that file is already provided by package  * xray-core
 * opkg_install_cmd: Cannot install package v2ray.
 * resolve_conffiles: Existing conffile /home/runner/work/openwrt-builder/openwrt-builder/openwrt/build_dir/target-x86_64_musl/root-x86/etc/ppp/options is different from the conffile in the new package. The new conffile will be placed at /home/runner/work/openwrt-builder/openwrt-builder/openwrt/build_dir/target-x86_64_musl/root-x86/etc/ppp/options-opkg.
make[2]: *** [package/install] Error 255
make[1]: *** [/home/runner/work/openwrt-builder/openwrt-builder/openwrt/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
package/Makefile:65: recipe for target 'package/install' failed
...
```

config 配置在 [这边](https://github.com/RookieZoe/openwrt-builder/blob/main/openwrt-19.07-x86_64_no-samba.config)

**Comment by MGBB** [comment]
删除源码中的v2ray 就可以解决如果用的coolsnowwolf的lede源码删除package/lean下的v2ray

**Comment by e703** [comment]
删除也还是编译失败，报错信息都没变

**Comment by e703** [comment]
感谢MGBB的提醒，仔细检查了下源码的文件夹，我的是一直在用的编译环境；只是每次编译前回用git pull更新下源码；查找package目录下包含v2ray 的文件；发现lean目录和passwall的目录下都有。应该是之前的源码的残留。手动删除后编译正常。

**Comment by RookieZoe** [comment]
> 删除源码中的v2ray 就可以解决如果用的coolsnowwolf的lede源码删除package/lean下的v2ray

Works for me:

``` bash
...
cd openwrt/
./scripts/feeds update -a
rm -rf ./feeds/diy1/v2ray
./scripts/feeds install -a
...
```
