### ISSUE TITLE
luci-app-passwall 4-12 编译成安装包安装的时候最后会卡住。。。

### ISSUE THREAD

**Issue by hathlife** [xiaorouji/openwrt-passwall#928]
如图所示，不知道为啥会卡在这个地方，但是Ctrl+C强行终止以后功能还是正常的
不知道是不是老的config文件不支持
![image](https://user-images.githubusercontent.com/19867269/107004421-375f1e00-67c9-11eb-81e7-1994ecea913d.png)

**Comment by xiaorouji** [comment]
see https://github.com/xiaorouji/openwrt-passwall/commit/8ab146dfcb114b2b249cae26a3c5644d30692d1b
