### ISSUE TITLE
规则更新失败，今天上午的编译的.

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall#929]
![image](https://user-images.githubusercontent.com/59167936/107006672-7773d000-67cc-11eb-827c-2f6b5d3cecaf.png)
![image](https://user-images.githubusercontent.com/59167936/107006695-8195ce80-67cc-11eb-8952-a5faf9384981.png)

**Comment by xiaorouji** [comment]
网络问题

**Comment by yunxi993** [comment]
> 网络问题
我墙内、墙外都是正常啊，网站都是正常访问.

**Comment by msn1983aa** [comment]
遇到了同样的问题。不论是3.x还是4.x版本
路由器自身tcp和udp都使用全局代理，已确保节点正常
