### ISSUE TITLE
在openwrt官方仓库中集成插件并编译时提示不兼容架构

### ISSUE THREAD

**Issue by JKSTAFF** [xiaorouji/openwrt-passwall#932]
```
（前略）
Configuring xray-core.
Collected errors:
 * pkg_hash_fetch_best_installation_candidate: Packages for luci-app-passwall found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package luci-app-passwall.
make[2]: *** [package/Makefile:69: package/install] Error 255

```
目标适配设备：Newifi D1（MT7621）  
该问题出现于将paasswall的luci插件置于openwrt官方仓库的master分支进行集成了固件编译时  
xray-core为openwrt官方包含的版本（Categories:network）而非本项目代码仓库中的版本  
luci-app-passwall为本项目main分支  
.config文件中加了一行`CONFIG_KERNEL_MIPS_FP_SUPPORT=y`提供软件模拟浮点的能力  
希望能得到大家的建议，非常感谢

**Comment by xiaorouji** [comment]
架构不兼容？

**Comment by JKSTAFF** [comment]
> 架构不兼容？

是的，我的.config文件中加了一行`CONFIG_KERNEL_MIPS_FP_SUPPORT=y`为固件提供FPU浮点模拟的能力，除此之外应该就只有使用的xray-core不是您仓库那个这么一个区别了。不知道是否是这个的影响

**Comment by lededev** [comment]
不用改那行.config做软件模拟。
把你的build_dir/target_mipsel*目录删了重新全部重新编译。因为我的x86_64也遇到同样问题了，删target_x86_64*重新编译就通过了。

**Comment by JKSTAFF** [comment]
> 不用改那行.config做软件模拟。
> 把你的build_dir/target_mipsel_目录删了重新全部重新编译。因为我的x86_64也遇到同样问题了，删target_x86_64_重新编译就通过了。

这几天一直在重复clean拉取编译不兼容

**Comment by MrMatttw** [comment]
网件wndr4300v1在Debian中编译适用19.07原版ooenwrt也提示架构不兼容

**Comment by w931018h** [comment]
相同问题
