### ISSUE TITLE
没有延时启动后感觉会跟adbyby冲突

### ISSUE THREAD

**Issue by TwoBall** [xiaorouji/openwrt-passwall#933]
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables v1.8.4 (legacy): Couldn't load target `PSW_OUTPUT':No such file or directory
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall:
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Try `iptables -h' or 'iptables --help' for more information.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables v1.8.4 (legacy): Couldn't load target `PSW':No such file or directory
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall:
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Try `iptables -h' or 'iptables --help' for more information.
Fri Feb  5 22:31:10 2021 cron.err crond[3569]: crond (busybox 1.31.1) started, log level 5
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables v1.8.4 (legacy): Couldn't load target `PSW':No such file or directory
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall:
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Try `iptables -h' or 'iptables --help' for more information.
Fri Feb  5 22:31:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.
Fri Feb  5 22:31:11 2021 daemon.notice procd: /etc/rc.d/S99passwall: iptables: No chain/target/match by that name.

貌似是和adbyby冲突了，原来有延迟启动，现在没有找到选项

**Comment by tritu** [comment]
Sun Feb  7 13:07:10 2021 daemon.notice procd: /etc/rc.d/S99passwall: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Sun Feb  7 13:07:35 2021 daemon.crit dnsmasq[3184]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:07:35 2021 daemon.crit dnsmasq[3184]: FAILED to start up
Sun Feb  7 13:07:40 2021 daemon.crit dnsmasq[3387]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:07:40 2021 daemon.crit dnsmasq[3387]: FAILED to start up
Sun Feb  7 13:07:45 2021 daemon.crit dnsmasq[3431]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:07:45 2021 daemon.crit dnsmasq[3431]: FAILED to start up
Sun Feb  7 13:07:50 2021 daemon.crit dnsmasq[3456]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:07:50 2021 daemon.crit dnsmasq[3456]: FAILED to start up
Sun Feb  7 13:07:55 2021 daemon.crit dnsmasq[3528]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:07:55 2021 daemon.crit dnsmasq[3528]: FAILED to start up
Sun Feb  7 13:08:00 2021 daemon.crit dnsmasq[3572]: bad option at line 3 of /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
Sun Feb  7 13:08:00 2021 daemon.crit dnsmasq[3572]: FAILED to start up
Sun Feb  7 13:08:00 2021 daemon.info procd: Instance dnsmasq::cfg01411c s in a crash loop 6 crashes, 0 seconds since last crash


cat  /var/etc/dnsmasq-passwall.d/00-vpsiplist_host.conf
server=/.xxx.yyy.zzz/127.0.0.1#5053
server=/.xxx.yyy.zzz/127.0.0.1#5054
127.0.0.1#5053

**Comment by xiaorouji** [comment]
@tritu 检查一下你的dnsmasq的上游

**Comment by xiaorouji** [comment]
@TwoBall 有没有更新最新源码再试？

**Comment by TwoBall** [comment]
> @TwoBall 有没有更新最新源码再试？

正在编译测试。这个从日志看，就是有程序（adbyby）在修改iptables，而且出现这个日志时，passwall日志里的`发现 adbyby 规则链，adbyby 规则优先...`是没有的

**Comment by TwoBall** [comment]
> @TwoBall 有没有更新最新源码再试？
`新源码测试了，还是有相同日志，不过好像passwall会自动重启一次，开机后有两段启动日志，第一段没有发现 adbyby 规则链，adbyby 规则优先...`。第二段有。

**Comment by xiaorouji** [comment]
之前没去掉延时启动的时候正常吗？

**Comment by TwoBall** [comment]
> 之前没去掉延迟启动的时候正常吗？

记忆中是正常的，我来改一下app.sh测试下

**Comment by TwoBall** [comment]
@xiaorouji 我测试在app.sh前面加加了个sleep 5s貌似正常了。`[ "$ENABLED" == 1 ] && sleep 5s && start`

**Comment by xiaorouji** [comment]
回滚了 https://github.com/xiaorouji/openwrt-passwall/commit/dd55c04e36bc5d48dd68a74fa05de6ccd560673f

**Comment by tritu** [comment]
> @tritu 检查一下你的dnsmasq的上游

fix in [https://github.com/xiaorouji/openwrt-passwall/pull/947](url)
