### ISSUE TITLE
编译到官方固件v19.07.6每次都是xray-core报错

### ISSUE THREAD

**Issue by Gx3dong** [xiaorouji/openwrt-passwall#934]
Makefile:106: recipe for target '/home/gx3dong/openwrt/build_dir/target-x86_64_musl/Xray-core-1.2.4/.built' failed
make[3]: *** [/home/gx3dong/openwrt/build_dir/target-x86_64_musl/Xray-core-1.2.4/.built] Error 1
make[3]: Leaving directory '/home/gx3dong/openwrt/package/openwrt-passwall/xray-core'
time: package/openwrt-passwall/xray-core/compile#0.12#0.05#84.25
package/Makefile:111: recipe for target 'package/openwrt-passwall/xray-core/compile' failed
make[2]: *** [package/openwrt-passwall/xray-core/compile] Error 2
make[2]: Leaving directory '/home/gx3dong/openwrt'
package/Makefile:107: recipe for target '/home/gx3dong/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
make[1]: *** [/home/gx3dong/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
make[1]: Leaving directory '/home/gx3dong/openwrt'
/home/gx3dong/openwrt/include/toplevel.mk:225: recipe for target 'world' failed
make: *** [world] Error 2

都已经更新到最新的了    

求大神指点下，谢谢

**Comment by hcym** [comment]
master正常

**Comment by Gx3dong** [comment]
请问下 我该怎么解决呢

**Comment by hcym** [comment]
用master分支编译啊，因为树莓4，我一直都是这样，编译肯定没问题

**Comment by Gx3dong** [comment]
main   4-6   还有dev用哪一个呀   谢谢

**Comment by xiaorouji** [comment]
用官源，你可能需要解决：
1. UPX
2. Go版本
3. 锁
4. 等等

**Comment by Gx3dong** [comment]
谢谢，大神为我解惑，第一次搞openwrt搞了好几天，一直以为搞不好。 那我别的固件编译好，在把ipk安装到   openwrt v19.07.6   插件能兼容吗？会不会有什么影响

**Comment by xiaorouji** [comment]
如果你是新入坑的话，建议可以用lean lienol ctcgfw的源码编译，可以解决好多坑

**Comment by xiaorouji** [comment]
用官方源码你还需要把dnsmasq去掉，换成dnsmasq-full

**Comment by Gx3dong** [comment]
就是一天闲的慌  目前有在用的    就是想无聊编着玩  喜欢折腾， 哈哈

**Comment by Gx3dong** [comment]
多编编，碰到问题   解决了  就会多学到点

**Comment by ma20at** [comment]
> 用官方源码你还需要把dnsmasq去掉，换成dnsmasq-full

上一版本的主界面tcp和upd节点下面有奈飞等分流节点选项，这一版没有了，是取消了吗？

**Comment by xiaorouji** [comment]
@ma20at  没有，这个分流功能上一年就已经有了，支持所有类型，只不过还是好多人没有发现。。哎。
要先去节点列表手动添加一个节点，选择xray，然后协议选择分流，然后就应该知道怎样做了吧？
然后在主页面选择这个节点后，也可以快速编辑。

**Comment by Gx3dong** [comment]
passwall已经添加编译到官方v19.07.6了，嘿嘿，谢谢，大神，给的启发

**Comment by hathlife** [comment]
> 用官源，你可能需要解决：
> 
> 1. UPX
> 2. Go版本
> 3. 锁
> 4. 等等

还有kcptun的依赖要处理一下

**Comment by ma20at** [comment]
> @ma20at 没有，这个分流功能上一年就已经有了，支持所有类型，只不过还是好多人没有发现。。哎。
> 要先去节点列表手动添加一个节点，选择xray，然后协议选择分流，然后就应该知道怎样做了吧？
> 然后在主页面选择这个节点后，也可以快速编辑。
节点菜单下设置分流那个我知道一直都有，我是说在基本设置主界面的主开关下面的tcp和udp节点选择菜单，我之前看到下面还有奈飞等单独选择节点的菜单，昨天git pull重编译固件更新后那几个子菜单不见了。。。

**Comment by xiaorouji** [comment]
> > @ma20at 没有，这个分流功能上一年就已经有了，支持所有类型，只不过还是好多人没有发现。。哎。
> > 要先去节点列表手动添加一个节点，选择xray，然后协议选择分流，然后就应该知道怎样做了吧？
> > 然后在主页面选择这个节点后，也可以快速编辑。
> > 节点菜单下设置分流那个我知道一直都有，我是说在基本设置主界面的主开关下面的tcp和udp节点选择菜单，我之前看到下面还有奈飞等单独选择节点的菜单，昨天git pull重编译固件更新后那几个子菜单不见了。。。

你要TCP节点选择 分流 节点 才会显示出来

**Comment by whave** [comment]
> passwall已经添加编译到官方v19.07.6了，嘿嘿，谢谢，大神，给的启发

请问问题解决了吗？是怎么解决的啊，我也遇到了这个文件。

**Comment by huanxianggu** [comment]
我也是同样问题，搞不定
