### ISSUE TITLE
DNS默认（使用ISP DNS）时无法上网

### ISSUE THREAD

**Issue by leochien0102** [xiaorouji/openwrt-passwall#935]
PULL代码后编译并更新固件，发现原来配置的使用默认DNS即ISP DNS时，无法上网，需选用公共DNS才可以
日志中看到将ISP DNS加到例外里了，但实际无法上网

> 2021-02-06 19:16:22: 删除相关防火墙规则完成。
> 2021-02-06 19:16:24: 重启 dnsmasq 服务[0]
> 2021-02-06 19:16:24: 清空并关闭相关程序和缓存完成。
> 2021-02-06 19:16:24: TCP节点：XXXXXXXXX，节点：XXXXXXXXXXXXXXXXXX，监听端口：1041
> 2021-02-06 19:16:24: 过滤服务配置：准备接管域名解析[0]...
> 2021-02-06 19:16:24:   + [0]Pdnsd (127.0.0.1:7913)...
> 2021-02-06 19:16:24:   | - [0]上游DNS：8.8.8.8:53
> 2021-02-06 19:16:24:   - 域名解析：pdnsd + 使用(TCP节点)解析域名...
> 2021-02-06 19:16:24:   * 请确认上游 DNS 支持 TCP 查询，如非直连地址，确保 TCP 代理打开，并且已经正确转发！
> 2021-02-06 19:16:24:   - [0]节点列表中的域名(vpsiplist)：127.0.0.1#5053,127.0.0.1#5054
> 127.0.0.1#5053,127.0.0.1#5054
> 2021-02-06 19:16:24:   - [0]域名白名单(whitelist)：127.0.0.1#5053,127.0.0.1#5054
> 127.0.0.1#5053,127.0.0.1#5054
> 2021-02-06 19:16:24:   - [0]代理域名表(blacklist)：127.0.0.1#7913
> 2021-02-06 19:16:24:   - [0]防火墙域名表(gfwlist)：127.0.0.1#7913
> 2021-02-06 19:16:24:   - 不强制设置默认DNS
> 2021-02-06 19:16:24: 开始加载防火墙规则...
> 2021-02-06 19:16:25: 本机网段互访直连：10.0.0.254/24
> 2021-02-06 19:16:25: 处理 ISP DNS 例外...
> 2021-02-06 19:16:25:   - 追加到白名单：116.228.111.18
> 2021-02-06 19:16:25:   - 追加到白名单：180.168.255.118
> 2021-02-06 19:16:25: 加入所有节点到ipset[vpsiplist]直连完成
> 2021-02-06 19:16:25: 加入负载均衡的节点到ipset[vpsiplist]直连完成
> 2021-02-06 19:16:25: 加载路由器自身 TCP 代理...
> 2021-02-06 19:16:25:   - [1]将上游 DNS 服务器 8.8.8.8:53 加入到路由器自身代理的 TCP 转发链2
> 2021-02-06 19:16:25: 使用链表 PREROUTING 排列索引4[0]
> 2021-02-06 19:16:25: TCP默认代理：使用TCP节点 [中国列表以外](REDIRECT:1041)代理所有端口
> 2021-02-06 19:16:25: 防火墙规则加载完成！
> 2021-02-06 19:16:28: 重启 dnsmasq 服务[0]
> 2021-02-06 19:16:28: 运行完成！

**Comment by hplee0120** [comment]
排查一下这个https dns proxy的127.0.0.1#5053和127.0.0.1#5054是怎么回事吧，你看看你dnsmasq上游是不是被这个接管了。

**Comment by leochien0102** [comment]
> 排查一下这个https dns proxy的127.0.0.1#5053和127.0.0.1#5054是怎么回事吧，你看看你dnsmasq上游是不是被这个接管了。

OK，发现的确是这个问题，也不记得是哪个东西配的这个（我自己绝对没动过这个）

**Comment by tritu** [comment]
fix in https://github.com/xiaorouji/openwrt-passwall/pull/947#issue-569970092
