### ISSUE TITLE
订阅、导入、导出还不支持XRay vless:// 格式

### ISSUE THREAD

**Issue by lededev** [xiaorouji/openwrt-passwall#937]
不支持vless://导致自动订阅时丢失vless类型的站点。
vless未编码示例URL(TLS/XTLS direct)：
`vless://44444444-dddd-5555-6666-777788889999@aaa.bbb.com:443?security=tls&encryption=none&host=aaa.bbb.com&headerType=none&type=tcp#aaa.bbb.com_VLESS_XTLS/TLS-direct_TCP`

**Comment by xiaorouji** [comment]
vless的分享链接格式 是否已经出标准？

**Comment by lededev** [comment]
这个就得问作者了 @rprx

**Comment by dwj0** [comment]
ssr-plus 已经支持vless 了

**Comment by xiaorouji** [comment]
已经初步支持，请更新源码，还需更多的测试和反馈。
