### ISSUE TITLE
刚刚编译新版passwall报错，But that file is already provided by package  * v2ray

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-passwall#938]
Collected errors:
 * check_data_file_clashes: Package xray-core wants to install file /home/openwrt/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
	But that file is already provided by package  * v2ray
 * opkg_install_cmd: Cannot install package luci-app-passwall.
 * check_data_file_clashes: Package xray-core wants to install file /home/openwrt/lede/build_dir/target-x86_64_musl/root-x86/usr/bin/v2ray
	But that file is already provided by package  * v2ray
 * opkg_install_cmd: Cannot install package xray-core.
make[2]: *** [package/Makefile:68: package/install] Error 255
make[2]: Leaving directory '/home/openwrt/lede'
make[1]: *** [package/Makefile:108: /home/openwrt/lede/staging_dir/target-x86_64_musl/stamp/.package_install] Error 2
make[1]: Leaving directory '/home/openwrt/lede'
make: *** [/home/openwrt/lede/include/toplevel.mk:224：world] 错误 2

**Comment by xiaorouji** [comment]
把v2ray包删了
