### ISSUE TITLE
希望在XRay的协议中加入一个Blackhole，方便分流屏蔽列表

### ISSUE THREAD

**Issue by 70599** [xiaorouji/openwrt-passwall#939]
![这里加个黑洞.png](https://i.loli.net/2021/02/07/cUmb6jyYReLh7WV.png)

**Comment by BGzErol** [comment]
自己随便手打个不通的节点然后分流选上就行

**Comment by xiaorouji** [comment]
反正睡不着，满足一下你的需求。更新最新源码即可。https://github.com/xiaorouji/openwrt-passwall/commit/f92c3e4b24af9c055deb2ef6ead3fef60921ece6
![image](https://user-images.githubusercontent.com/60100640/107161551-5b447e80-69d8-11eb-824b-ef3be12e891f.png)

**Comment by doegeenon** [comment]
> 反正睡不着，满足一下你的需求。更新最新源码即可。[f92c3e4](https://github.com/xiaorouji/openwrt-passwall/commit/f92c3e4b24af9c055deb2ef6ead3fef60921ece6)
> ![image](https://user-images.githubusercontent.com/60100640/107161551-5b447e80-69d8-11eb-824b-ef3be12e891f.png)

就是说我现在可以开TCP全局模式然后用分流做白名单模式和广告过滤（blackhole geosite:ads啥啥啥）了？

**Comment by xiaorouji** [comment]
@doegeenon 是的，你可以测试下，有问题可以来反馈

**Comment by doegeenon** [comment]
> @doegeenon 是的，你可以测试下，有问题可以来反馈  

太赞了，那大佬后续会考虑加入更新geoip.dat和geosite.dat的方法吗？类似更新gfwlist那样。

**Comment by xiaorouji** [comment]
@doegeenon  这个是支持的，只要你/usr/share/xray目录下有geosite或geoip就可以。这个也可以在编译固件的时候，勾选上一同编译

**Comment by xiaorouji** [comment]
@doegeenon  以后会加上的

**Comment by 70599** [comment]
编译完用上了，标题需求已满足，感谢迅速对应！

**Comment by 70599** [comment]
开全局靠XRay分流直连还不行。
推测原因应该是DNS分流走的是另一套规则。
开全局后，所有的DNS解析都走了“过滤模式”里的DNS服务器。
我这里的结果是国内网站全部打不开了。

**Comment by hcym** [comment]
嗯，用这个源码不能用dsnmasq去广告，可能机制比较暴力，😹

**Comment by xiaorouji** [comment]
@70599 还需要调优一下逻辑

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/107411268-4dfad180-6b49-11eb-85a1-eb1fce2fcc27.png)
![image](https://user-images.githubusercontent.com/60100640/107411291-54894900-6b49-11eb-950e-3c1ce5059b7b.png)
已经可以愉快的玩耍了

**Comment by 70599** [comment]
已确认。感谢🙏

**Comment by 70599** [comment]
代理模式设置为全局时，zerotier就不能用了。
尝试用以下规则return，没有效果。
```sh
iptables -t nat -I PSW -i zt3jn4igbl -j RETURN
iptables -t mangle -I PSW -i zt3jn4igbl -j RETURN
iptables -t nat -I PSW -d 10.144.50.0/24 -j RETURN
iptables -t mangle -I PSW -d 10.144.50.0/24 -j RETURN
```
