### ISSUE TITLE
最新源码，好像出现BUG了

### ISSUE THREAD

**Issue by lllrrr2** [xiaorouji/openwrt-passwall#943]
今天早上更新编译的，发现切换节点后，日志显示切换成功了，但实际还是上次的节点，ip111.cn显示出还是上次的节点IP.只有重启路由器后，才会真正的切换

**Comment by lllrrr2** [comment]
前天的版本正常

**Comment by lllrrr2** [comment]
总开关，关掉passwall后，日志也提示成功了，但实际上，还是在代理。

**Comment by xiaorouji** [comment]
是有一个BUG，DNS使用TCP节点的Socks查询时自动切换时，socks没有换过去

**Comment by lllrrr2** [comment]
更新最新源码，编译了一下，切换节点好像还是不成功。一直是用的第一次使用的节点

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/107206155-a2169080-6a39-11eb-88bd-ab7719a3b9dc.png)
以这个为标准

**Comment by lllrrr2** [comment]
切换节点，提示成功。实际没变，可能是原来的进程还在，所以还是上次的节点代理，重启路由后，就切换成功了。
