### ISSUE TITLE
passwall的monitor似乎无效

### ISSUE THREAD

**Issue by BGzErol** [xiaorouji/openwrt-passwall#944]
我在op的进程管理那手动强制关闭chinadns-ng后等待进三分钟了passwall仍未自动重启，不知道怎么回事

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall/commit/41b3316ae1df4e841f9fbbd7afdcdae24dfb0ba8

**Comment by BGzErol** [comment]
> [41b3316](https://github.com/xiaorouji/openwrt-passwall/commit/41b3316ae1df4e841f9fbbd7afdcdae24dfb0ba8)

👌
