### ISSUE TITLE
My TCP Server is not running

### ISSUE THREAD

**Issue by xenstar** [xiaorouji/openwrt-passwall#945]
Hello, I am doing this setting in passwall, but my TCP Server doesn't run. I am not sure where I am making the mistake. I have attached the screenshot of my setting. 

<img width="821" alt="screen2" src="https://user-images.githubusercontent.com/55502651/107196070-1a2a8980-6a2d-11eb-9ac9-5e7e77886d2e.png">
<img width="698" alt="screeen3" src="https://user-images.githubusercontent.com/55502651/107196108-2a426900-6a2d-11eb-9fe2-e61b216b9fc2.png">
<img width="681" alt="screen4" src="https://user-images.githubusercontent.com/55502651/107196042-11d24e80-6a2d-11eb-9fa1-3d385dffbef7.png">

**Comment by xiaorouji** [comment]
please watch log

**Comment by xenstar** [comment]
> please watch log

Can you find anything? 

<img width="521" alt="log1" src="https://user-images.githubusercontent.com/55502651/107200986-61b41400-6a33-11eb-9101-a69ee0572dcb.png">

**Comment by lllrrr2** [comment]
我也发现有这个问题，刚才更新源码，编译出来的

**Comment by lllrrr2** [comment]
![image](https://user-images.githubusercontent.com/61368564/107205815-3cc29f80-6a39-11eb-83fe-ec636765b542.png)

**Comment by xiaorouji** [comment]
You can check the node log.
![image](https://user-images.githubusercontent.com/60100640/107207448-464d0700-6a3b-11eb-8e77-fc5d85c546e4.png)

**Comment by monokoo** [comment]
同样的问题，后台进程多出来很多，貌似重启应用时相关进程都没有杀掉

**Comment by lllrrr2** [comment]
![image](https://user-images.githubusercontent.com/61368564/107220513-61287700-6a4d-11eb-926f-4d53640065d1.png)

**Comment by lllrrr2** [comment]
![image](https://user-images.githubusercontent.com/61368564/107220589-7c938200-6a4d-11eb-8833-be84948d44aa.png)
这个重启路由后，竟然有二组一样的

**Comment by lllrrr2** [comment]
上图只是截图了一组

**Comment by lllrrr2** [comment]
切换节点后，也会跑出二组
![image](https://user-images.githubusercontent.com/61368564/107220876-d6944780-6a4d-11eb-8e60-1fc7080d95ba.png)

**Comment by xiaorouji** [comment]
这...我似乎无法复现，方便把配置文件发我邮箱给我测试？

**Comment by lllrrr2** [comment]
我什么都没配置就加了二个节点。全是默认值。不过我好像找到原因了。出现TCP没运行是因为编译的时候选了procps-ng这个包。他的命令好像和PS不同。我又编译了一个版本，没选这个包，就正常了。大雕的源码是默认就选了procps-ng,可能要改一下app.sh中的查进程的代码。

**Comment by lllrrr2** [comment]
procps-ng 包。ps命令就无效了，要加参数。
-ef ww

**Comment by xenstar** [comment]
<img width="487" alt="log 1" src="https://user-images.githubusercontent.com/55502651/107238045-5d531f80-6a62-11eb-9bea-d4176661993d.png">
<img width="510" alt="log 2" src="https://user-images.githubusercontent.com/55502651/107238070-63e19700-6a62-11eb-9799-0dc06f4a59dc.png">

There is no log recording, although I tried with a different option. which one should I select to get some log data first?

**Comment by xiaorouji** [comment]
![image](https://user-images.githubusercontent.com/60100640/107239709-19611a00-6a64-11eb-8973-9eba8d63e701.png)
Remove the checkbox.
Log level choose debug.

**Comment by xenstar** [comment]
PROT_EXEC|PROT_WRITE

**Comment by exLuLu** [comment]
既然有人开lssues我也就说一下，这个问题在我印象是从 优先用xray启动trojan节点 那次更新出现的，一直到现在。编译时只勾选了Xray、haproxy、ChinaDNS-NG和dns2socks，新装lede或者卸载重装passwall，添加自建VLESS节点（没试过其他类型节点，只有一台机器不想随便动），开启passwll，TCP必定不会运行，无论怎么改设置TCP都不会运行，而且TCP日志是完全空白的，然后我订阅机场运行一次trojan节点（我那个机场只有trojan节点）TCP便能成功运行，日志正常显示，然后再切换刚刚的自建VLESS节点，TCP也能运行，日志也能正常显示，之后怎么变，TCP都能运行起来。在我家里只要新装lede或者卸载重装passwall必定能复现，但是在我公司，却没有这个问题（同一个IMG分别转esxi和vmware），家里是电信的网络，装在esxi6.7，公司也是电信的网络，装在VMware Workstation16。你说是lede或者passwall的问题吧，在公司用就没有这种问题，你说是网络或者DNS或者节点或者设置的问题吧，只要把TCP搞开一次，那之后怎样搞，TCP也能运行起来。你说是偶然几率吧，在我家里必定能复现。

**Comment by lllrrr2** [comment]
这个问题我已经复现了，以前我的一直可以正常，但昨天我编译的时候选了procps-ng这个包后，只要启用passwall，我一直都是用trojan，在进程中就会出现二组进程，但代理可以上，只是切换节点无效，要重启路由以后才可以生效。但TCP那个图标显示是没启动的。大雕的lede源码默认就是有procps-ng这个包，我一直是用官源的。所以一直没有问题，直到昨天选了procps-ng这个包后才出现这个问题

**Comment by lllrrr2** [comment]
我编译了好多版本，只要选了procps-ng这个包就会出现问题。退出4.12 4.11也会

**Comment by xenstar** [comment]
I am using R2S, and I have installed this - https://github.com/soffchen/NanoPi-R2S (Passwall was already compiled)

So anyway, hopefully, the developer can find the solution and I can use passwall soon.

**Comment by monokoo** [comment]
开启socks主开关，并开启自动切换功能，后台会检测到大量重复的socks相关进程
类似
` 6844 root      1932 S    /var/etc/passwall/bin/ss-local -c /var/etc/passwall/v2_socks_044d6b9.json -b 127.0.0.1 -u -v
13525 root      1932 S    /var/etc/passwall/bin/ss-local -c /var/etc/passwall/v2_socks_044d6b9.json -b 127.0.0.1 -u -v
19886 root      1932 S    /var/etc/passwall/bin/ss-local -c /var/etc/passwall/v2_socks_044d6b9.json -b 127.0.0.1 -u -v
23360 root      1932 S    /var/etc/passwall/bin/ss-local -c /var/etc/passwall/v2_socks_044d6b9.json -b 127.0.0.1 -u -v`

**Comment by xiaorouji** [comment]
@monokoo 你是否使用了Xray的分流/负载均衡，然后分流的节点类型为非Xray类型，如SS。如果是的话是正常的，因为会利用Socks套娃。。。如果是进程无法杀掉的话，看看你的固件支不支持 `top -bn1` 命令，我之前把`ps -w` 全部改成`top -bn1`了。。。

**Comment by xiaorouji** [comment]
No reappearance.
