### ISSUE TITLE
4-13

### ISSUE THREAD

**Issue by yunxi993** [xiaorouji/openwrt-passwall#946]
现在chinadns-ng 与 chnlist 是自适应的吗？
还有分流里面的黑洞是什么意思?
直连是走默认节点的意思吗？
不懂 哈哈.

**Comment by xcyll** [comment]
chn-ng自适应启动（自定义dns除外）
黑洞是屏蔽
直连是代理的反义

**Comment by xiaorouji** [comment]
是的，当启动中国列表外模式会自动启动，如果过滤模式使用了自定义DNS将不会使用，但是可以使用pdnsd再转一下。
黑洞顾名思义就是黑洞，禁止访问
直连是不走代理（该功能可能尚未完善）
