### ISSUE TITLE
路由重启后仍无法代理

### ISSUE THREAD

**Issue by BGzErol** [xiaorouji/openwrt-passwall#949]
xray内核下使用vmess的节点，在路由器重启后passwall显示正在运行，但仍然无法翻墙，手动保存应用后才正常。若是xray下使用trojan则不会有这个问题，不清楚是core的问题还是passwall的问题_(:з」∠)_

**Comment by BGzErol** [comment]
刚刚又重新测试了，结果是trojan也同样的问题，日志中未发现异常
![EY }L5%YS %)01W8ALSK0I0](https://user-images.githubusercontent.com/61510455/107349262-f89bd180-6b02-11eb-9db9-832a5f7aebfd.png)

**Comment by WYC-2020** [comment]
我的不重启，长时间运行也会出现这个不能出国，感觉还是有问题，但是我自动切换是关闭了的，我是4.13版，年后来试下最新版看下

**Comment by BGzErol** [comment]
> 我的不重启，长时间运行也会出现这个不能出国，感觉还是有问题，但是我自动切换是关闭了的，我是4.13版，年后来试下最新版看下

我也试过最新源码，还是同样的问题

**Comment by BGzErol** [comment]
更新：刚刚测试发现软路由reboot重启后是正常的，但整个直接断电重启后，软路由本身正常代理，但通过tcp节点的日志可以看到passwall未收到任何来自客户端的代理请求，导致客户端无法被代理

**Comment by BGzErol** [comment]
但在软路由luci界面的reboot重启后有一小段时间会报错，日志如下
[TCP.log](https://github.com/xiaorouji/openwrt-passwall/files/5956055/TCP.log)

**Comment by BGzErol** [comment]
今早重新断电重启测试仍然有几率会这样，此时tcp节点日志除了xray start外便无其他日志，passwall自身的日志正常，ip111.cn中的国外测试和谷歌测试显示的是我宽带的ip_(:з」∠)_

**Comment by netwlb** [comment]
> 此时tcp节点日志除了xray start外便无其他日志，passwall自身的日志正常，ip111.cn中的国外测试和谷歌测试显示的是我宽带的ip_(:з」∠)_

一样问题，异常断电重启后，passwall的tcp代理失效，检测节点正常。有没有解决办法？
