### ISSUE TITLE
 使用此插件打开IPV6无法访问奈飞

### ISSUE THREAD

**Issue by MGBB** [xiaorouji/openwrt-passwall#951]
在开启IPV6后打开奈飞网页显示Not Available
  打开禁止解析 IPv6 DNS 记录 能正常访问奈飞， 是ipv6的问题。
  是奈飞网站检测到了国内IPV6导致的，禁止IPV6dns解析或者禁止netflix相关域名的ipv6 解析则正常访问，建议添加仅对代理域 
  禁用 IPv6查询。参考https://github.com/xiaorouji/openwrt-passwall/issues/688#issue-706476554

**Comment by ShanStone** [comment]
这个commit清空了proxy_host，https://github.com/xiaorouji/openwrt-passwall/commit/44888b418d09d3018f909ff490bbe2e340ecb3b1
你试试把netflix相关域名加回代理列表呢，我测试过加进去后解决了

**Comment by MGBB** [comment]
打开禁止解析 IPv6 DNS 记录  能正常访问是ipv6的问题

**Comment by ligbang** [comment]
我试了下，清空poxy_host 再加回代理列表，还是不行，还是Not Avilable

**Comment by aiastia** [comment]
我也是 Not Avilable
