### ISSUE TITLE
一闪而过的分流设置

### ISSUE THREAD

**Issue by hplee0120** [xiaorouji/openwrt-passwall#953]
虽然没有启用分流，但是点开插件后主页面会有一闪而过的分流设置然后恢复正常。不知道算不算bug。另外还是建议大佬开个频道什么的公布下更新说明啥的，最近频繁更新后修改了许多东西，有很多东西不知道逻辑和更改。玩法 功能性也不清楚。。。比如这个分流玩法还有增加的geoip。。

**Comment by hplee0120** [comment]
这个新加入的geoip 是否只针对启用了分流后的 直连规则进行匹配。默认不开启分流的话是否tcp节点还是启用大陆白名单的ip列表。另外如果启用分流后，自动切换的逻辑是不是需要自己手动添加分流1 分流2 分流3用来自动切换。感觉有点繁琐。不然的话如果分流的默认节点或者youtube节点发生断连它是怎么判断需要切换的，如果备用节点不是设置好的分流节点是不是会跳到单一的普通节点取消分流。感觉逻辑有点绕，不知道有啥好方案

**Comment by snakwu** [comment]
我同样也迷糊，这个分流的优先级，或者什么条件模式下生效

**Comment by xiaorouji** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/1005
