### ISSUE TITLE
关于chinadns-ng的逻辑

### ISSUE THREAD

**Issue by BGzErol** [xiaorouji/openwrt-passwall#956]
1.我revert掉**f399e48**这个commit后编译的passwall在用自定义dns也能启用chinadns-ng，但scp进入系统查看文件发现**chnlist是默认打开的**，而在**44888b4**这个commit中写着**只有在回国模式时才会使用chnlist**，但实际查看chinadns-ng的log发现大陆白名单模式下也使用了chnlist，所以想问问这是不是逻辑方面的bug
2.在上述所编译的passwall中，发现直连/代理名单管理中的条目**并非是合并在/var/etc/passwall/chnlist下和/var/etc/passwall/gfwlist.txt下**，**而是/var/etc/dnsmasq-passwall.d/中的00-proxy_host.conf和999-gfwlist.conf中**，chinadns-ng作为dnsmasq的上游，在这样的情况下应该是无法应对dns污染的（**因为解析会被同时发往国内dns与可信dns，例如github.io被污染，将github.io域名写入代理列表保存应用后解析出来的仍然是污染ip**）
我将passwall的源码fork过来后整个回退到**8ab146d**这个commit后编译出的passwall，可以手动开启chinadns-ng，**在此passwall下，直连/代理名单管理中的条目将被合并在/var/etc/passwall/chnlist下和/var/etc/passwall/gfwlist.txt下**而**不是/var/etc/dnsmasq-passwall.d/中**，并由chinadns-ng直接读取然后正常进行解析分流，**在此状态下chinadns-ng能与直连/代理名单管理功能完美结合**，在**未勾选使用chnlist的情况下/var/etc/passwall/chnlist条目为空**（直连/代理名单管理中直连列表会正常写入），开启后才会将chnlist本来的条目写入进去。我认为这样的逻辑才是最合理也是最简洁的，所以想恳请dalao再修缮下dns的逻辑

**Comment by BGzErol** [comment]
绝了，这github的文字加粗真不好用

**Comment by tournet** [comment]
也发现最近dns逻得相当不好用（取消china dns之后的版本）。

**Comment by WYC-2020** [comment]
确实刚看了 的确没有合并进去

**Comment by xiaorouji** [comment]
确认没有合并进去？会自动排序的

**Comment by WYC-2020** [comment]
搜索了几个确实没有
