### ISSUE TITLE
关于geoip、geosite的规则更新

### ISSUE THREAD

**Issue by SakuraFallingMad** [xiaorouji/openwrt-passwall#957]
先祝贺psw分流功能越来越好用，我这边提出个需要：在规则管理页面内，能够如同其他规则一样，给予geoip、geosite自定义设置更新url就更好了。
目前我在用[https://github.com/Loyalsoldier/v2ray-rules-dat](url)这位大佬的版本

**Comment by hcym** [comment]
这个完全没有必要吧，自己上传覆盖，自定义方便才是最重要的

**Comment by xiaorouji** [comment]
年后再做吧。

**Comment by xiaorouji** [comment]
已经有人PR了，已经合并。
