### ISSUE TITLE
关于在openwrt 1907编译passwall中，xray-core 部分go代码问题

### ISSUE THREAD

**Issue by Debbie-Yuan** [xiaorouji/openwrt-passwall#958]
**报错信息如下**：
`Building targets
github.com/xtls/xray-core/transport/internet/tls
github.com/xtls/go
\#github.com/xtls/xray-core/transport/internet/tls
../../transport/internet/tls/config.go:284:21: undefined: tls.CipherSuites
note: module requires Go 1.15
github.com/lucas-clemente/quic-go/internal/qtls
\# github.com/lucas-clemente/quic-go/internal/qtls
pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate
note: module requires Go 1.14
\# github.com/xtls/go
pkg/mod/github.com/xtls/go@v0.0.0-20201118062508-3632bf3b7499/auth.go:29:7: undefined: ecdsa.VerifyASN1
pkg/mod/github.com/xtls/go@v0.0.0-20201118062508-3632bf3b7499/key_schedule.go:177:16: xShared.FillBytes undefined (type *big.Int has no field or method FillBytes)

Cleaning module download cache (golang/go#27455)

make[3]: *** [Makefile:109: /home/parallels/Downloads/openwrt-openwrt-19.07/build_dir/target-mipsel_24kc_musl/Xray-core-1.2.4/.built] Error 2
make[3]: Leaving directory '/home/parallels/Downloads/openwrt-openwrt-19.07/package/self_aggragated_packages/openwrt-passwall/xray-core'
time: package/self_aggragated_packages/openwrt-passwall/xray-core/compile#5.22#2.77#18.59
make[2]: *** [package/Makefile:113: package/self_aggragated_packages/openwrt-passwall/xray-core/compile] Error 2
make[2]: *** Waiting for unfinished jobs....
go: extracting github.com/golang/protobuf v1.4.3

^Cmake[3]: *** [Makefile:77: /home/parallels/Downloads/openwrt-openwrt-19.07/build_dir/target-mipsel_24kc_musl/v2ray-plugin-1.8.0/.built] Interrupt
time: package/self_aggragated_packages/openwrt-passwall/v2ray-plugin/compile#0.15#0.04#1257.32
make[1]: *** [package/Makefile:107: /home/parallels/Downloads/openwrt-openwrt-19.07/staging_dir/target-mipsel_24kc_musl/stamp/.package_compile] Interrupt
make: *** [/home/parallels/Downloads/openwrt-openwrt-19.07/include/toplevel.mk:227: world] Interrupt`

**报错信息摘要**：

1. （../../transport/internet/tls/config.go:284:21）.undefined: tls.CipherSuites
2. （internal/qtls/qtls.go:79:25）. cannot convert cert (type *tls.Certificate) to type *qtls.Certificate
3. （key_schedule.go:177:16）.xShared.FillBytes undefined

**初步尝试&系统信息**
系统：ubuntu20.04 
尝试了go1.14，1.14.x，1.15.8，也在环境变量中加入了GO15VENDOREXPERIMENT=1
可是结果仍然不行，我的go水平不行，还请大佬赐教这是怎么回事？

ps：make menuconfig里面passwall我全选了

**Comment by hcym** [comment]
编译了正常的，梯子问题吧，go编译要求比较高

**Comment by Debbie-Yuan** [comment]
> 编译了正常的，梯子问题吧，go编译要求比较高

emmm梯子挺好啊测速满200，刚才又尝试了一次，是一定要执行make clean再重试嘛，

**Comment by Debbie-Yuan** [comment]
> 编译了正常的，梯子问题吧，go编译要求比较高

这是最新的错误了，刚才的三个减少到一个了
**错误信息**
`Building targets
github.com/lucas-clemente/quic-go/internal/qtls
github.com/lucas-clemente/quic-go/internal/qtls
pkg/mod/github.com/lucas-clemente/quic-go@v0.19.3/internal/qtls/qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate
note: module requires Go 1.14`

**Comment by xiaorouji** [comment]
请更新Go到1.15以上

**Comment by xiaorouji** [comment]
是openwrt packages里面的golang，而不是本机Go版本

**Comment by Debbie-Yuan** [comment]
> 是openwrt packages里面的golang，而不是本机Go版本

好的，我现在正在按照lede里：https://github.com/coolsnowwolf/lede/issues/6289添加xray源并更新feeds重试，稍后我尝试您的方法！谢谢！

**Comment by Debbie-Yuan** [comment]
> 是openwrt packages里面的golang，而不是本机Go版本

看来要用您的方法，请问大佬具体怎么操作啊

**Comment by Debbie-Yuan** [comment]
> 是openwrt packages里面的golang，而不是本机Go版本

我发现我的packages里面没有lang这个文件夹，我说呢，按照您说的我已经openwrt/packages里面clone了，并放在自己的文件夹里面去，我先尝试一下可以不哈，谢谢您的指导！

**Comment by Debbie-Yuan** [comment]
> 是openwrt packages里面的golang，而不是本机Go版本

啊大佬，还是您说下怎么更新packages里的golang吧，我已经从packages仓库里面下下来并且放到本机的packages/lang下了，并且make menuconfig里面也选择了golang，可是还是有那个`qtls.go:79:25: cannot convert cert (type *tls.Certificate) to type *qtls.Certificate`的报错，到底应该怎么操作啊

**Comment by hcym** [comment]
要是go版本过低就用官方最新分支编译最简单
我一直用master分支，编译正常，熟悉了再考虑单独更换包包。

**Comment by Debbie-Yuan** [comment]
> 要是go版本过低就用官方最新分支编译最简单
> 我一直用master分支，编译正常，熟悉了再考虑单独更换包包。

好的，等下我切换到master分支去再编译下，谢谢您！

**Comment by MrMatttw** [comment]
以下为解决go依赖的方案：
编辑openwrt/feeds/packages/lang/golang/golang-version.mk文件，修改其中的GO_VERSION_MAJOR_MINOR:=1.15，GO_VERSION_PATCH:=8，之后修改openwrt/feeds/packages/lang/golang/golang/Makefile文件，修改PKG_HASH:=540c0ab7781084d124991321ed1458e479982de94454a98afab6acadf38497c2。重新编译就好

**Comment by Debbie-Yuan** [comment]
> 以下为解决go依赖的方案：
> 编辑openwrt/feeds/packages/lang/golang/golang-version.mk文件，修改其中的GO_VERSION_MAJOR_MINOR:=1.15，GO_VERSION_PATCH:=8，之后修改openwrt/feeds/packages/lang/golang/golang/Makefile文件，修改PKG_HASH:=540c0ab7781084d124991321ed1458e479982de94454a98afab6acadf38497c2。重新编译就好

谢谢大佬！成功了！
