### ISSUE TITLE
IPv6 TProxy的相关问题

### ISSUE THREAD

**Issue by Jingye-Xia** [xiaorouji/openwrt-passwall#963]
已经打开了IPv6透明代理(TProxy)实验选项，但日志里可以看到：

`TCP默认代理：使用TCP节点 [全局代理](REDIRECT:1041)代理所有端口`

是否代表并没有改用TProxy，实测ipv6test网站也无法获取到vps的IPv6地址。
@xiaorouji

**Comment by xiaorouji** [comment]
我这里没有ipv6环境，不太清楚
@ShanStone

**Comment by Jingye-Xia** [comment]
[passwall.txt](https://github.com/xiaorouji/openwrt-passwall/files/5973878/passwall.txt)
这是日志 @ShanStone

**Comment by Jingye-Xia** [comment]
> 我这里没有ipv6环境，不太清楚
> @ShanStone

您指的是使用IPv6 TProxy是本地需要有IPv6环境还是指vps端需要有IPv6环境？

**Comment by ShanStone** [comment]
> > 我这里没有ipv6环境，不太清楚
> > @ShanStone
> 
> 您指的是使用IPv6 TProxy是本地需要有IPv6环境还是指vps端需要有IPv6环境？

如果开启ipv6的TProxy日志是这一句：节点类型:xray，开启实验性IPv6透明代理(TProxy)...
IPv6的TProxy需要ip6tables和tproxy模块支持，makefile里已经有tproxy依赖了，只要确保有ip6tables就行
我的测试环境是nat6，节点支持ipv6，其他也没条件测试。如果你的电脑获取的是fe80::等本地地址，各种系统默认是不会走IPv6的，可以通过访问ipv6.google.com来确认TProxy代理是否正常，能访问代表IPv6代理已经正常了

**Comment by kxjhcmc** [comment]
测试，该功能使用正常

**Comment by Jingye-Xia** [comment]
> 测试，该功能使用正常

你是本地网络就有ipv6环境还是单纯通过vps代理ipv6？
另外，ipv6test网站测试能10分通过吗？

**Comment by kxjhcmc** [comment]
本地就有IPv6,IPv6也能透明代理，完美

**Comment by hcym** [comment]
很早就行的，就是没有ping值，不能负载均衡，现在我的几个节点速度慢了，就没用了
