### ISSUE TITLE
请求去除xray geodata依赖,空间不足

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#966]
16M ROM 刷完后可用空间有56KB,勉强够用,但是未来系统更新后可能不够用了.
建议改为手动更新方式.

**Comment by WYC-2020** [comment]
啥子鬼哦会占用那么多空间没搞错

**Comment by ShanStone** [comment]
16G 不够用？你确定是16G不是16M，还是你编译的时候没改过固件空间大小

**Comment by tritu** [comment]
geodata should be configurable only and not be compulsorily dependent

**Comment by lededev** [comment]
我提一个折中方案吧，这个方案设为可选平时不开启，供固件闪存窘迫时使用。
当xray选项启用时增加xz打包子选项，该选项启用时：
由passwall编译时负责下载和用xz最大压缩率压缩geodata并打包进passwall安装包，xray包取消geodata选项。
passwall启用zram zstd编译选项。
passwal服务启动时mount一个zram zstd ramdisk到/tmp/geozram/，并将被xz打包的geodata解压进此ramdisk目录，然后将xray的配置文件中默认geodata位置指向此ramdisk路径。
passwall服务停止并结束xray后，解除这个zram mount。

**Comment by z826540272** [comment]
> 我提一个折中方案吧，这个方案设为可选平时不开启，供固件闪存窘迫时使用。
> 当passwall的xray选项启用时增加xz打包geodata子选项，该选项启用时：
> 由passwall编译时负责下载和用xz最大压缩率压缩geodata并打包进passwall安装包，xray包取消geodata选项。
> passwall启用zram zstd编译选项。
> passwal服务启动时mount一个zram zstd ramdisk到/tmp/geozram/，并将被xz打包的geodata解压进此ramdisk目录，然后将xray的配置文件中默认geodata位置指向此ramdisk路径。
> passwall服务停止并结束xray后，解除这个zram mount。
> 
> 如果闪存依然不足，那只能考虑接管xray包的构建，将xray执行文件一起打包进上述xz，使用xray时将之解压到上述zram disk再执行。
> 
> 要是这样都还不行，那就在首次启动xray时，先采用不使用geodata的配置启动xray，然后通过代理下载geodata到/tmp/geozram/，重新配置xray使用geodata并重启。

没必要吧,目前的功能没有GEODATA也能正常使用,这个可以作为可选功能

**Comment by dwj0** [comment]
你可以编辑Makefile文件，去除这行依赖
