### ISSUE TITLE
编译失败(;´༎ຶД༎ຶ`)

### ISSUE THREAD

**Issue by jh0072110** [xiaorouji/openwrt-passwall#967]
make[3]: *** [/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-1.8.0/.built] Error 1
11071
Makefile:74: recipe for target '/workdir/openwrt/build_dir/target-x86_64_musl/v2ray-plugin-1.8.0/.built' failed
11072
make[3]: Leaving directory '/workdir/openwrt/package/openwrt-passwall/v2ray-plugin'
11073
make[2]: *** [package/openwrt-passwall/v2ray-plugin/compile] Error 1
11074
time: package/openwrt-passwall/v2ray-plugin/compile#0.61#0.19#5.99
11075
make[1]: *** [/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile] Error 2
11076
    ERROR: package/openwrt-passwall/v2ray-plugin failed to build.
11077
make: *** [world] Error 2
11078
package/Makefile:112: recipe for target 'package/openwrt-passwall/v2ray-plugin/compile' failed
11079
make[2]: Leaving directory '/workdir/openwrt'
11080
package/Makefile:108: recipe for target '/workdir/openwrt/staging_dir/target-x86_64_musl/stamp/.package_compile' failed
11081
make[1]: Leaving directory '/workdir/openwrt'
11082
/workdir/openwrt/include/toplevel.mk:228: recipe for target 'world' failed
11083
Error: Process completed with exit code 2.

**Comment by ShanStone** [comment]
没看出来什么原因，只知道是v2ray-plugin编译失败了，有可能是upx压缩支持的问题

**Comment by Myoko** [comment]
v2ray 取消了 现在没必要编译V2 Plug了

**Comment by jh0072110** [comment]
> v2ray 取消了 现在没必要编译V2 Plug了

现在的plugin好像是teddysun在维护，也不能说完全没用吧，我在极偶然的情况下也会用用ss(⁎⁍̴̛ᴗ⁍̴̛⁎)

**Comment by jh0072110** [comment]
> 没看出来什么原因，只知道是v2ray-plugin编译失败了，有可能是upx压缩支持的问题

也许是个偶然情况 我再试试(;´༎ຶД༎ຶ`)

**Comment by jh0072110** [comment]
emmm依旧失败=。=还是v2ray-plugin报错……
上一次成功编译是 bf40e67 大佬们拜年累了可以研究一下是哪里出问题了=。=
新年快乐～

**Comment by ShanStone** [comment]
make V=s
再给个详细点的报错日志，要包括出错的内容，要不只能给你算一卦哪里出错了

**Comment by jh0072110** [comment]
> make V=s
> 再给个详细点的报错日志，要包括出错的内容，要不只能给你算一卦哪里出错了

咳咳 那不能让大佬算卦=。=附上github actions日志
[11_Compile the firmware.txt](https://github.com/xiaorouji/openwrt-passwall/files/5975352/11_Compile.the.firmware.txt)

**Comment by ShanStone** [comment]
> > make V=s
> > 再给个详细点的报错日志，要包括出错的内容，要不只能给你算一卦哪里出错了
> 
> 咳咳 那不能让大佬算卦=。=附上github actions日志
> [11_Compile the firmware.txt](https://github.com/xiaorouji/openwrt-passwall/files/5975352/11_Compile.the.firmware.txt)

日志里显示下载需要的go模块的时候被重定向超过了10次，然后报错了，只能说是网络方面的问题，具体哪里出了问题不好说

**Comment by jh0072110** [comment]
> > > make V=s
> > > 再给个详细点的报错日志，要包括出错的内容，要不只能给你算一卦哪里出错了
> > 
> > 
> > 咳咳 那不能让大佬算卦=。=附上github actions日志
> > [11_Compile the firmware.txt](https://github.com/xiaorouji/openwrt-passwall/files/5975352/11_Compile.the.firmware.txt)
> 
> 日志里显示下载需要的go模块的时候被重定向超过了10次，然后报错了，只能说是网络方面的问题，具体哪里出了问题不好说

这个确实不太好定位了…不过之前编译没有出过问题来着……

**Comment by a1094174619** [comment]
在github actions编译xray，我也出现了这个问题，倒腾一天了，没找到解决办法，在makefile中设置export GOPROXY=https://proxy.io  也不行，猜测是微软的服务器不能访问proxy.golang.com.cn。


日志链接 https://github.com/a1094174619/lede_actions/runs/1895758998?check_suite_focus=true

**Comment by wangziyannb** [comment]
> 在github actions编译xray，我也出现了这个问题，倒腾一天了，没找到解决办法，在makefile中设置export GOPROXY=https://proxy.io 也不行，猜测是微软的服务器不能访问proxy.golang.com.cn。
> 
> 日志链接 https://github.com/a1094174619/lede_actions/runs/1895758998?check_suite_focus=true

实测换成https://proxy.golang.org也不行，但是有错误码（410），至少知道应该不是网络问题
错误如下：
not found: github.com/v2fly/v2ray-core@v4.34.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required

**Comment by a1094174619** [comment]
github actions编译 取消Network->project V->Compiling with GOPROXY proxy默认选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/

**Comment by bigbighill** [comment]
> github actions编译 取消Network->project V->Compiling with GOPROXY proxy默认选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/

可以分享下.config文件吗，想看看 Compiling with GOPROXY proxy 对应.config文件中对应项

**Comment by lxhao61** [comment]
> github actions编译 取消Network->project V->Compiling with GOPROXY proxy默认选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/

你这个方法，测试编译成功，无问题。

**Comment by jh0072110** [comment]
> github actions编译 取消Network->project V->Compiling with GOPROXY proxy默认选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/

成功+1

**Comment by BapiGso** [comment]
> github actions编译取消Network-> Project V->使用GOPROXY proxy编译选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/

成功了，太感谢了

**Comment by uclee888** [comment]
> github actions编译 取消Network->project V->Compiling with GOPROXY proxy默认选项就行了，不走代理，微软的服务器可以直接访问https://proxy.golang.org/
good！

**Comment by tejing** [comment]
.config文件的参数名是CONFIG_v2ray-plugin_INCLUDE_GOPROXY    is not set

**Comment by eightsheep67** [comment]
尝试一下T-T，已经浪费了我快2000分钟的额度了

**Comment by yaleyip** [comment]
选取
Network->project V->Compiling with GOPROXY proxy

不用代理，成功编译。
