### ISSUE TITLE
adguardhome 替换 dnsmasq

### ISSUE THREAD

**Issue by ritech** [xiaorouji/openwrt-passwall#969]
新版版0.105.0已出，支持ipset ，希望passwall gfwlist翻墙模式改用adguardhome dns 服务

**Comment by xiaobaishu1** [comment]
那是不是不用adguardhome就不能用这个了？

**Comment by xiaorouji** [comment]
给32M ROM留条活路吧...

**Comment by lededev** [comment]
在smartdns的自定义设置里面加这么一行就可以实现广告过滤了，要啥adguardhome。
`conf-file /etc/smartdns/anti-ad-smartdns.conf`
所以目前我对正在用的chinadns-ng=>smartdns方案很满意。

**Comment by ritech** [comment]
> 在smartdns的自定义设置里面加这么一行就可以实现广告过滤了，要啥adguardhome。
> `conf-file /etc/smartdns/anti-ad-smartdns.conf`
> 所以目前我对正在用的chinadns-ng=>smartdns方案很满意。

adguardhome 不仅仅屏蔽广告啊， 我觉得dns查询并发上效率很高

**Comment by lededev** [comment]
> adguardhome 不仅仅屏蔽广告啊， 我觉得dns查询并发上效率很高

smartdns也不仅仅屏蔽广告啊，smartdns总能得到离你最近的结果IP，无论走直连还是走代理。
查询快有P用，解析出来的网站速度快才真的提升速度。
何况smartdns才100多KB大小，放路由器里正合适。

**Comment by lededev** [comment]
另外分享一下我用的smartdns广告屏蔽文件的更新脚本，放在cron.weekly等等定时执行的位置比较合适。
update-smartdns-anti-ad
```
#!/bin/sh

AD_PATH=/tmp/anti-ad-for-smartdns.conf
SM_AD_PATH=/etc/smartdns/anti-ad-smartdns.conf

docp=0
/bin/rm -f $AD_PATH
if wget -q -P /tmp https://anti-ad.net/anti-ad-for-smartdns.conf; then
  if cmp -s $SM_AD_PATH $AD_PATH
  then
    /bin/rm -f $AD_PATH
    exit 0
  else
    /bin/mv -f $AD_PATH $SM_AD_PATH
    docp=1
  fi
fi

if [ $docp -eq 1 ]; then
  /etc/init.d/smartdns restart
fi

```

**Comment by tedaz** [comment]
如果手动修改的，请问如何修改passwall的配置文件以调整passwall的chinadns-ng的监听端口？

**Comment by lededev** [comment]
> 如果手动修改的，请问如何修改passwall的配置文件以调整passwall的chinadns-ng的监听端口？

#940 里面我截图了最新版本下的设置方法，以我最后发文的截图为准，实际上没改chinadns-ng的监听端口，改的是chinadns-ng到smartdns的端口，cn port设置成5353(这个可以改，和smartdns里cn port设置一致就行)，smartdns us port必须是7913，这个不能改，目前passwall的脚本里面就这么对chiandns-ng设定的。

**Comment by tianiue** [comment]
最近passwall用着会出现突然不能访问网页，和smartdns也有些冲突

**Comment by lededev** [comment]
> 最近passwall用着会出现突然不能访问网页，和smartdns也有些冲突

我也遇到过，看日志是节点自动切换造成的，但关掉又怕节点真的无效了，不切换一直断开，更难受。

**Comment by ritech** [comment]
> > 最近passwall用着会出现突然不能访问网页，和smartdns也有些冲突
> 
> 我也遇到过，看日志是节点自动切换造成的，但关掉又怕节点真的无效了，不切换一直断开，更难受。

TCP直连代理使用链2

貌似是这个问题，可以启用自动切换，把TCP 恢复切换打开
