### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by MrMatttw** [xiaorouji/openwrt-passwall#972]
使用源Lieno大神的master branch;
已开启全局科学上网
不加passwall可正常编译，加入passwall后报错信息如下：

Finding targets
go: downloading github.com/v2fly/v2ray-core v4.34.0+incompatible

Building targets
go: downloading github.com/v2fly/v2ray-core v4.34.0+incompatible
../../main.go:18:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:20:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:37:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:21:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:22:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:23:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../errors.generated.go:3:8: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:38:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:25:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:40:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:26:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:27:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:29:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:30:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:32:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:33:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:34:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects
../../main.go:35:2: github.com/v2fly/v2ray-core@v4.34.0+incompatible: Get "https://proxy.golang.com.cn/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.zip": stopped after 10 redirects

make[2]: *** [Makefile:77: /home/matthew/openwrt/build_dir/target-mips_24kc_musl/v2ray-plugin-1.8.0/.built] Error 1
make[2]: Leaving directory '/home/matthew/openwrt/feeds/xiaorouji/v2ray-plugin'
time: package/feeds/xiaorouji/v2ray-plugin/compile#0.39#0.12#14.29
    ERROR: package/feeds/xiaorouji/v2ray-plugin failed to build.
make[1]: *** [package/Makefile:114: package/feeds/xiaorouji/v2ray-plugin/compile] Error 1
make[1]: Leaving directory '/home/matthew/openwrt'
make: *** [/home/matthew/openwrt/include/toplevel.mk:230: package/luci-app-passwall/compile] Error 2

请大大详解！自行下载了那个包，放进了openwrt/dl文件夹下不起作用

**Comment by jh0072110** [comment]
#967 你可以跟我并成一个issue ಠ_ಠ

**Comment by MrMatttw** [comment]
> #967 你可以跟我并成一个issue ಠ_ಠ

好像可以hhhh

**Comment by stephenchou888** [comment]
Fork大佬的这个源
然后在ACTIONS中修改成自己的这个源
在luci-app-passwall/Makefile
文件中将
config PACKAGE_$(PKG_NAME)_INCLUDE_v2ray-plugin
	bool "Include v2ray-plugin (Shadowsocks plugin)"
	default y if i386||x86_64||arm||aarch64
改成
	default n if i386||x86_64||arm||aarch64
就可以了。

**Comment by firkerword** [comment]
同样的问题  有大佬成功了吗

**Comment by firkerword** [comment]
> Fork大佬的这个源
> 然后在ACTIONS中修改成自己的这个源
> 在luci-app-passwall/Makefile
> 文件中将
> config PACKAGE_$(PKG_NAME)_INCLUDE_v2ray-plugin
> bool "Include v2ray-plugin (Shadowsocks plugin)"
> default y if i386||x86_64||arm||aarch64
> 改成
> default n if i386||x86_64||arm||aarch64
> 就可以了。
么
其实就是去掉v2ray-plugin编译吧  passwall里面是默认编译的  config里注释一下就可以

**Comment by stephenchou888** [comment]
L大是默认这个插件自动添加编译进固件的，所以要把默认改成不添加编译就可以顺利执行ACTIONS了

**Comment by jh0072110** [comment]
> Fork大佬的这个源
> 然后在ACTIONS中修改成自己的这个源
> 在luci-app-passwall/Makefile
> 文件中将
> config PACKAGE_$(PKG_NAME)_INCLUDE_v2ray-plugin
> bool "Include v2ray-plugin (Shadowsocks plugin)"
> default y if i386||x86_64||arm||aarch64
> 改成
> default n if i386||x86_64||arm||aarch64
> 就可以了。

你这不是解决问题啊 你这是解决提出问题的人啊(●°u°●)​ 」

**Comment by wangziyannb** [comment]
我看是重定向，还以为是梯子网络问题，给make里的goproxy变量换成了https://proxy.golang.org。然而还是出错，go跑到https://proxy.golang.org/github.com/v2fly/v2ray-core/@v/v4.34.0+incompatible.mod
去拉包了，整了个
not found: github.com/v2fly/v2ray-core@v4.34.0+incompatible: invalid version: +incompatible suffix not allowed: module contains a go.mod file, so semantic import versioning is required
的错误（410）
自己对go没有太多了解，无路可走，只能不安装v2ray-plugin了（哭

**Comment by dgnanhe** [comment]
rm -rf package/feeds/passwall/v2ray 删除v2ray目录就能成功。

**Comment by Noo13-man** [comment]
编译的时候取消下面几个就可以了。
**Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)

Network ---> Project V (全部取消勾选)**

**Comment by MrMatttw** [comment]
> 编译的时候取消下面几个就可以了。
> 
> Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)
> 
> Network ---> Project V (全部取消勾选)

问题是需要使用v2ray T T

**Comment by MrMatttw** [comment]
> > Fork大佬的这个源
> > 然后在ACTIONS中修改成自己的这个源
> > 在luci-app-passwall/Makefile
> > 文件中将
> > config PACKAGE_$(PKG_NAME)_INCLUDE_v2ray-plugin
> > bool "Include v2ray-plugin (Shadowsocks plugin)"
> > default y if i386||x86_64||arm||aarch64
> > 改成
> > default n if i386||x86_64||arm||aarch64
> > 就可以了。
> 
> 你这不是解决问题啊 你这是解决提出问题的人啊(●°u°●)​ 」

还有一个问题在于，我是编译给wndr4300路由器使，是ath79平台。另外暗搓搓问一句，有没有用ath79平台编译出来以后刷不进路由器的....

**Comment by MrMatttw** [comment]
> rm -rf package/feeds/passwall/v2ray 删除v2ray目录就能成功。

我去试试！

**Comment by SunHuey** [comment]
> rm -rf package/feeds/passwall/v2ray 删除v2ray目录就能成功。

我试了 没用还是报错

**Comment by 70599** [comment]
> > 编译的时候取消下面几个就可以了。
> > Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)
> > Network ---> Project V (全部取消勾选)
> 
> 问题是需要使用v2ray T T

功能上看，目前v2ray是xray的子集，xray应该可以满足你的需求。
如果你要的是plugin就不知道了。

**Comment by jh0072110** [comment]
> > > 编译的时候取消下面几个就可以了。
> > > Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)
> > > Network ---> Project V (全部取消勾选)
> > 
> > 
> > 问题是需要使用v2ray T T
> 
> 功能上看，目前v2ray是xray的子集，xray应该可以满足你的需求。
> 如果你要的是plugin就不知道了。

现在遇到问题的都是需要v2ray-plugin的，不是需要v2ray的ಠ_ಠ

**Comment by SunHuey** [comment]
> > > > 编译的时候取消下面几个就可以了。
> > > > Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)
> > > > Network ---> Project V (全部取消勾选)
> > > 
> > > 
> > > 问题是需要使用v2ray T T
> > 
> > 
> > 功能上看，目前v2ray是xray的子集，xray应该可以满足你的需求。
> > 如果你要的是plugin就不知道了。
> 
> 现在遇到问题的都是需要v2ray-plugin的，不是需要v2ray的ಠ_ಠ

怎么解决这个问题啊？

**Comment by SunHuey** [comment]
> > > > > 编译的时候取消下面几个就可以了。
> > > > > Luci ---> Applications ---> Luci-app-passwall ---> Include v2ray-plugin (Shadowsocks plugin)
> > > > > Network ---> Project V (全部取消勾选)
> > > > 
> > > > 
> > > > 问题是需要使用v2ray T T
> > > 
> > > 
> > > 功能上看，目前v2ray是xray的子集，xray应该可以满足你的需求。
> > > 如果你要的是plugin就不知道了。
> > 
> > 
> > 现在遇到问题的都是需要v2ray-plugin的，不是需要v2ray的ಠ_ಠ
> 
> 怎么解决这个问题啊？

按照上面取消那些选项可以编译成功

**Comment by William1204** [comment]
小白第一次用虚拟机，我尝试改了feeds下v2ray-plugin makefile，#掉了GOPROXY 结果发现没有用，那这个改cn镜像加速的调用的命令是在哪里？我本地直接#掉就行了吧？

**Comment by jh0072110** [comment]
https://github.com/xiaorouji/openwrt-passwall/issues/967#issuecomment-778777911
我的issue里有大佬解决了这个问题

**Comment by tianiue** [comment]
v2ray切换到xray，去掉v2ray这样应该也不影响使用
