### ISSUE TITLE
Xray分流Rule貌似不能自己添加

### ISSUE THREAD

**Issue by TwoBall** [xiaorouji/openwrt-passwall#974]
我在网页上添加特定的Rule，发现`/var/etc/passwall/TCP.json`也没有相应的路由规则生成。

不知道是否为bug。 @xiaorouji

**Comment by 70599** [comment]
我这里4-15版本没有这个问题。

**Comment by xiaorouji** [comment]
没有复现，因为我正在用。

**Comment by TwoBall** [comment]
> 没有复现，因为我正在用。

我复现了一下，发现是浏览器的问题，我用edge和Safari没有问题，但是百分浏览器（chrome）保存不了
