### ISSUE TITLE
PDNSD 查询不稳定,经常超时

### ISSUE THREAD

**Issue by z826540272** [xiaorouji/openwrt-passwall#977]
手动设置dnsmasq缓存为0,然后使用nslookup 查询 google.com.hk,多次查询之后会有一段时间的超时
可以确认不是线路问题,因为这时候打开没有被封的网站是走的代理,并且过程稳定.
导致有些时候打不开谷歌网站.

**Comment by z826540272** [comment]
发现把查询地址改成1.1.1.1就很稳定了,8.8.4.4不稳定.
但是,改成使用UDP解析之后,nslookup查询10次google.com.hk能有一次解析成功,其他全部超时.
但是我nslookup google.com.hk 8.8.4.4 却能每次成功，应该是有bug，希望修复

**Comment by xiaorouji** [comment]
用dns2socks的话会经常超时不？

**Comment by z826540272** [comment]
没socks服务器，这个问题异常烦人，因为出现几率不固定
好像我直接去查询7913和7914端口是通的，但是直接去查127.0.0.1 53却又不通。每次故障时间10-30秒左右。

**Comment by z826540272** [comment]
开启socks服务器,使用dns2socks可以正常解析,不过解析国内网站的结果和默认的pdnsd模式不一样,不知道是不是DNS全局走了代理

**Comment by CoolCollin** [comment]
我也发现最新的编译有同样的问题，pdnsd导致负载均衡无法启动，udp模式可以，但也经常无法连接。所以回退到了最早的415. 保留本地dns那个版本就暂时没问题。

**Comment by xiaorouji** [comment]
> 观察了下,dns2socks是配合chinadns运作的,请问dns2socks请求的socks服务器是不是xray程序本身提供的
不是，dns2socks是使用socks去请求TCP DNS，效果和pdnsd的TCP请求应该是一样。

**Comment by z826540272** [comment]
> > 观察了下,dns2socks是配合chinadns运作的,请问dns2socks请求的socks服务器是不是xray程序本身提供的
> 
> 不是，dns2socks是使用socks去请求TCP DNS，效果和pdnsd的TCP请求应该是一样。

目前用的dns2socks基本没发现这种现象了，报个bug
选择用udp节点解析 大概率每次都超时5秒返回，应该是chinadns-ng的bug，不通过chinadns-ng进行udp解析没有问题。已经给chinadns反馈
