### ISSUE TITLE
开启IPv6 TProxy后无法访问路由器的IPv6端口

### ISSUE THREAD

**Issue by WROIATE** [xiaorouji/openwrt-passwall#979]
使用今天编译的4-15版本，出现开启IPv6代理后无法访问路由器本机端口的情况
复现为在本地内网中正常，在外网服务器上curl本机的路由器界面超时，ssh连接超时
关闭IPv6 TProxy后恢复正常

**Comment by WROIATE** [comment]
分别测试了国内外的服务器，开启IPv6 TProxy后国内服务器可以访问端口，国外的服务器不行

**Comment by ShanStone** [comment]
模式使用的大陆列表以外？tcp转发端口选择常用时会代理22,25,53,143,465,587,993,995,80,443端口。
可以把ssh端口换个不常用的试试，或者把路由器自身TCP代理模式改成不代理试试

**Comment by WROIATE** [comment]
@ShanStone 
是使用大陆列表和游戏模式的
试了按照 `常用+换端口` 是可以解决，我也感觉应该是被转发到服务器了，但这属于正常情况吗？外部访问的回程也会被转发吗？

**Comment by WROIATE** [comment]
还有我尝试使用 `不转发ssh端口+转发所有tcp` 的方法不管用，按照不转发端口的优先级来说应该是可以的吧

**Comment by ShanStone** [comment]
> @ShanStone
> 是使用大陆列表和游戏模式的
> 试了按照 `常用+换端口` 或 `改变路由本机代理为GFW` 是可以解决，我也感觉应该是被转发到服务器了，但这属于正常情况吗？外部访问的回程也会被转发吗？

1.正常，大陆列表外含义就是不是大陆的ip统统转发到代理，路由器想回应境外服务器，流量就会被转发到代理
2.外部访问的回程目标ip是本机地址，规则也是按照设置规则的代理，所以gfw和白名单模式下不会被转发
3.解决方法有更改本机代理模式，加入不代理端口，把服务器域名或ip加到直连名单里
4.不转发端口优先级最高，不转发ssh端口+转发所有tcp应该是可行的。我这里看了一下ip6tables是正常的，这个功能应该是可以正常工作的

**Comment by WROIATE** [comment]
@ShanStone 
我现在使用 `不转发ssh端口+转发所有tcp` 还是不行，这是passwall output的防火墙，2222端口是修改后的ssh端口
![Snipaste_2021-02-18_00-39-51](https://user-images.githubusercontent.com/44677306/108236448-e3b5e280-7181-11eb-89b3-5c864725e371.png)

**Comment by ShanStone** [comment]
ssh后执行
ip6tables -t mangle -I PSW_OUTPUT 4 -p tcp -m multiport --sport 2222 -j RETURN
看看能用2222端口访问不

**Comment by WROIATE** [comment]
> ssh后执行
> ip6tables -t mangle -I PSW_OUTPUT 4 -p tcp -m multiport --sport 2222 -j RETURN
> 看看能用2222端口访问不

可以了，缺了这条规则是代码问题还是我操作不当？
顺便@xiaorouji 大佬来看看
