### ISSUE TITLE
pw+smartdns 无效？

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#981]
先贴几张我的配置
![image](https://user-images.githubusercontent.com/34025388/108141064-fd154b00-70fd-11eb-9cca-a65fe2843c21.png)
![image](https://user-images.githubusercontent.com/34025388/108141084-09010d00-70fe-11eb-9e46-a7d798844625.png)
![image](https://user-images.githubusercontent.com/34025388/108141033-ed960200-70fd-11eb-95d9-5a611b168c8f.png)

以上就是配置，但是在最新版本上发现出国没法解析，看日志感觉没啥不对的，不知道哪里问题，那位大佬这样用的 说下 是我配置哪里有问题还是咋的，以前版本我这样配置是完全没问题的，也是pw+china-ng+smartdns

**Comment by WYC-2020** [comment]
![image](https://user-images.githubusercontent.com/34025388/108141270-58dfd400-70fe-11eb-9cb6-584049ef20d1.png)
最后一张截图错误，如果换成这样
![image](https://user-images.githubusercontent.com/34025388/108141309-6bf2a400-70fe-11eb-9225-bf187ff4486a.png)
就可行，不知道是那个步骤问题

**Comment by WYC-2020** [comment]
改成用第一第二服务器搞定，不知道为啥命令不行

**Comment by xiaorouji** [comment]
这是因为你自定义smartdns没有监听TCP，你监听TCP即可，或者改成通过UDP节点请求DNS

**Comment by WYC-2020** [comment]
@xiaorouji 嗯刚看了一下命令bind-tcp就可以
