### ISSUE TITLE
openwrt master最新的源码，选择haproxy会提示Packages for libreadline8 found, but incompatible with the architectures configured

### ISSUE THREAD

**Issue by tinnlux** [xiaorouji/openwrt-passwall#982]
个人感觉是这两天源码修改abi相关代码的事回滚代码到b12288fa69b171f7c9405518c9bed3581a06f7ce之前都可以正常编译通过。错误如下，求各位大佬帮忙分析下如何解决，谢谢：
pkg_hash_fetch_best_installation_candidate: Packages for libreadline8 found, but incompatible with the architectures configured
opkg_install_cmd: Cannot install package libreadline8.

**Comment by hcym** [comment]
官方依赖问题，我用官方编译，没有pass只有haproxy也是这个错误

**Comment by tinnlux** [comment]
> 官方依赖问题，我用官方编译，没有pass只有haproxy也是这个错误
@hcym 
是的，有错误，我感觉应该不是依赖问题，所以想问问怎么修复，因为这个并不是所有package都会出错，我看了看应该是前天改了abi的相关代码后出现的，这个更改不可能回滚了，只能想办法更改出错误的package的代码来适应主线新的改变。

**Comment by xiaorouji** [comment]
官方最近在大更，应该会搞上5.10内核，出问题也正常，等官方修复吧。

**Comment by tinnlux** [comment]
> 官方最近在大更，应该会搞上5.10内核，出问题也正常，等官方修复吧。

@xiaorouji 谢谢大佬
