### ISSUE TITLE
开启passwall后微信打开公众号，朋友圈照片加载缓慢

### ISSUE THREAD

**Issue by brucelau1987** [xiaorouji/openwrt-passwall#983]
如题，更换很多版本都一样，关闭一切正常，秒开，打开后基本要等5秒钟，跟换ssr，缓解很多，还是喜欢passwall，希望快快有没有类似问题的处理办法！谢谢！

**Comment by eightsheep67** [comment]
感觉像是DNS模块的问题，我最近也是，想用XRAY DNS (DOH)，但是用一会儿就突然其他页面都打不开了，关闭PASSWALL就好了，我就把本地解析换成默认了，感觉好一些。

**Comment by yazawaniconii** [comment]
> 感觉像是DNS模块的问题，我最近也是，想用XRAY DNS (DOH)，但是用一会儿就突然其他页面都打不开了，关闭PASSWALL就好了，我就把本地解析换成默认了，感觉好一些。

同，之前没用xray dns就很流畅，后来用了就变得很慢，受影响的有网易云、微博、公众号，其他国内软件好像没什么问题

**Comment by xiaorouji** [comment]
检查一下本地DNS（DNSMASQ上游）

**Comment by eightsheep67** [comment]
清理了IPSET后好了，目前坚持了3天没有出现这种问题。
