### ISSUE TITLE
Passwall 与官方 OpenWRT 集成的正确姿势

### ISSUE THREAD

**Issue by LittleNewton** [xiaorouji/openwrt-passwall#984]
由于各种原因吧，个人不是很喜欢用两位 L 的固件，所以一直想把 Passwall 编译进官方的 OpenWRT 库。

我的做法是这样的。

1. 在 package 目录里建立一个目录，不妨叫做 myPack 目录
2. 在 package/myPack/ 里 `git clone` 下passwall 的最新代码
3. 然后直接 `make menuconfig`，在 TUI 界面里选择好 Passwall

有一段时间，上述的操作是管用的，但是 xray-core 升级到 1.3.0 之后吧，再编译就会出错，错误也看不到输出（或许是我不会看），反正非常恶心，满屏的输出，最后的错误的地方也不带提示。

希望能获得一个**编译+集成**的正确姿势。

**Comment by WYC-2020** [comment]
这个自己改下就可以，别人都给了解决方案

**Comment by LittleNewton** [comment]
> 这个自己改下就可以，别人都给了解决方案

解决方案有 web 链接吗？抱歉，我对这个不是很精通，刚入门编译。

**Comment by nobk** [comment]
我的方法是加个feeds：
编辑 Openwrt 根目录下的 feeds.conf.default 文件
末尾添加一行：
`src-git passwall https://github.com/xiaorouji/openwrt-passwall.git`
然后执行正常的openwrt更新步骤：
```
git pull
scripts/feeds update -a
scripts/feeds install -a
```
由于xray-core包在官方源已经存在，但目前版本比passwall的要低一些，可以强制覆盖安装passwall的xray-core
```
scripts/feeds uninstall xray-core
scripts/feeds install -p passwall -f xray-core

```
确认一下xray-core符号链接已经成功建立
`ls -l package/feeds/passwall/`

编译前需要更新保存一下.config
`make menuconfig`
再次拉取更新时如果不想进界面确认，可以快速更新.config
`make defconfig`
最后就可以编译了
`make -j$((`nproc`-1))`
如果编译出错，则输出详细编译信息排查
`make -j1 V=s`

**Comment by nobk** [comment]
我的方法是加个feeds：
编辑 Openwrt 根目录下的 feeds.conf.default 文件
末尾添加一行：
`src-git passwall https://github.com/xiaorouji/openwrt-passwall.git`
然后执行正常的openwrt更新步骤：
```
git pull
scripts/feeds update -a
scripts/feeds install -a
```
由于xray-core包在官方源已经存在，但目前版本比passwall的要低一些，可以强制覆盖安装passwall的xray-core
```
scripts/feeds uninstall xray-core
scripts/feeds install -p passwall -f xray-core

```
确认一下xray-core符号链接已经成功建立
`ls -l package/feeds/passwall/`

编译前需要更新保存一下.config
`make menuconfig`
再次拉取更新时如果不想进界面确认，可以快速更新.config
`make defconfig`
最后就可以编译了
```
make -j$((`nproc`-1))
```
如果编译出错，则输出详细编译信息排查
`make -j1 V=s`

**Comment by LittleNewton** [comment]
@nobk 非常感谢！

之前确实用过自定义 feeds 的策略，但遇到了 xray-core 冲突的问题，当时特别想弄明白这里面的集成策略，但是苦于没有好上手的教程。后来有个朋友直接告诉我说能自己建立文件夹，make 程序自己扫描 `Makefile`，然后再 TUI 里选中 Passwall.

我将进行尝试，感谢！

**Comment by hcym** [comment]
学习规范做法，谢谢啦😂

**Comment by tritu** [comment]
just add feed

**Comment by LittleNewton** [comment]
1. add feed
2. 自己建立一个文件夹，拷贝 Passwall 的源码进去

上述两种方法都可以，但两者有什么区别吗？

**Comment by 70599** [comment]
>     1. add feed
> 
>     2. 自己建立一个文件夹，拷贝 Passwall 的源码进去
> 
> 
> 上述两种方法都可以，但两者有什么区别吗？

使用的过程有区别呗

**Comment by cielpy** [comment]
可以用 Docker 来编译，不用搭环境，装好 Docker 直接跑就可以了，项目 https://github.com/cielpy/DockerOpenWrtPackagesBuilder
