### ISSUE TITLE
passwall开启后 DDNS不能正常更新IP地址

### ISSUE THREAD

**Issue by CatSamaDD** [xiaorouji/openwrt-passwall#989]
4-15版本   xray1.30
开启passwall后，路由器的DDNS功能无法正常更新IP地址
提示如下
![QQ截图20210218201950](https://user-images.githubusercontent.com/34727840/108356112-aa837e00-7226-11eb-8d73-3ffcceec865e.png)
关闭passwall后正常

代理服务器本身确认没问题，我尝试通过代理服务器用浏览器直接访问API链接可以完成IP更新。

**Comment by lededev** [comment]
我这里动态DNS正常。
你可以把ddns服务网站的域名加入passwall直连名单，然后再试试；或者反过来，加入代理名单。
动态DNS的LUCI界面“修改”按钮点开后，最后一页有读取日志功能，可以看看那个日志是否提供更详细信息。
高级设置页的选项也看一下，有没有警告信息。
