### ISSUE TITLE
本地开启DOH解析速度缓慢，网页刷新两次才能全

### ISSUE THREAD

**Issue by zhucaidan** [xiaorouji/openwrt-passwall#991]
本地的DNS模式开启为DOH后，总体解析变得很慢
极大可能在没访问过的网页第一次加载不出来图片，要刷新第二遍才行
切换到默认UDP的DNS没有此问题

**Comment by z826540272** [comment]
V2RAY DOH效率低,没有连接复用,每一个查询都要经过TLS握手.
不建议用

**Comment by zhucaidan** [comment]
> V2RAY DOH效率低,没有连接复用,每一个查询都要经过TLS握手.
> 不建议用

悲剧。。那lede有别的DOH插件能编译吗？

**Comment by jh0072110** [comment]
> V2RAY DOH效率低,没有连接复用,每一个查询都要经过TLS握手.
> 不建议用

xray不是修过DOH来着……

**Comment by Myoko** [comment]
![as](https://user-images.githubusercontent.com/3013386/108591852-cf522f80-73a5-11eb-80d0-1df2ccded70b.jpg)

过滤模式用XRAY DOH 效果也不是很理想 还是PDNSD DNS2好用

**Comment by zhucaidan** [comment]
> ![as](https://user-images.githubusercontent.com/3013386/108591852-cf522f80-73a5-11eb-80d0-1df2ccded70b.jpg)
> 
> 过滤模式用XRAY DOH 效果也不是很理想 还是PDNSD DNS2好用

过滤模式我感觉无所谓，反正都是先走TCP然后再取得IP不会被污染；但是本地就不一样了，被污染必须用DOH才能跳过

**Comment by z826540272** [comment]
现在一般没什么dns污染，有大多是http劫持
