### ISSUE TITLE
建议不要删除本地dns选项

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#997]
因为本地可能会搭配ad进行广告过滤，现在最新版是默认用的wan口的网关作为的本地dns这样没法手动控制，加入adg进行广告过滤

**Comment by xiaorouji** [comment]
请自行配置dnsmasq上游

**Comment by WYC-2020** [comment]
@xiaorouji 现在新版的china-ng不会自动设置成dnsmasq上游了？这样不会冲突？

**Comment by xiaorouji** [comment]
不会

**Comment by xiaorouji** [comment]
逻辑没有改变，如果你要设置本地自定义DNS，只需要设置dnsmasq的上游即可

**Comment by WYC-2020** [comment]
@xiaorouji 好的，因为以前是china-ng会自动设置成dnsmasq上游，所以我smartdns和adg重定向都设置成的无，保证dnsmasq只有一个上游的

**Comment by WYC-2020** [comment]
@xiaorouji 我还是revert一个提交目前用起来没问题，不revert还是可以用的，辛苦大佬了

**Comment by 70599** [comment]
以前本地dns可以设置`XRay(DoH)`，现在想本地解析走DoH是不是得另开其他的了？

**Comment by xiaorouji** [comment]
@70599 是的，经过和一些大佬的商量，觉得不应该破坏本地DNS设置，如果要自定义本地DNS，请自行配置dnsmasq的上游DNS。

**Comment by 70599** [comment]
> @70599 是的，经过和一些大佬的商量，觉得不应该破坏本地DNS设置，如果要自定义本地DNS，请自行配置dnsmasq的上游DNS。

好的。现在在用SmartDNS做本地DNS上游实现DoH、DoT
