### ISSUE TITLE
fake ip  模式手机网页无法打开youtube,google可以打开

### ISSUE THREAD

**Issue by WYC-2020** [xiaorouji/openwrt-passwall#998]
手机是小米手机，我不知道其他人又没这个问题，改成pdnsd模式就全部能打开了

**Comment by WYC-2020** [comment]
刚试了facebook 也是一样，google搜索youtube，一样打不开youtube,直接域名打开也不行，是fakeip 针对手机端浏览器有什么限制吧，目前不知道，大佬有时间看看呗

**Comment by xiaorouji** [comment]
哪个能用用哪个

**Comment by z826540272** [comment]
不建议用fake ip模式,无技术优势,有劣势

**Comment by WYC-2020** [comment]
@xiaorouji 用pdnsd就能全部打开，如果用fake的话，手机又的国外网站打不开

**Comment by WYC-2020** [comment]
@z826540272 嗯嗯，我也就试下，因为很多人说pdnsd不稳定，所以想试下其他的呵呵

**Comment by WYC-2020** [comment]
好了可以关闭了，爱折腾的去玩把，等你们玩出花样了 我再来关注
